- src/css/variables/_colors.scss
> fix typo in variable name

- src/components/molecules/SfInputNumber/SfInputNumber.js
Fix event to handle `v-model` properly.
> Fix/ SfInputNumber emit 'input' instead of 'change'

- docs/working-with-alpaca.md
Fixing an outdated link to alcapa's storybook in working-with-alpaca.md
> [docs] Fix link to alcapa's storybook

- src/components/atoms/SfButton/README.md
- src/components/atoms/SfButton/SfButton.scss
- src/components/atoms/SfButton/SfButton.stories.js
rename CSS variable and add readme.md
> add Button README.md

- README.md
- docs/working-with-alpaca.md
https://github.com/DivanteLtd/storefront-ui/issues/121
Made the shorthand name consistent
> Made the shorthand name consistent #121

- packages/vue/docs/customization.md
> fix typo and add punctuations

- packages/vue/config/storybook/home/home.js
- yarn.lock
> Storybook docs update

- packages/vue/config/storybook/home/home.js
- packages/vue/src/components/atoms/SfArrow/SfArrow.stories.js
- packages/vue/src/components/atoms/SfSticky/SfSticky.vue
Fix prettier and syntax errors on master branch. Need to merge it as soon as possible.
> fixing prettier and syntax errors

- packages/vue/src/components/molecules/SfFilter/SfFilter.html
- packages/vue/src/components/molecules/SfFilter/SfFilter.js
- packages/vue/src/components/molecules/SfFilter/SfFilter.vue
Fixed styles import and extracted single file to specyfic files
> Fixed SfFilter

- packages/vue/src/components/molecules/SfProductCard/SfProductCard.stories.js
> Fixed ProductCard story props

- packages/shared/styles/components/SfHeading.scss
- packages/shared/styles/components/SfHero.scss
- packages/vue/src/components/atoms/SfButton/SfButton.stories.js
#202
Removed unnecessary breakpoints variable
> cleaning remove unnecessary breakpoint vars

- packages/vue/src/components/organisms/SfAccordion/SfAccordion.stories.js
- packages/vue/src/examples/pages/category/Category.vue
> hotfix/sfaccordion slot's

- CONTRIBUTING.md
https://github.com/DivanteLtd/storefront-ui/issues/273
change Urls to point to new home at https://docs.storefrontui.io
> update CONTRIBUTING.md links to new home of docs

- packages/shared/styles/components/SfSelect.scss
- packages/vue/src/components/molecules/SfSelect/SfSelect.html
- packages/vue/src/components/molecules/SfSelect/SfSelect.js
> Adjusted SfSelect to mobile design

- packages/shared/styles/components/SfSidebar.scss
- packages/vue/src/components/organisms/SfBottomNavigation/SfBottomNavigation.js
- packages/vue/src/components/organisms/SfSidebar/SfSidebar.html
- packages/vue/src/components/organisms/SfSidebar/SfSidebar.js
- packages/vue/src/components/organisms/SfSidebar/SfSidebar.stories.js
> Adjusted SfSidebar

- packages/shared/styles/components/SfSelect.scss
- packages/vue/src/components/atoms/SfInput/SfInput.html
- packages/vue/src/components/molecules/SfSelect/SfSelect.html
- packages/vue/src/components/molecules/SfSelect/SfSelect.js
- packages/vue/src/components/molecules/SfSelect/SfSelect.stories.js
> Adjusted SfSelect

- packages/shared/styles/components/SfTabs.scss
- packages/vue/src/components/organisms/SfTabs/SfTabs.html
- packages/vue/src/components/organisms/SfTabs/SfTabs.stories.js
- packages/vue/src/components/organisms/SfTabs/_internal/SfTab.html
> Rewrited SfTabs styles

- packages/shared/styles/components/SfSelect.scss
- packages/vue/src/components/molecules/SfSelect/SfSelect.html
- packages/vue/src/components/molecules/SfSelect/SfSelect.js
> Rewrited SfSelect styles and used SfOverlay 

- package.json
https://github.com/DivanteLtd/storefront-ui/issues/314
Added storybook:serve script in main package.json
> Added storybook:serve script in main package.json

- package.json
Reverts DivanteLtd/storefront-ui#317 revert and move to master directly
> Revert "Added storybook:serve script in main package.json"

- packages/shared/styles/components/SfProductCard.scss
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.html
- packages/vue/src/examples/pages/category/Category.vue
- packages/vue/src/examples/pages/home/Home.vue
- packages/vue/src/examples/pages/product/Product.vue
> Adjusted SfProduct to desing

- .github/PULL_REQUEST_TEMPLATE.md
> Update component rules link on PR template

- CONTRIBUTING.md
- packages/vue/docs/assets/members.json
#381 
1. Add Eduard to core team.
2. Fix broken link in Contributing.md
> fix #381 add Eduard and fix contributing broken link

- CONTRIBUTING.md
- packages/vue/docs/contributing/github-guidelines.md
> update docs for contributing

- packages/shared/styles/components/SfStoreLocator.scss
- packages/vue/src/components/organisms/SfStoreLocator/SfStoreLocator.js
@filrak This should fix the nuxt issue, I did test it locally with yarn pack and the build succeeds, can you verify as well and let me know? thank you!
> Fix: move leaflet css loading to mounted function

- packages/vue/docs/contributing/documentation-guidelines.md
#323
Flatten hierarchy as discussed in #323.
> Flatten hierarchy of documentation-guidelines

- packages/vue/src/components/atoms/SfImage/SfImage.js
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.js
Reverts DivanteLtd/storefront-ui#428
> Revert "Fix/image responsiveness"

- packages/vue/docs/.vuepress/components/SfDocsBullets.vue
- packages/vue/docs/.vuepress/components/SfDocsCheckbox.vue
- packages/vue/docs/.vuepress/components/SfDocsLoader.vue
- packages/vue/docs/.vuepress/components/SfDocsOverlay.vue
- packages/vue/src/components/atoms/SfBullets/SfBullets.md
- packages/vue/src/components/atoms/SfCheckbox/SfCheckbox.html
- packages/vue/src/components/atoms/SfCheckbox/SfCheckbox.js
- packages/vue/src/components/atoms/SfCheckbox/SfCheckbox.md
- packages/vue/src/components/atoms/SfChevron/SfChevron.html
- packages/vue/src/components/atoms/SfChevron/SfChevron.md
- packages/vue/src/components/atoms/SfDivider/SfDivider.md
- packages/vue/src/components/atoms/SfHeading/SfHeading.md
- packages/vue/src/components/atoms/SfInput/SfInput.md
- packages/vue/src/components/atoms/SfLoader/SfLoader.html
- packages/vue/src/components/atoms/SfLoader/SfLoader.md
- packages/vue/src/components/atoms/SfOverlay/SfOverlay.js
- packages/vue/src/components/atoms/SfOverlay/SfOverlay.md
#420 [Docs] Create missing component docs
- Bullets
- Checkbox
- Chevron
- Divider
- Heading
- Input
- Loader
> Add Components Docs

- packages/vue/docs/.vuepress/components/SfDocsBreadcrumbs.vue
- packages/vue/docs/.vuepress/components/SfDocsRating.vue
- packages/vue/src/components/atoms/SfBreadcrumbs/SfBreadcrumbs.md
- packages/vue/src/components/atoms/SfCircleIcon/SfCircleIcon.md
- packages/vue/src/components/atoms/SfPrice/SfPrice.md
- packages/vue/src/components/atoms/SfProperty/SfProperty.md
- packages/vue/src/components/atoms/SfRating/SfRating.md
#420 [Docs] Create missing component docs
- Breadcrumbs
- CircleIcon
- Price
- Property
- Rating
> Add More Components Docs

- README.md
- Fixed some spelling mistakes in `README.md`.
- Found & fixed some grammatical mistakes also.
Please note that the path mentioned in the link in `Line 40` of the `README.md` **does not exist** in the `develop` branch. This is a separate issue (#478) which should be dealt in a different PR, probably.
> fix: grammar & spelling issues in README

- packages/vue/package.json
Fixes problem with index package files on local publishing and linking.
> fix: publish with index files

- packages/vue/src/components/atoms/SfCircleIcon/SfCircleIcon.js
- packages/vue/src/components/organisms/SfGroupedProduct/_internal/SfGroupedProductItem.js
Removes required props causing problems.
> fix: remove required properties causing render problems

- packages/vue/src/components/molecules/SfSelect/SfSelect.js
Fix problem with not existing ref element
> fix: reach for element of not existing ref

- packages/vue/scripts/create-root-sfui-scss.js
fix create root sfui.scss script
> bugfix/fix condition for create root sfui.scss

- packages/vue/src/components/atoms/SfCheckbox/SfCheckbox.html
- packages/vue/src/components/atoms/SfCheckbox/SfCheckbox.js
#516 
- add boolean behaviour
- get id and for from name props
> feature/add boolean way in SfCheckbox

- packages/vue/src/components/organisms/SfTabs/SfTabs.stories.js
N/A (afaik)
slightly improve SfTabs stories
> Improve SfTabs stories

- packages/vue/docs/getting-started.md
> Nuxt installation docs

- packages/shared/styles/components/SfFooter.scss
- packages/vue/src/components/organisms/SfFooter/SfFooter.js
#559 
disable click if !isMobile
> bugfix/remove SfFooter click on desktop

- README.md
N/A
Update supporters list in readme.md to match the list from docs
> Update supporters section

- packages/vue/src/components/molecules/SfFilter/SfFilter.js
- packages/vue/src/components/molecules/SfMenuItem/SfMenuItem.js
Fixed errors on numeric fields in `count` props.
> fix(props): allow numeric types in count props

- packages/vue/src/components/atoms/SfCheckbox/SfCheckbox.stories.js
update SfChecbox stories for boolean way and multiple checkboxes way
> chore/update SfCheckbox stories

- package.json
- packages/vue/package.json
- yarn.lock
#583
add linter to pre-commit
add test:unit to pre-push
> chore(convention)/ add husky pre-commit linter and pre-push unit test

- packages/vue/package.json
- yarn.lock
add percy, visual testing tool, to run it you need have token, I configure it later
> feat: add percy visual testing

- packages/shared/package.json
- packages/vue/package.json
fix package version, we release 0.4.0 and inside package we have 0.3.6
> fix: update packages version

- packages/vue/src/components/atoms/SfImage/SfImage.stories.js
> chore: update source in SfImage stories

- packages/vue/src/components/atoms/SfImage/SfImage.vue
- packages/vue/src/components/atoms/SfProperty/SfProperty.vue
-
* added Number type in SfProperty
* fixed bug in SfImage - sometimes source was null, which was not a string and template tried to access its properties
> fix: SfImage error

- packages/vue/src/examples/pages/checkout/Checkout.vue
- packages/vue/src/examples/pages/checkout/_internal/OrderSummary.vue
- packages/vue/src/examples/pages/checkout/_internal/Payment.vue
- packages/vue/src/examples/pages/checkout/_internal/PersonalDetails.vue
- packages/vue/src/examples/pages/checkout/_internal/ReviewOrder.vue
- packages/vue/src/examples/pages/checkout/_internal/Shipping.vue
> chore: adjust events names

- packages/vue/src/components/molecules/SfAddToCart/SfAddToCart.stories.js
- packages/vue/src/components/molecules/SfAddToCart/SfAddToCart.vue
- packages/vue/src/examples/pages/checkout/Checkout.vue
Null
clean after implement SfQuantitySelector in SfAddToCart
Null
> refactor: small cleaning in SfAddToCart

- lerna.json
Closes  #579
enable lerna changelog base on conventional commits
[examples](https://github.com/pspaczek/storefront-ui/tree/changelog)
> feat: add changelog

- packages/vue/package.json
- packages/vue/src/components/molecules/SfModal/SfModal.vue
- packages/vue/src/components/organisms/SfSidebar/SfSidebar.vue
- yarn.lock
> revert: vue-simple-portal

- packages/vue/src/examples/pages/checkout/Checkout.vue
> fix: import on checkout page

- packages/vue/src/components/molecules/SfAddToCart/SfAddToCart.stories.js
- packages/vue/src/components/molecules/SfBanner/SfBanner.stories.js
- packages/vue/src/examples/pages/cart/Cart.stories.js
- packages/vue/src/examples/pages/category/Category.stories.js
- packages/vue/src/examples/pages/home/Home.stories.js
- packages/vue/src/examples/pages/login/Login.stories.js
- packages/vue/src/examples/pages/product/Product.stories.js
- packages/vue/src/examples/pages/static/Static.stories.js
> chore: update stories

- packages/shared/styles/components/atoms/SfChevron.scss
- packages/vue/src/components/atoms/SfChevron/SfChevron.vue
Closes #752
- Refactor SfChevron styles - removed too many calcs
- Class name fix
If applicable:
> refactor: SfChevron styles

- packages/vue/docs/contributing/coding-guidelines.md
- packages/vue/docs/contributing/creating-new-component.md
Update and fix link contributing guide
Contributing Guide
> doc: Update contributing guide

- README.md
- packages/vue/docs/assets/members.json
> docs: add Marta Radziszewska to core team

- packages/shared/styles/components/atoms/SfCheckbox.scss
- packages/shared/styles/components/molecules/SfRadio.scss
- packages/vue/src/components/atoms/SfCheckbox/SfCheckbox.vue
- packages/vue/src/components/molecules/SfRadio/SfRadio.vue
Closes #766 
- Changed is-disabled and is-active to modifiers
- Adjusted CSS after changes
> refactor: Change is-active and is-disabled to modifiers

- packages/shared/styles/components/organisms/SfAccordion.scss
- packages/shared/styles/components/organisms/SfMegaMenu.scss
- packages/vue/scripts/create-vue-components-docs.js
None.
Update CS variable scrapper. 
Update iframe url
If applicable:
> fix: docs for CSS custom properties

- packages/shared/styles/components/atoms/SfCheckbox.scss
- packages/shared/styles/components/atoms/SfColor.scss
- packages/shared/styles/components/atoms/SfHeading.scss
- packages/shared/styles/components/atoms/SfImage.scss
- packages/shared/styles/components/molecules/SfAddToCart.scss
- packages/shared/styles/components/organisms/SfCollectedProduct.scss
- packages/shared/styles/components/organisms/SfHeader.scss
- packages/vue/src/components/atoms/SfQuantitySelector/SfQuantitySelector.vue
- packages/vue/src/components/organisms/SfHeader/SfHeader.vue
- packages/vue/src/examples/pages/category/Category.vue
Closes #
Fix few small SSR issues before release
If applicable:
> fix: small ssr bugs

- packages/vue/docs/contributing/github-guidelines.md
Closes #743
Update github guidelines
Add 'read more' links to conventional commits and our new branch flow
If applicable:
> docs: Github Guidelines update

- packages/vue/src/components/organisms/SfTabs/SfTabs.stories.js
Closes #788 
Revert removed Storybook stories knobs
None.
If applicable:
> fix: add openTab in SfTabs stories

- packages/shared/styles/variables/_colors.scss
As discussed with Marcin added the missing color for disabled text
> refactor: added color-disabled

- packages/shared/styles/components/atoms/SfOverlay.scss
- change background color and opacity for overlay
If applicable:
> refactor(atoms): SfOverlay

- packages/shared/styles/components/atoms/SfBadge.scss
- packages/shared/styles/components/atoms/SfButton.scss
- packages/shared/styles/components/atoms/SfColor.scss
adjust merged components to changes in #843
> refactor: adjust to changes in global variables

- packages/vue/src/components/molecules/SfScrollable/SfScrollable.vue
change `v-if` to `v-show`
If applicable:
> fix: ssr in SfScrollable

- packages/shared/styles/components/atoms/SfBullets.scss
Improved bullets
If applicable:
> refactor(atoms): SfBullets

- packages/shared/styles/components/atoms/SfHeading.scss
- packages/vue/src/components/atoms/SfHeading/SfHeading.vue
adjusted SfHeading styles
If applicable:
> refactor(atoms): SfHeading

- packages/shared/styles/components/atoms/SfChevron.scss
- packages/vue/src/components/atoms/SfChevron/SfChevron.stories.js
https://github.com/DivanteLtd/storefront-ui/issues/804
refactor atom/chevron, hover style added, left and right modifier and css modifiers in stories
If applicable:
> refactor(atoms): SfChevron

- packages/shared/styles/components/molecules/SfAlert.scss
> refactor(molecules): SfAlert

- packages/shared/styles/components/organisms/SfCollectedProduct.scss
- packages/shared/styles/components/organisms/SfSidebar.scss
Closes #835 
- fix the issue with bottom button on the sidebar
If applicable:
> fix: button on sidebar

- ROADMAP.md
Storefront UI Roadmap RFC. In .md file, you can find the proposition of responsibility 
🧙‍♂️ - Divante team 😎 - Community Core team 🤝 - Community
and ⛰️ - as soon as possible emoji. We add it for important for us tasks.
> [RFC] Storefront UI ROADMAP.md

- packages/shared/styles/components/atoms/SfButton.scss
- packages/shared/styles/components/molecules/SfReview.scss
- packages/vue/src/components/molecules/SfReview/SfReview.stories.js
- packages/vue/src/components/molecules/SfReview/SfReview.vue
- add slot with an icon
- adjusted styles 
- fix stories, add a story with an icon
If applicable:
> refactor(molecules): SfReview

- packages/shared/styles/components/molecules/SfPagination.scss
- packages/vue/src/components/molecules/SfPagination/SfPagination.stories.js
- packages/vue/src/components/molecules/SfPagination/SfPagination.vue
- adjusted styles
- add props of status arrows display
- updated stories
If applicable:
> refactor(molecules): SfPagination

- packages/shared/styles/helpers/_layout.scss
Closes #865 
add helpers mixin for backgrounds
If applicable:
> feat: background scss mixin

- packages/shared/styles/components/molecules/SfSlidingSection.scss
- adjusted spacers and margin
- [IMPORTANT] component needs attention and deeper refactor after design process of final layout
If applicable:
> refactor(molecules): SfSlidingSection

- packages/shared/styles/components/atoms/SfHeading.scss
> fix: font weight variable name

- packages/vue/src/components/molecules/SfPagination/SfPagination.vue
- adjusted `SfPagination` inetrnals (computed properties specifically) logic and usage to comply with their names (`canGoPrev`, `canGoNext`)
> refactor: adjust SfPagination internals

- packages/shared/styles/components/atoms/SfHeading.scss
- packages/shared/styles/components/atoms/SfInput.scss
- packages/shared/styles/components/molecules/SfSteps.scss
> fix: variable names

- packages/shared/styles/components/atoms/SfDivider.scss
> refactor(atoms): SfDivider

- packages/shared/styles/variables/_typography.scss
- packages/vue/src/components/atoms/SfHeading/SfHeading.vue
> fix: implement h1 styles, changed heading sizes

- packages/shared/styles/components/molecules/SfBanner.scss
- packages/shared/styles/components/organisms/SfBannerGrid.scss
- packages/vue/src/components/organisms/SfBannerGrid/SfBannerGrid.vue
Part of #806
* this component should be rewriten to CSS grid
If applicable:
> refactor(organisms) SfBannerGrid

- packages/shared/package.json
- packages/shared/styles/components/organisms/SfStoreLocator.scss
- packages/vue/package.json
- packages/vue/src/components/organisms/SfStoreLocator/SfStoreLocator.vue
Fixes:
* problem with leaflet causing build problems
* problem with not using exact version of shared package, to avoid problems in future
* deleted check for *.scss stylelint, as it has some working issue, showed error without pointing that. @pspaczek I think it should be fixed with next release separately
> fix: build problems in 0.6.3

- packages/vue/src/components/atoms/SfQuantitySelector/SfQuantitySelector.vue
There can be only positive integer in quantity selector
Closes #932
> fix: only positive integer in qty selector

- packages/shared/styles/components/atoms/SfCheckbox.scss
- packages/shared/styles/components/molecules/SfFilter.scss
- packages/vue/src/components/molecules/SfFilter/SfFilter.stories.js
- packages/vue/src/components/molecules/SfFilter/SfFilter.vue
> feat: add sf color to sf filter

- packages/vue/config/storybook/home/home.js
- packages/vue/config/storybook/home/home.scss
> chore: add style for storybook introduction page

- packages/shared/styles/components/organisms/SfFooter.scss
- packages/vue/src/examples/templates/default/Default.stories.js
- packages/vue/src/examples/templates/default/Default.vue
add example default template with header and footer
If applicable:
> feat: add example default template

- packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.stories.js
- packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.vue
Closes #998 
V-model added to SfAddToCart
> fix: quantity for SfAddToCart in SfProductCardHorizontal 

- packages/vue/src/components/molecules/SfSelect/SfSelect.stories.js
- packages/vue/src/components/molecules/SfSelect/SfSelect.vue
#1013
Closes #
add cancel button slot and story regarging this slot
> feat: SfSelect add cancel button slot

- .gitignore
- packages/shared/package.json
- packages/vue/.eslintrc.js
- packages/vue/.gitignore
- packages/vue/package.json
- yarn.lock
update to newest all SFUI dependencies
> chore: update SFUI dependencies

- packages/shared/styles/components/atoms/SfButton.scss
- packages/shared/styles/components/atoms/SfIcon.scss
- packages/shared/styles/components/atoms/SfInput.scss
- packages/shared/styles/components/molecules/SfModal.scss
- packages/shared/styles/components/molecules/SfPagination.scss
- packages/shared/styles/components/molecules/SfSearchBar.scss
- packages/shared/styles/components/molecules/SfSelect.scss
> a11y: outline none deleted

- packages/vue/src/components/atoms/SfImage/SfImage.stories.js
- packages/vue/src/components/atoms/SfImage/SfImage.vue
Closes #1048
add lozad props: rootMargin and threshold
> feat: add props to lozad

- packages/vue/docs/migration-guide.md
Closes #
- fix table with changes in spacers comparing to sass variables
If applicable:
> fix: spacers in migration guide

- packages/vue/src/components/atoms/SfArrow/SfArrow.stories.js
- packages/vue/src/components/atoms/SfLink/SfLink.vue
- packages/vue/src/components/atoms/SfQuantitySelector/SfQuantitySelector.stories.js
- packages/vue/src/components/atoms/SfQuantitySelector/SfQuantitySelector.vue
- packages/vue/src/components/molecules/SfSearchBar/SfSearchBar.stories.js
- packages/vue/src/components/molecules/SfSearchBar/SfSearchBar.vue
- packages/vue/src/examples/pages/checkout/_internal/OrderSummary.vue
- packages/vue/src/examples/pages/home/Home.vue
> refactor: regex in isExternalLink

- packages/shared/styles/components/atoms/SfBreadcrumbs.scss
- packages/shared/styles/variables/_colors.scss
- packages/vue/src/components/organisms/SfGroupedProduct/SfGroupedProduct.stories.js
- packages/vue/src/examples/pages/category/Category.vue
https://github.com/DivanteLtd/storefront-ui/issues/1065
Closes #
changed colors and typo  in breadcrumbs and  navbar color in category
> #1065 category a11y

- packages/shared/styles/components/organisms/SfHeader.scss
SfSearchbar is under logo in SfHeader with hasMobileSearch on true
> fix: SfSearchbar under logo on mobile

- packages/vue/src/components/organisms/SfHero/SfHero.stories.js
> fix: typo in SfHero stories

- packages/shared/styles/components/molecules/SfDropdown.scss
- packages/vue/src/components/molecules/SfDropdown/SfDropdown.stories.js
- packages/vue/src/components/molecules/SfDropdown/SfDropdown.vue
> fix: 'sf-dropdown--up' modifier 

- packages/shared/styles/components/molecules/SfSearchBar.scss
- packages/shared/styles/components/organisms/SfHeader.scss
- packages/vue/src/components/organisms/SfHeader/SfHeader.vue
- packages/vue/src/components/organisms/SfMegaMenu/SfMegaMenu.stories.js
Closes #
fix specificity for SfSearchBar on SfHeader
If applicable:
> fix: ssr and specificity in SfHeader

- packages/vue/src/components/atoms/SfImage/SfImage.vue
> fix: nullish SfImage

- packages/shared/styles/components/molecules/SfRadio.scss
- packages/vue/src/components/molecules/SfRadio/SfRadio.stories.js
- packages/vue/src/components/molecules/SfRadio/SfRadio.vue
Closes #1169 
Class in new convention and fixed typo in stories
> fix: disabled SfRadio 

- packages/shared/styles/components/organisms/SfProductCardHorizontal.scss
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
- packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.vue
> refactor: use SfLink

- packages/vue/src/components/organisms/SfHeader/SfHeader.vue
Closes #
restore and fix `cartIcon`, `wishlistIcon` and `accountIcon` to SfHeader behaviour
If applicable:
> fix: header icons API in SfHeader

- packages/shared/styles/components/atoms/SfPrice.scss
- packages/vue/src/components/atoms/SfPrice/SfPrice.spec.js
- packages/vue/src/components/atoms/SfPrice/SfPrice.vue
Closes #994
Order of price values changed and customization properties added. Flex dsiplay added to enable value direction and order changes. Unit tests adjuted.
> refactor: price variant as elements

- packages/vue/src/components/organisms/SfContentPages/SfContentPages.stories.js
- packages/vue/src/components/organisms/SfContentPages/SfContentPages.vue
> fix: add unique keys to SfContentPages

- packages/vue/src/components/molecules/SfPagination/SfPagination.vue
> fix: remove this from SfPagination

- packages/shared/styles/components/organisms/SfProductCard.scss
- packages/shared/styles/components/organisms/SfProductCardHorizontal.scss
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
- packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.vue
> fix: product cards with SfLink inside slots

- packages/vue/docs/customization.md
Closes # N/A
Improved the docs, fixed some typos and improved a statement.
If applicable:
> Fixed some typos and improved a statement

- packages/vue/src/components/organisms/SfTabs/SfTabs.md
Closes #1206 
Add warning to SfTabs docs
If applicable:
> docs: add warning do SfTabs docs

- packages/vue/src/components/molecules/SfSelect/SfSelect.vue
https://github.com/DivanteLtd/storefront-ui/issues/1213
Closes #
Changed the label and role attribute of af-select and remove roles in other elements.
> #1213 fix/sfselect accessibility violations

- packages/shared/styles/components/atoms/SfInput.scss
- packages/shared/styles/components/molecules/SfSelect.scss
Closes #1173
change font size in label when select and input are focused
> fix: change label size in select and input

- packages/shared/styles/components/atoms/SfInput.scss
- packages/shared/styles/components/molecules/SfSelect.scss
- packages/vue/src/components/molecules/SfSelect/SfSelect.vue
- packages/vue/src/examples/others/form/Form.stories.js
- packages/vue/src/examples/others/form/Form.vue
Closes #1027
- add min-height to input and select
- fix styles
- add form template example 
If applicable:
> fix: inputs height on validation

- packages/vue/src/components/organisms/SfAccordion/SfAccordion.vue
Closes #1299 
Accordion keeps information about opened header in data 
No visual changes
> fix: SfAccordion folds after data updates

- packages/vue/docs/customization.md
The proposed tailwind config has been added to the documentation. It also shows how you can install tailwind and how to use it with storefrontu components.
If applicable:
> docs: Tailwind customization docs update

- .gitignore
- packages/shared/styles/components/molecules/SfScrollable.scss
- packages/vue/src/components/molecules/SfScrollable/SfScrollable.stories.js
- packages/vue/src/components/molecules/SfScrollable/SfScrollable.vue
Closes ##1301
Slot for button in SfScrollable added. There is also story for it added.
> feat: SfScrollable add slot for button

- packages/vue/src/components/molecules/SfPagination/SfPagination.stories.js
Closes # 1311
Change number property to page in "number" story.
> fix: SfPagination number slot fix

- packages/shared/styles/components/organisms/SfHeader.scss
- packages/vue/src/components/organisms/SfHeader/SfHeader.vue
> [WIP] fix: SfHeader errors with ref

- package.json
- packages/vue/docs/.vuepress/config.js
- packages/vue/docs/pull-off-components.md
- scripts/copy-components.js
Closes #1362
script to pull off components with styles from SFUI to the project 
If applicable:
> feat: script to pull off components from SFUI to the project 

- packages/vue/jest.config.js
- packages/vue/src/components/molecules/SfMenuItem/SfMenuItem.vue
> hotfix: Change from kebab-case to camelCase in SfMenuItem

- packages/vue/jest.config.js
- packages/vue/src/components/molecules/SfSelect/SfSelect.stories.js
- packages/vue/src/components/molecules/SfSelect/SfSelect.vue
- packages/vue/src/components/molecules/SfSelect/_internal/SfSelectOption.vue
> hotfix: SfSelect mutates prop directly

- packages/vue/docs/migration-guide.md
Closes #
Added info about new class name for smartphones
If applicable:
> docs: class for smartphones

- packages/shared/styles/components/molecules/SfSelect.scss
no
Remove unnecessary code from SfSelect.scss
If applicable:
> fix: remove unnecesary code

- packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue
Closes #1490 #1491
Changed prop name, added watch and emitted event 
No visual changes 
If applicable:
> fix: SfAddressPicker doesn't react to "selected" prop changes

- packages/vue/src/components/organisms/SfHeader/SfHeader.stories.js
- packages/vue/src/components/organisms/SfMegaMenu/SfMegaMenu.stories.js
Closes #1029
SfOverlay added in stories 
If applicable:
> fix: SfMegaMenu confusing on theme

- packages/vue/docs/contributing/become-a-contributor.md
- packages/vue/docs/design/working-with-designs.md
Closes #1467 
Updated link to our new designs in Figma
No changes 
If applicable:
> fix: updated link to our new designs in figma

- packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.stories.js
> fix: styles for hover buttons in story variant

- packages/vue/src/components/organisms/SfAccordion/_internal/SfAccordionItem.vue
- packages/vue/src/examples/pages/category/Category.vue
Closes #1062 
Added additional slot for info in accordion item 
If applicable:
> fix: apply new designs in storybook

- packages/vue/src/components/molecules/SfBar/SfBar.vue
Closes #1378 
Added button types for buttons in SfBar
If applicable:
> fix: button type for buttons in SfBar

- packages/vue/docs/getting-started/customization.md
Closes #1478 
Updated config for tailwind 
If applicable:
> fix: updated config for tailwind

- packages/vue/src/components/atoms/SfImage/SfImage.vue
Closes #1414 
SfImage nullish propagation changed to nested properties check using && operator.
If applicable:
> fix: nullish propagation in sfimage

- packages/vue/src/components/organisms/SfTable/_internal/SfTableHeading.spec.js
- packages/vue/src/components/organisms/SfTable/_internal/SfTableHeading.vue
- packages/vue/src/components/organisms/SfTable/_internal/SfTableRow.spec.js
- packages/vue/src/components/organisms/SfTable/_internal/SfTableRow.vue
Closes #1509 
tbody and thead in SfTable
no visual changes
If applicable:
> fix: tbody and thead in SfTable

- packages/vue/src/components/molecules/SfCallToAction/SfCallToAction.stories.js
- packages/vue/src/components/molecules/SfCallToAction/SfCallToAction.vue
Closes #1525 
link prop for button in SfCallToAction
If applicable:
> feat: SfCallToAction add link prop 

- packages/shared/styles/components/organisms/SfProductCard.scss
https://github.com/DivanteLtd/storefront-ui/issues/1547
Update styles to match the designs
https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/shared/styles/components/organisms/SfProductCard.scss
If applicable:
> fix: update SfProductCard spacing and title

- packages/shared/styles/components/organisms/SfHero.scss
- packages/vue/src/components/organisms/SfHero/SfHero.spec.js
- packages/vue/src/components/organisms/SfHero/SfHero.vue
- packages/vue/src/examples/pages/home/Home.vue
Closes #1537 
No visual changes 
If applicable:
> fix: SfHero custom prev next not clickable

- packages/vue/src/components/molecules/SfPagination/SfPagination.vue
Closes #1544 
I've tested, and it works now with router.
If applicable:
> Fix linkToPage for SfPagination if has router

- packages/vue/src/examples/pages/my-account/MyAccount.stories.js
Closes #
MIssing export story MyAccount added
If applicable:
> fix: missing MyAccount 

- packages/vue/src/examples/pages/checkout/Checkout.vue
> fix: checkout - floating buttons

- packages/vue/src/components/molecules/SfModal/SfModal.vue
https://github.com/vuestorefront/storefront-ui/issues/1603
fix props
Before
After
> fix: #1603

- packages/vue/src/components/atoms/SfImage/SfImage.stories.js
- yarn.lock
Closes #1614 
Unused import deleted
If applicable:
> hotfix: SfImage has no image

- packages/shared/styles/components/organisms/SfCarousel.scss
- packages/vue/src/examples/pages/home/Home.vue
> hotfix: carousel fixed (home differs form figma)

- packages/vue/src/components/atoms/SfDivider/SfDivider.stories.js
- yarn.lock
> hotfix: story for SfDivider

- packages/vue/src/examples/pages/category/Category.vue
> hotfix: Category (mobile view) - missing title in SfProductCard

- packages/shared/styles/components/organisms/SfHero.scss
Closes #1649 
removed pointer-events: none 
If applicable:
> hotfix: SfHero - buttons are not clickable

- packages/shared/styles/components/organisms/SfHero.scss
- packages/vue/src/components/organisms/SfHero/SfHero.stories.js
- packages/vue/src/components/organisms/SfHero/_internal/SfHeroItem.vue
> feat: SfHero with SfCimage

- README.md
> docs: updated readme links

- packages/vue/src/components/organisms/SfHero/SfHero.vue
- packages/vue/src/stories/releases/v0.10.1/v0.10.1.stories.mdx
> fix: SfHero - removed SfButton as wrapper for SfArrow

- packages/vue/src/components/organisms/SfCarousel/SfCarousel.vue
- packages/vue/src/components/organisms/SfHero/SfHero.vue
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
- packages/vue/src/stories/releases/v0.10.1/v0.10.1.stories.mdx
- packages/vue/src/stories/releases/v0.10.2/v0.10.2.stories.mdx
Closes #1669 
Removed client checker from SfProductVard, SfCarousel, SfHero
If applicable:
> fix: removed client checker

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- packages/vue/src/stories/Introduction.stories.mdx
- packages/vue/src/stories/getting-started/2. customization.stories.mdx
> chore: updated links to docs

- packages/vue/src/components/molecules/SfPagination/SfPagination.vue
- packages/vue/src/stories/releases/v0.10.2/v0.10.2.stories.mdx
- packages/vue/src/stories/releases/v0.10.3/v0.10.3.stories.mdx
Closes #1687 #1686 
If applicable:
> fix: SfPagination both arrows visible and fixed links

- packages/vue/src/components/organisms/SfTabs/SfTabs.stories.js
- packages/vue/src/components/organisms/SfTabs/SfTabs.vue
- packages/vue/src/examples/pages/product/Product.vue
- packages/vue/src/stories/releases/v0.10.3/v0.10.3.stories.mdx
- packages/vue/src/stories/releases/v0.10.4/v0.10.4.stories.mdx
> feat: open tabs not only by clicking on SfTab

- packages/vue/src/components/organisms/SfProductCard/SfProductCard.spec.js
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.stories.js
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
- packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.stories.js
- packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.vue
- packages/vue/src/examples/pages/category/Category.vue
- packages/vue/src/examples/pages/home/Home.vue
- packages/vue/src/stories/releases/v0.11.0/v0.11.0.stories.mdx
Closes #1718 
Renamed all occurences of isOnCart and isOnWishlist
If applicable:
> Bug #1718/fix naming convention

- .vuestorefrontcloud/docker/Dockerfile
> feat: adjust Dockerfile to correctly serve storybook

- packages/vue/src/components/atoms/SfImage/SfImage.vue
- packages/vue/src/stories/releases/v0.10.5/v0.10.5.stories.mdx
> hotfix: images are not shown on ssr 

- packages/vue/src/components/atoms/SfQuantitySelector/SfQuantitySelector.vue
- packages/vue/src/stories/releases/v0.11.0/v0.11.0.stories.mdx
> feat: SfQuantitySelector emit blur event

- packages/shared/styles/components/organisms/SfHero.scss
- packages/vue/src/components/organisms/SfHero/_internal/SfHeroItem.vue
- packages/vue/src/stories/releases/v0.10.5/v0.10.5.stories.mdx
- packages/vue/src/stories/releases/v0.10.6/v0.10.6.stories.mdx
> fix: SfHero remove css vars for background img

- packages/shared/styles/components/organisms/SfAccordion.scss
- packages/vue/src/stories/releases/v0.10.7/v0.10.7.stories.mdx
> Fix #1796/accordion multiline center

- packages/shared/styles/components/molecules/SfModal.scss
- packages/vue/src/components/molecules/SfModal/SfModal.stories.js
- packages/vue/src/components/molecules/SfModal/SfModal.vue
- packages/vue/src/stories/releases/v0.10.7/v0.10.7.stories.mdx
Closes #1812
- [] Changes documented 
If applicable:
> feat: SfModal without js

- packages/vue/src/components/molecules/SfBanner/SfBanner.vue
- packages/vue/src/components/molecules/SfCategoryCard/SfCategoryCard.vue
- packages/vue/src/components/molecules/SfTile/SfTile.vue
- packages/vue/src/components/organisms/SfHeader/_internal/SfHeaderNavigation.vue
- packages/vue/src/components/organisms/SfHeader/_internal/SfHeaderNavigationItem.vue
- packages/vue/src/components/organisms/SfHero/_internal/SfHeroItem.vue
- packages/vue/src/stories/releases/v0.10.7/v0.10.7.stories.mdx
- yarn.lock
> fix: SSR missmatch

- packages/shared/styles/components/organisms/SfSidebar.scss
- packages/vue/src/components/organisms/SfSidebar/SfSidebar.stories.js
- packages/vue/src/components/organisms/SfSidebar/SfSidebar.vue
- packages/vue/src/stories/releases/v0.10.7/v0.10.7.stories.mdx
Reverts vuestorefront/storefront-ui#1825 as it was causing SSR Missmatch issues
> Revert "feat:  sfsidebar without js"

- packages/nuxt/CHANGELOG.md
- packages/nuxt/package.json
- packages/shared/CHANGELOG.md
- packages/shared/package.json
- packages/vue/CHANGELOG.md
- packages/vue/package.json
- packages/vue/src/components/organisms/SfSidebar/SfSidebar.vue
- packages/vue/src/stories/releases/v0.10.7/v0.10.7.stories.mdx
> Hotfix 0.10.71

- packages/vue/src/components/atoms/SfLink/SfLink.vue
- packages/vue/src/stories/releases/v0.10.8/v0.10.8.stories.mdx
> Fix #1883/revert sf link

- packages/vue/.storybook/preview-head.html
- packages/vue/src/components/organisms/SfSidebar/SfSidebar.vue
> fix: sidebar and modal (scroll after navigation)

- packages/vue/src/stories/Introduction.stories.mdx
> fix: storybook link in homepage

- packages/vue/.storybook/manager-head.html
- packages/vue/.storybook/preview-head.html
Closes #1935 
Added Google Tag Manager and HubSpot for analytics.
If applicable:
> docs: Connect gtm + hubspot

- packages/vue/src/stories/Introduction.stories.mdx
- packages/vue/src/stories/Websites.stories.mdx
> fix: remove websites from docs

- packages/vue/src/stories/Introduction.stories.mdx
- packages/vue/src/stories/Websites.stories.mdx
> fix: remove websites

- packages/shared/styles/components/organisms/SfProductCard.scss
- packages/vue/src/components/atoms/SfImage/SfImage.vue
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.stories.js
- packages/vue/src/examples/pages/category/Category.vue
- packages/vue/src/stories/releases/v0.10.8/v0.10.8.stories.mdx
- packages/vue/src/stories/releases/v0.10.9/v0.10.9.stories.mdx
> Fix #1662/product card size

- packages/vue/src/components/organisms/SfFooter/SfFooter.vue
- packages/vue/src/components/organisms/SfFooter/_internal/SfFooterColumn.vue
- packages/vue/src/stories/releases/v0.10.9/v0.10.9.stories.mdx
> Fix #1667/footer without js

- packages/vue/src/components/atoms/SfHeading/SfHeading.vue
- packages/vue/src/components/atoms/SfIcon/SfIcon.vue
- packages/vue/src/components/atoms/SfImage/SfImage.vue
- packages/vue/src/stories/releases/v0.10.9/v0.10.9.stories.mdx
> fix: atoms static classes

- packages/vue/src/components/molecules/SfAlert/SfAlert.vue
- packages/vue/src/components/molecules/SfNotification/SfNotification.vue
- packages/vue/src/stories/releases/v0.10.9/v0.10.9.stories.mdx
> Fix #1960/molecules without dynamic classes

- packages/shared/styles/components/organisms/SfProductCard.scss
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.stories.js
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
- packages/vue/src/stories/releases/v0.10.9/v0.10.9.stories.mdx
> Feat #881/color picker in product card

- packages/vue/src/components/molecules/SfGallery/SfGallery.vue
- packages/vue/src/stories/releases/v0.11.0/v0.11.0.stories.mdx
Reverts vuestorefront/storefront-ui#1794
> Revert "fix: #1782 - SfGallery - missing alt for an image"

- packages/shared/styles/components/organisms/SfBottomNavigation.scss
Reverts vuestorefront/storefront-ui#1588
> Revert "#1551 SfBottomNavigation fixes"

- packages/shared/styles/components/organisms/SfProductCard.scss
- packages/vue/index.js
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.stories.js
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
- packages/vue/src/stories/releases/v0.10.6/v0.10.6.stories.mdx
- packages/vue/src/stories/releases/v0.11.0/v0.11.0.stories.mdx
Reverts vuestorefront/storefront-ui#1499
> Revert "feat: Implement SfColorPicker in SfProductCard"

- package.json
> fix: add @vue/cli-plugin-eslint to root

- packages/vue/src/stories/introduction/members.json
> docs: #1981 add Aditya Patel to team docs

- packages/vue/src/components/templates/form/Form.vue
- packages/vue/src/stories/releases/v0.11.x/v0.11.0/v0.11.0.stories.mdx
https://github.com/vuestorefront/storefront-ui/issues/2016
Closes #2016
updated form email input validation message
Current Prod
Proposed fix
> fix: updated form email input validation message

- packages/shared/styles/components/templates/SfMyNewsletter.scss
- packages/shared/styles/components/templates/SfMyProfile.scss
- packages/shared/styles/components/templates/SfOrderHistory.scss
- packages/shared/styles/components/templates/SfPayment.scss
- packages/shared/styles/components/templates/SfPersonalDetails.scss
- packages/shared/styles/components/templates/SfShipping.scss
- packages/shared/styles/components/templates/SfShippingDetails.scss
- packages/vue/src/components/templates/SfMyNewsletter/SfMyNewsletter.vue
- packages/vue/src/components/templates/SfMyProfile/SfMyProfile.vue
- packages/vue/src/components/templates/SfOrderHistory/SfOrderHistory.vue
- packages/vue/src/components/templates/SfPayment/SfPayment.vue
- packages/vue/src/components/templates/SfPersonalDetails/SfPersonalDetails.vue
- packages/vue/src/components/templates/SfShipping/SfShipping.vue
- packages/vue/src/components/templates/SfShippingDetails/SfShippingDetails.vue
> fix: reorganized template styles

- README.md
- packages/vue/src/stories/1. Introduction.stories.mdx
- packages/vue/src/stories/contributing-guide/1. contribute.stories.mdx
- packages/vue/src/stories/releases/v0.11.x/v0.11.1/v0.11.1.stories.mdx
Closes https://github.com/vuestorefront/storefront-ui/issues/2072
redirect to correct URL 
If applicable:
> docs: fix contributing links

- packages/vue/src/components/molecules/SfRadio/SfRadio.stories.js
- packages/vue/src/stories/releases/v0.11.x/v0.11.3/v0.11.3.stories.mdx
> fix: SfRadio - mutating prop directly error

- packages/vue/src/components/atoms/SfIcon/SfIcon.vue
> hotfix: adjusted icon size

- packages/vue/src/components/atoms/SfIcon/SfIcon.vue
> hotfix: SfIcon - remove default value for color prop

- packages/vue/.browserslistrc
- packages/vue/src/stories/1. Introduction.stories.mdx
- packages/vue/src/stories/releases/v0.11.x/v0.11.4/v0.11.4.stories.mdx
Closes #
- updated information about browser support of SFUI
> chore: updated browser support file

- packages/vue/src/components/organisms/SfFooter/_internal/SfFooterColumn.vue
- packages/vue/src/stories/releases/v0.11.x/v0.11.3/v0.11.3.stories.mdx
- packages/vue/src/stories/releases/v0.11.x/v0.11.4/v0.11.4.stories.mdx
> refactor: button with type attribute in footer

- packages/shared/styles/components/organisms/SfProductCard.scss
no
Layout fix of add to cart button on product card in hover and active states. 
If applicable:
> fix: add to cart on hover and in active state

- packages/vue/src/components/atoms/SfImage/SfImage.vue
- packages/vue/src/components/organisms/SfGroupedProduct/_internal/SfGroupedProductItem.vue
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
- packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.vue
- packages/vue/src/stories/releases/v0.12.x/v0.12.0/migration.stories.mdx
- packages/vue/src/stories/releases/v0.12.x/v0.12.0/v0.12.0.stories.mdx
> feat: SfImage - placeholder as a picture 

- packages/shared/styles/components/molecules/SfBanner.scss
- packages/shared/styles/components/organisms/SfBannerGrid.scss
- packages/vue/src/components/molecules/SfBanner/SfBanner.stories.js
- packages/vue/src/components/molecules/SfBanner/SfBanner.vue
- packages/vue/src/components/organisms/SfBannerGrid/SfBannerGrid.stories.js
- packages/vue/src/stories/releases/v0.12.x/v0.12.0/v0.12.0.stories.mdx
> feat: SfBanner with img tag

- packages/vue/src/stories/releases/v0.12.x/v0.12.0/v0.12.0.stories.mdx
- packages/vue/src/utilities/mobile-observer.js
- packages/vue/src/utilities/mobile-observer.spec.js
Closes #1701 
- cleaned up the way we call each functions
- removed unused variables
-
If applicable:
> refactor: mobile observer

- packages/nuxt/cypress/integration/login.spec.js
- packages/vue/src/stories/releases/v0.12.x/v0.12.1/v0.12.1.stories.mdx
> fix: login e2e test fixed

- .gitignore
- packages/vue/src/stories/releases/v0.12.x/v0.12.0/v0.12.0.stories.mdx
- packages/vue/src/stories/releases/v0.12.x/v0.12.1/v0.12.1.stories.mdx
Closes #2186 
Add local history folder in gitignore
If applicable:
> fix: included the local history folder in gitignore

- packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx
> docs: changelog 0.12.2

- packages/shared/styles/components/organisms/SfHero.scss
- packages/vue/src/components/organisms/SfHero/SfHero.stories.js
- packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx
> feat: SfHero easier button customisation by css vars

- packages/shared/styles/components/organisms/SfProductCardHorizontal.scss
- packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.vue
- packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx
Closes #2254 
- removed unused computed property
- added css fix for wishlist-icon
> fix: SfProductCardHorizontal - adjusted position of wishlist icon

- package.json
Add `scripts.playground` to `package.json`
> Add `scripts.playground` to `package.json`

- lighthouserc.json
- packages/vue/src/stories/releases/v0.12.x/v0.12.3/v0.12.3.stories.mdx
> feat: lighthouse - plp, detailed cart, login and static pages added

- packages/nuxt/cypress/integration/home.spec.js
- packages/vue/src/stories/releases/v0.12.x/v0.12.3/v0.12.3.stories.mdx
- packages/vue/src/stories/releases/v0.12.x/v0.12.4/v0.12.4.stories.mdx
>  fix: e2e test hero

- README.md
Updated README.md to a new design
Check the file at
https://github.com/vuestorefront/storefront-ui/blob/4baedbeeca7a168f47f286a252c638a00a93bd87/README.md
If applicable:
> chore: update README.md to new design

- packages/nuxt/layouts/default.vue
- packages/vue/src/stories/releases/v0.12.x/v0.12.4/v0.12.4.stories.mdx
> fix: SfFooter doubled on nuxt

- packages/vue/src/stories/releases/v0.12.x/v0.12.4/v0.12.4.stories.mdx
> docs: changelog updated

- packages/vue/src/stories/releases/v0.12.x/v0.12.0/migration.stories.mdx
- packages/vue/src/stories/releases/v0.12.x/v0.12.0/v0.12.0.stories.mdx
- packages/vue/src/stories/releases/v0.12.x/v0.12.1/v0.12.1.stories.mdx
- packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx
- packages/vue/src/stories/releases/v0.12.x/v0.12.3/v0.12.3.stories.mdx
- packages/vue/src/stories/releases/v0.13.x/v0.13.0/v0.13.0.stories.mdx
- packages/vue/src/stories/releases/v0.13.x/v0.13.1/v0.13.1.stories.mdx
Closes #2348 
After:
If applicable:
> improvement: the release section structure in storybook

- packages/vue/src/components/atoms/SfInput/SfInput.stories.js
- packages/vue/src/stories/releases/v0.13.x/v0.13.1/v0.13.1.stories.mdx
> fix: SfInput - console errors in story

- packages/vue/src/components/atoms/SfBullets/SfBullets.vue
- packages/vue/src/stories/releases/v0.13.x/v0.13.1/v0.13.1.stories.mdx
> fix: SfBullets invalid array length

- packages/vue/src/components/molecules/SfBottomModal/SfBottomModal.stories.js
- packages/vue/src/stories/releases/v0.13.x/v0.13.1/v0.13.1.stories.mdx
Closes #2373 
Removed unnecessary styles in SfBottomModal story. 
If applicable:
> fix: SfBottomModal example story

- packages/vue/src/components/organisms/SfGroupedProduct/SfGroupedProduct.stories.js
- packages/vue/src/stories/releases/v0.13.x/v0.13.2/v0.13.2.stories.mdx
> fix: SfGroupedProduct error in console

- packages/shared/styles/components/molecules/SfGallery.scss
- packages/vue/src/components/molecules/SfGallery/SfGallery.vue
- packages/vue/src/stories/releases/v0.13.x/v0.13.2/v0.13.2.stories.mdx
> fix: SfGallery outside zoom

- packages/nuxt/cypress/integration/login.spec.js
- packages/vue/src/stories/releases/v0.13.x/v0.13.3/v0.13.3.stories.mdx
> fix: e2e test for login page

- packages/vue/src/stories/1. Introduction.stories.mdx
- packages/vue/src/stories/2. Websites.stories.mdx
- packages/vue/src/stories/releases/v0.13.x/v0.13.4/v0.13.4.stories.mdx
Closes #
Changed links and logos on docs welcome page.
If applicable:
> chore: Update links and logos in docs 

- packages/vue/scripts/copy-components.js
> fix: updated copy components script

- packages/vue/src/components/organisms/SfHeader/SfHeader.stories.js
- packages/vue/src/components/organisms/SfHeader/SfHeader.vue
- packages/vue/src/stories/releases/v0.13.x/v0.13.4/v0.13.4.stories.mdx
> fix: Storybook Organisms Header some props do not work

- apps/docs/components/blocks/NavbarBottom.md
Closes #
- fixes `NavbarBottom` code snippet to use Vue source code
If applicable:
> docs: fix navbarbottom code snippet

- apps/docs/components/blocks/NavbarBottom.md
- apps/docs/components/blocks/ProductCard.md
fix vue examples (which currently show react code instead of vue one)
> fix: vue examples source code

- apps/docs/components/components/chip.md
Closes[ #900](https://vsf.atlassian.net/browse/SFUI2-900)
If applicable:
> fix: (sfui2-900) chip docs [ hotfix]

- .vuestorefrontcloud/router/docker/default.conf
> chore: publish v2 docs

- apps/docs/components/react/getting-started.md
> fix: react installation guide

- .vuestorefrontcloud/docs/README.md
> fix: dot for docker readme

- apps/preview/nuxt/package.json
- yarn.lock
> chore: update nuxt version

- apps/docs/development/release.md
> chore: update release.md

- apps/docs/components/components/listitem.md
https://vsf.atlassian.net/browse/SFUI2-927?atlOrigin=eyJpIjoiOTJlNDllZDBlNmE0NDA5NmIyNDczOWE2MzRlNjI0NTgiLCJwIjoiaiJ9
- fixed incorrect link
> chore: fixed invalid link for colors

- apps/preview/nuxt/pages/showcases/Select/SelectCustomChevron.vue
- apps/preview/nuxt/pages/showcases/Select/SelectSizes.vue
https://vsf.atlassian.net/browse/SFUI2-925?atlOrigin=eyJpIjoiZGNlYjZmNGRlMDdmNDM0OTk1ZGNiNGQyZWY5YmYxNzUiLCJwIjoiaiJ9
- added missing placeholders in select blocks
-
> fix: added missing select placeholders

- apps/docs/components/customization/overriding-default-styles.md
- apps/docs/components/react/components.md
- apps/docs/components/vue/components.md
- adds customization and base components vs. blocks videos to the relevant docs
> docs: add latest videos

- apps/preview/next/pages/showcases/Drawer/Placement.tsx
- apps/preview/nuxt/pages/showcases/Button/ButtonVariants.vue
- apps/preview/nuxt/pages/showcases/Drawer/Placement.vue
- apps/preview/nuxt/pages/showcases/Drawer/TransitionAndCloseButton.vue
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/69?modal=detail&selectedIssue=SFUI2-941&assignee=5fcf86fca1d3f100684db8a5
Removed enums form examples
> fix: remove enums from button examples

- apps/preview/next/pages/showcases/Alert/AlertError.tsx
- apps/preview/next/pages/showcases/Alert/AlertPositive.tsx
- apps/preview/next/pages/showcases/Alert/AlertSecondary.tsx
- apps/preview/next/pages/showcases/Alert/AlertWarning.tsx
- apps/preview/nuxt/pages/showcases/Alert/AlertError.vue
- apps/preview/nuxt/pages/showcases/Alert/AlertPositive.vue
- apps/preview/nuxt/pages/showcases/Alert/AlertSecondary.vue
- apps/preview/nuxt/pages/showcases/Alert/AlertWarning.vue
https://vsf.atlassian.net/browse/SFUI2-1046
add no shrinking icon 
add focus-visible on button
> fix: alert blocks styling [SFUI2-1046]

- apps/docs/components/hooks/useFocusVisible.md
- apps/docs/components/hooks/useScrollable.md
> fix: mark useFocusVisible as experimental

- apps/preview/next/pages/showcases/MegaMenu/BaseMegaMenu.tsx
- apps/preview/next/pages/showcases/NavbarTop/NavbarTop.tsx
- apps/preview/next/pages/showcases/NavbarTop/NavbarTopFilled.tsx
- apps/preview/nuxt/pages/showcases/MegaMenu/BaseMegaMenu.vue
- apps/preview/nuxt/pages/showcases/NavbarTop/NavbarTop.vue
- apps/preview/nuxt/pages/showcases/NavbarTop/NavbarTopFilled.vue
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/69?modal=detail&selectedIssue=SFUI2-1043&assignee=5fcf86fca1d3f100684db8a5
Adjusted mega menu to figma design
> fix: mega menu differences in design

- apps/docs/components/blocks/Filters.md
- apps/preview/next/pages/showcases/Filters/FiltersPanel.tsx
- apps/preview/nuxt/pages/showcases/Filters/FiltersPanel.vue
https://vsf.atlassian.net/browse/SFUI2-1049?atlOrigin=eyJpIjoiZGUwNDZiZTFlNjRlNDg0Zjg5YjMwNTUwZjYyNmVmZTQiLCJwIjoiaiJ9
- adjusted headings to the new design
- changed clear filters logic
- fixed issue with missing sortby section
> fix: (sfui2-1016) filters panel improvements

- apps/docs/components/package.json
- package.json
- yarn.lock
Closes #
Just unification of one package we use
> chore(deps): unify rimraf version

- packages/sfui/frameworks/react/components/SfScrollable/SfScrollable.tsx
- packages/sfui/frameworks/vue/components/SfScrollable/SfScrollable.vue
Closes[ #1073](https://vsf.atlassian.net/browse/SFUI2-1073)
Remove floating buttons from the inside of the main element in SfScrollable.
> fix: remove floating buttons from main element in SfScrollable 

- .github/workflows/configure-environment.yml
- .github/workflows/deploy-docs-vue-storefront-cloud.yml
- .github/workflows/deploy-router-vue-storefront-cloud.yml
- .github/workflows/deploy-test-next-storefront-cloud.yml
- .github/workflows/deploy-test-nuxt-storefront-cloud.yml
add support for release branches deployment
> ci: support release branches deployment

- .github/workflows/configure-environment.yml
> ci: fix pattern matching for stage deploy

- .github/workflows/configure-environment.yml
> ci: add missing stage env to deploy script

- apps/preview/next/pages/showcases/SelectDropdown/SelectDropdownDisabled.tsx
- apps/preview/next/pages/showcases/SelectDropdown/SelectDropdownError.tsx
- apps/preview/next/pages/showcases/SelectDropdown/SelectDropdownRequired.tsx
- apps/preview/next/pages/showcases/SelectDropdown/SelectDropdownWithPlaceholder.tsx
- apps/preview/nuxt/pages/showcases/SelectDropdown/SelectDropdownDisabled.vue
- apps/preview/nuxt/pages/showcases/SelectDropdown/SelectDropdownError.vue
- apps/preview/nuxt/pages/showcases/SelectDropdown/SelectDropdownRequired.vue
- apps/preview/nuxt/pages/showcases/SelectDropdown/SelectDropdownWithPlaceholder.vue
https://vsf.atlassian.net/browse/SFUI2-1121
label "Speed" -> "Delivery"
> fix: change label of SelectDropdown example [SFUI2-1121]

- apps/preview/nuxt/pages/showcases/SelectDropdown/SelectDropdownRequired.vue
https://vsf.atlassian.net/browse/SFUI2-1115
> fix: selectdropdown inconsistency between frameworks [SFUI2-1115]

- apps/preview/next/pages/showcases/Pagination/Pagination.tsx
https://vsf.atlassian.net/browse/SFUI2-1040?atlOrigin=eyJpIjoiODIyYWYzZWM2OGYyNGQ3ZmFkZGZjZDc5NzIxNzZlYmYiLCJwIjoiaiJ9
- added auto/width responsiveness for buttons in Pagination
-
> fix: adjusted responsiveness of pagination

- apps/preview/next/pages/showcases/Gallery/GalleryVertical.tsx
https://vsf.atlassian.net/browse/SFUI2-1130
missing className
> fix: react - VerticalGallery thumbnails are hidden on mobile [SFUI2-1130]

- apps/docs/components/.vuepress/components/Showcase.vue
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/69?modal=detail&selectedIssue=SFUI2-1132&assignee=5fcf86fca1d3f100684db8a5
https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/69?modal=detail&selectedIssue=SFUI2-1019&assignee=5fcf86fca1d3f100684db8a5
> fix: wider screen for blocks

- apps/docs/components/blocks/Gallery.md
- apps/docs/components/blocks/MegaMenu.md
- apps/docs/components/blocks/Search.md
- apps/docs/components/blocks/SelectDropdown.md
https://vsf.atlassian.net/browse/SFUI2-1145
Update 4 blocks description
> chore: update blocks description [SFUI2-1145]

- apps/docs/components/blocks/Gallery.md
https://vsf.atlassian.net/browse/SFUI2-1129
added experimental info to Gallery block. Not really a fan of this solution - will talk again with PM if that really needed (it's a block in the end, not a base component).
> chore: mark gallery block as experimental [SFUI2-1129]

- CHANGELOG.md
Closes [SFUI2-1138](https://vsf.atlassian.net/browse/SFUI2-1138)
v2.2.0 release notes
[SFUI2-1138]: https://vsf.atlassian.net/browse/SFUI2-1138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: release notes v2.2.0

- packages/config/tailwind/package.json
- packages/sfui/frameworks/react/package.json
- packages/sfui/frameworks/vue/package.json
- packages/sfui/shared/package.json
- packages/sfui/tw-plugin-peer-next/package.json
- packages/sfui/typography/package.json
> chore(release): v2.2.0

- apps/docs/components/react/getting-started.md
- apps/docs/components/vue/getting-started.md
https://vsf.atlassian.net/browse/SFUI2-1098?atlOrigin=eyJpIjoiMTU4YmI2MTkyYTU2NDcwNmEyZjc2ZGQyZTU5YWFhODkiLCJwIjoiaiJ9
- restored missing sections in astro/nuxt docs
-
> chore: restored missing sections in docs

- apps/docs/components/hooks/useTrapFocus.md
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/69?modal=detail&selectedIssue=SFUI2-1102&assignee=5fcf86fca1d3f100684db8a5
Updated docs for useTrapFocus
> docs: update docs for useTrapFocus

- apps/preview/next/tsconfig.json
Closes #
Add `incremental: true` option to the Next tsconfig. This option has been automatically added by Next for quite some time when running the app. I think we can finally add it.
You can find info about the incremental flag [here](https://www.typescriptlang.org/tsconfig#incremental).
> chore: add incremental to Next tsconfig

- apps/preview/next/pages/showcases/Search/SearchBasic.tsx
- apps/preview/nuxt/pages/showcases/Search/SearchBasic.vue
- packages/sfui/frameworks/react/hooks/useTrapFocus/useTrapFocus.ts
- packages/sfui/frameworks/vue/composables/useTrapFocus/useTrapFocus.ts
Closes [#1086](https://vsf.atlassian.net/browse/SFUI2-1086)
Added separate ref to handle focus trap. It allows to handle it and dropdown floating as well.
> fix: search - dropdown focus

- apps/docs/components/blocks/Gallery.md
- apps/preview/next/pages/showcases/Gallery/GalleryHorizontalArrowKeyNavigation.tsx
- apps/preview/nuxt/pages/showcases/Gallery/GalleryHorizontalArrowKeyNavigation.vue
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/69?modal=detail&selectedIssue=SFUI2-1127&assignee=5fcf86fca1d3f100684db8a5
Arrow key navigation for gallery
> feat: arrow key navigation for gallery

- .github/ISSUE_TEMPLATE/1.bug-report.yml
Closes #
What changes in the bug report template?
1. Merge "current behaviour" and "description" fields because it's not clear what's the difference between them.
2. Move questions to the placeholder.
3. Concise labels for better readability.
> chore: update bug-report template

- CONTRIBUTING.md
> docs: remove WIP note from CONTRIBUTING

- .vuestorefrontcloud/docs/Dockerfile
- .vuestorefrontcloud/docs/README.md
- .vuestorefrontcloud/docs/default.conf
- .vuestorefrontcloud/router/docker/default.conf
- README.md
- apps/docs/components/.vuepress/config.js
- packages/sfui/typography/README.md
closes https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/146?modal=detail&selectedIssue=SFUI2-1155
add `DOCKER_BUILDKIT=1` to make docker builds quicker.
> docs: fix figma redirect [SFUI2-1155]

- packages/sfui/frameworks/react/components/SfInput/SfInput.tsx
- packages/sfui/frameworks/vue/components/SfInput/SfInput.vue
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/146?modal=detail&selectedIssue=SFUI2-975
1. Box shadow added to pseudo element so that children background also has border.
2. Defined max height for all sizes so bigger icons don't have an impact on input size.
3 and 4 - there's no more wrappers for slots (not in this PR)
> fix: input fixes

- apps/docs/components/hooks/useScrollable.md
- packages/sfui/frameworks/react/components/SfScrollable/SfScrollable.tsx
- packages/sfui/frameworks/react/hooks/useScrollable/useScrollable.ts
- packages/sfui/frameworks/vue/components/SfScrollable/SfScrollable.vue
- packages/sfui/frameworks/vue/composables/useScrollable/useScrollable.ts
https://vsf.atlassian.net/browse/SFUI2-1067?atlOrigin=eyJpIjoiY2EzN2I0OGVjMDNmNDk4YzgwZWEyN2RiMTJhOWE2ZmMiLCJwIjoiaiJ9
- exposed showNext and showPrev methods
- removed getContainerProps and adjusted SfScrollable component code
- updated documentation
-
> feat: (sfui2-1067) useScrollable refactor

- apps/docs/components/.vuepress/components/Showcase.vue
https://vsf.atlassian.net/browse/SFUI2-892?atlOrigin=eyJpIjoiYzk4ZDhjMzNlMDFhNDU1NjhjN2Q4NzQ1ZWFjMjJjMzQiLCJwIjoiaiJ9
- added touch event listeners for mobile preview
-
> feat: (sfui2-892) added ability to resize preview on mobile

- .vuestorefrontcloud/docs/Dockerfile
- .vuestorefrontcloud/docs/README.md
Closes #
Updated command in docs for docker
> chore: update docker command in docs

- packages/sfui/frameworks/react/components/SfDrawer/SfDrawer.tsx
- packages/sfui/frameworks/react/components/SfModal/SfModal.tsx
- packages/sfui/frameworks/react/hooks/useScrollable/useScrollable.ts
- packages/sfui/frameworks/react/package.json
- packages/sfui/frameworks/react/shared/utils/index.ts
- packages/sfui/frameworks/react/shared/utils/refs.ts
- yarn.lock
closes #2699
move mergeRefs into our codebase to avoid errors in cjs bundle
> fix: cjs support

- .vuestorefrontcloud/docs/default.conf
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/69?modal=detail&selectedIssue=SFUI2-1160&assignee=5fcf86fca1d3f100684db8a5
https://github.com/vuestorefront/storefront-ui/assets/46591755/82642e92-21fc-4647-a407-287d83d98aba
> fix: redirect urls to .html

- apps/preview/next/pages/showcases/Card/CardFeature.tsx
- apps/preview/nuxt/pages/showcases/Card/CardFeature.vue
https://vsf.atlassian.net/browse/SFUI2-962?atlOrigin=eyJpIjoiZDVjMjUwMmRkYTMxNDk4NDk2ZDM1Y2RkMzY3NzczNzAiLCJwIjoiaiJ9
- adjusted responsiveness of cards
-
> fix: adjusted width of cards in card feature block

- CHANGELOG.md
- packages/config/tailwind/package.json
- packages/sfui/frameworks/react/package.json
- packages/sfui/frameworks/vue/package.json
- packages/sfui/shared/package.json
- packages/sfui/tw-plugin-peer-next/package.json
- packages/sfui/typography/package.json
> chore(release): v2.2.1

- .vuestorefrontcloud/docs/default.conf
- packages/sfui/frameworks/react/hooks/useScrollable/useScrollable.ts
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/69?modal=detail&selectedIssue=SFUI2-1180&assignee=5fcf86fca1d3f100684db8a5
> fix: absolute redirect off

- packages/sfui/frameworks/react/components/SfRating/SfRating.tsx
- packages/sfui/frameworks/vue/components/SfAccordionItem/SfAccordionItem.vue
- packages/sfui/frameworks/vue/components/SfRating/SfRating.vue
Closes #
Test to check if canary deployment works
> fix: format components

- .github/workflows/ci.yml
Closes #
Add tokens to changesets actions
> ci: add token to changeset actions

- .github/workflows/ci.yml
Closes #
update npm token for changeset publish
> ci: update npm token for changeset publish

- .github/workflows/ci.yml
Closes #
add registry to setup-node- changesets
> ci: add registry to setup-node- changesets

- apps/preview/next/pages/showcases/Banners/DisplayHorizontal.tsx
- apps/preview/next/pages/showcases/Banners/DisplayVertical.tsx
- apps/preview/next/pages/showcases/Banners/DisplayVerticalMultiple.tsx
- apps/preview/next/pages/showcases/Breadcrumbs/Breadcrumbs.tsx
- apps/preview/next/pages/showcases/Breadcrumbs/BreadcrumbsSeparator.tsx
- apps/preview/next/pages/showcases/Breadcrumbs/BreadcrumbsWithIcon.tsx
- apps/preview/next/pages/showcases/Button/ButtonAsLink.tsx
- apps/preview/next/pages/showcases/Card/CardDefault.tsx
- apps/preview/next/pages/showcases/Card/CategoryCard.tsx
- apps/preview/next/pages/showcases/Footer/FooterBasic.tsx
- apps/preview/next/pages/showcases/MegaMenu/BaseMegaMenu.tsx
- apps/preview/next/pages/showcases/MegaMenu/MegaMenuNavigation.tsx
- apps/preview/next/pages/showcases/NavbarTop/NavbarTop.tsx
- apps/preview/next/pages/showcases/NavbarTop/NavbarTopFilled.tsx
- apps/preview/next/pages/showcases/OrderSummary/OrderSummary.tsx
- apps/preview/nuxt/pages/showcases/Banners/DisplayHorizontal.vue
- apps/preview/nuxt/pages/showcases/Banners/DisplayVertical.vue
- apps/preview/nuxt/pages/showcases/Banners/DisplayVerticalMultiple.vue
- apps/preview/nuxt/pages/showcases/Breadcrumbs/Breadcrumbs.vue
- apps/preview/nuxt/pages/showcases/Breadcrumbs/BreadcrumbsSeparator.vue
- apps/preview/nuxt/pages/showcases/Breadcrumbs/BreadcrumbsWithIcon.vue
- apps/preview/nuxt/pages/showcases/Button/ButtonAsLink.vue
- apps/preview/nuxt/pages/showcases/Card/CardDefault.vue
- apps/preview/nuxt/pages/showcases/Card/CategoryCard.vue
- apps/preview/nuxt/pages/showcases/Footer/FooterBasic.vue
- apps/preview/nuxt/pages/showcases/MegaMenu/BaseMegaMenu.vue
- apps/preview/nuxt/pages/showcases/MegaMenu/MegaMenuNavigation.vue
- apps/preview/nuxt/pages/showcases/OrderSummary/OrderSummary.vue
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/146?modal=detail&selectedIssue=SFUI2-1171
changed slash to hash in links
> fix: change slash to hash in links

- .github/workflows/ci.yml
Closes #
Additional changes to release candidate process github actions
> ci: update release candidate github actions

- .github/workflows/release-changeset-changelog.yml
Closes #
Additional fixes for creating changelog PR
> ci: create changelog PR fix

- .github/workflows/deploy-docs-vue-storefront-cloud.yml
https://vsf.atlassian.net/browse/SFUI2-1169
add a script for syncing image assets to GCP storage
> chore: sync docs assets with GCP storage [SFUI2-1169]

- apps/preview/next/pages/showcases/Search/SearchWithButton.tsx
- apps/preview/next/pages/showcases/Search/SearchWithIcon.tsx
- apps/preview/nuxt/pages/showcases/Search/SearchWithButton.vue
- apps/preview/nuxt/pages/showcases/Search/SearchWithIcon.vue
https://vsf.atlassian.net/browse/SFUI2-1204?atlOrigin=eyJpIjoiOTgxYjA1MzQxNDQwNDBmYzk4YmU4YzMwNjMxMjcwNjYiLCJwIjoiaiJ9
- adjusted rings
> fix: ring adjustment in search blocks

- apps/docs/components/blocks/Filters.md
- apps/preview/next/pages/showcases/Filters/Category.tsx
- apps/preview/next/pages/showcases/Filters/Price.tsx
- apps/preview/nuxt/pages/showcases/Filters/Brand.vue
- apps/preview/nuxt/pages/showcases/Filters/Category.vue
- apps/preview/nuxt/pages/showcases/Filters/Price.vue
- apps/preview/nuxt/pages/showcases/Filters/Size.vue
Closes [#1211](https://vsf.atlassian.net/browse/SFUI2-1211)
Added Price and Brand filter blocks to docs and fix filter blocks.
> fix: filters in docs and in blocks [SFUI2-1211]

- packages/config/tailwind/package.json
- packages/sfui/frameworks/react/package.json
- packages/sfui/frameworks/vue/package.json
- packages/sfui/shared/package.json
- packages/sfui/tw-plugin-peer-next/package.json
- packages/sfui/typography/package.json
- yarn.lock
closes https://vsf.atlassian.net/browse/SFUI2-1221
> chore(release): v2.3.0

- packages/config/tailwind/package.json
- packages/sfui/frameworks/react/package.json
- packages/sfui/frameworks/vue/package.json
- packages/sfui/shared/package.json
- packages/sfui/tw-plugin-peer-next/package.json
- packages/sfui/typography/package.json
- turbo.json
> chore(release): v2.3.1

- apps/docs/tests/cypress.config.ts
- apps/docs/tests/e2e/iconsVisible.cy.ts
- apps/docs/tests/fixtures/elements.json
- apps/docs/tests/fixtures/iconTestId.json
- apps/docs/tests/support/pageObject/IconVisible.PageObject.ts
<[!-- paste a link to related issue --](https://vsf.atlassian.net/browse/SFUI2-1166?atlOrigin=eyJpIjoiZmRhODlkYjczZjZkNDA3NWI2NzhjZWNiMjhjYTMwNWQiLCJwIjoiaiJ9)>
Closes #
Created e2e cypress test to check fix for icons not visible
- [ x] Self code-reviewed
- [ x] Changes documented
- [ x] cypress tests created
> feat: add e2e test for icons dissappear

- .github/workflows/ci.yml
https://vsf.atlassian.net/browse/SFUI2-1099
For now only console log what this call return and check other solution
https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#check-if-a-user-is-a-repository-collaborator
> ci: validate collaborator check step [SFUI2-1099]

- .github/workflows/ci.yml
- .github/workflows/generate-changelog-changeset.yml
Closes #
Create more descriptive title and commit message 
Add missing node and yarn install
> ci: improve changelog generation [SFUI2-1184]

- apps/preview/next/pages/showcases/NavbarBottom/NavbarBottom.tsx
- apps/preview/next/pages/showcases/NavbarBottom/NavbarBottomFilled.tsx
- apps/preview/nuxt/pages/showcases/NavbarBottom/NavbarBottom.vue
- apps/preview/nuxt/pages/showcases/NavbarBottom/NavbarBottomFilled.vue
https://vsf.atlassian.net/browse/SFUI2-1173?atlOrigin=eyJpIjoiYjFhMDk5ZjZhY2YzNDY5OWJlMGMyMmM4YTc4MjM0YWYiLCJwIjoiaiJ9
- changed order of items 
- replaced search item with account item
> feat: changed items order in navbarbottom

- apps/preview/nuxt/pages/showcases/Combobox/ComboboxBasic.vue
Closes [#1241](https://vsf.atlassian.net/browse/SFUI2-1241)
Error message in Combobox not showing fixed.
> fix: combobox error message [SFUI2-1242]

- apps/preview/next/pages/showcases/FormFields/FormFieldsRequired.tsx
- apps/preview/nuxt/pages/showcases/FormFields/FormFieldsRequired.vue
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/69?modal=detail&selectedIssue=SFUI2-641
Added missing margins
> fix: more space for notification in form

- packages/sfui/frameworks/nuxt/CHANGELOG.md
- packages/sfui/frameworks/nuxt/package.json
- packages/sfui/frameworks/react/CHANGELOG.md
- packages/sfui/frameworks/react/package.json
- packages/sfui/frameworks/vue/CHANGELOG.md
- packages/sfui/frameworks/vue/package.json
- packages/sfui/shared/CHANGELOG.md
- packages/sfui/shared/package.json
> chore(release): 2.4.1

- apps/docs/components/components/link.md
> fix: broken blocks link

- apps/preview/next/pages/showcases/NavbarTop/NavbarTopFilledSimpleMobile.tsx
- apps/preview/next/pages/showcases/NavbarTop/NavbarTopSimpleMobile.tsx
- apps/preview/nuxt/pages/showcases/NavbarTop/NavbarTopFilledSimpleMobile.vue
- apps/preview/nuxt/pages/showcases/NavbarTop/NavbarTopSimpleMobile.vue
Closes # https://vsf.atlassian.net/browse/SFUI2-1172
Added square to buttons
> fix: navbar top square buttons

- apps/docs/tests/e2e/tableOfContentCheck.cy.ts
- apps/docs/tests/fixtures/buttonTablesOfContent.json
- apps/docs/tests/fixtures/genericTablesOfContent.json
- apps/docs/tests/support/pageObject/TableOfContent.PageObject.ts
Test check all sections in button and all generic ones in all components
Closes #
- [x ] Self code-reviewed
- [x ] Changes documented
- [ x] cypress tests created
> feat: add e2e test for base components table of content

- packages/vue/src/stories/getting-started/2. development guide/1. customization.stories.mdx
Closes #1907
Add additional tip to the documentation to help people overcoming global variables issues.
> docs: add tip about global variables

- README.md
- apps/docs/components/index.md
- apps/preview/next/pages/showcases/Badge/BadgeAvatar.tsx
- apps/preview/next/pages/showcases/Banners/DisplayVertical.tsx
- apps/preview/next/pages/showcases/Banners/DisplayVerticalMultiple.tsx
- apps/preview/next/pages/showcases/Card/CategoryCard.tsx
- apps/preview/next/pages/showcases/ProductCard/ProductCardHorizontal.tsx
- apps/preview/next/pages/showcases/ProductCard/ProductCardVertical.tsx
- apps/preview/next/pages/showcases/Search/SearchWithButton.tsx
- apps/preview/nuxt/pages/showcases/Badge/BadgeAvatar.vue
- apps/preview/nuxt/pages/showcases/Banners/DisplayVertical.vue
- apps/preview/nuxt/pages/showcases/Banners/DisplayVerticalMultiple.vue
- apps/preview/nuxt/pages/showcases/Card/CategoryCard.vue
- apps/preview/nuxt/pages/showcases/ProductCard/ProductCardHorizontal.vue
- apps/preview/nuxt/pages/showcases/ProductCard/ProductCardVertical.vue
- apps/preview/nuxt/pages/showcases/Search/SearchWithButton.vue
- packages/sfui/tw-plugin-peer-next/README.md
- packages/sfui/typography/README.md
https://vsf.atlassian.net/browse/SFUI2-1260
`width` and `height` attributes for `<img>` tag can be only written in `px` so `%` or `auto` causes issues. Also writing it as reactive prop in react (`width={40}`) or vue (`:width="40"`) is unnecessary overhead that add up extra work for framework, not significant but still
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#height
e.g in Nuxt 
```
```
was evaluated and rendered as 
```
```
> chore: fix img width and height attributes [SFUI2-1260]

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- packages/vue/package.json
- packages/vue/src/components/atoms/SfOverlay/SfOverlay.stories.js
- packages/vue/src/components/molecules/SfBottomModal/SfBottomModal.stories.js
- packages/vue/src/components/molecules/SfColorPicker/SfColorPicker.stories.js
- packages/vue/src/components/molecules/SfModal/SfModal.stories.js
- packages/vue/src/components/organisms/SfAccordion/SfAccordion.stories.js
- packages/vue/src/components/organisms/SfMegaMenu/SfMegaMenu.stories.js
- packages/vue/src/components/templates/SfPayment/SfPayment.stories.js
- packages/vue/src/components/templates/SfPersonalDetails/SfPersonalDetails.stories.js
- packages/vue/src/components/templates/SfShippingDetails/SfShippingDetails.stories.js
- packages/vue/src/stories/1. Introduction.stories.mdx
Closes https://vsf.atlassian.net/browse/SFUI2-1264
> fix: update v1 links [SFUI2-1264]

- apps/docs/components/blocks/RatingForms.md
- apps/preview/next/pages/showcases/RatingForms/ProductRatingWithReview.tsx
- apps/preview/nuxt/pages/showcases/RatingForms/ProductRatingWithReview.vue
Closes # https://vsf.atlassian.net/browse/SFUI2-1183
Product rating review block
> feat: product rating review

- .changeset/great-cheetahs-listen.md
- apps/preview/next/pages/showcases/Checkout/CheckoutDeliveryOptions.tsx
- apps/preview/next/pages/showcases/ListItem/ListItemSlots.tsx
- apps/preview/nuxt/pages/showcases/Checkout/CheckoutDeliveryOptions.vue
- apps/preview/nuxt/pages/showcases/ListItem/ListItemSlots.vue
- packages/sfui/frameworks/react/components/SfListItem/SfListItem.tsx
- packages/sfui/frameworks/vue/components/SfListItem/SfListItem.vue
Closes # https://vsf.atlassian.net/browse/SFUI2-1203
removed flex classes form wrapper slot in SfListItem
> fix!: remove flex classes form wrapper slot in SfListItem

- .changeset/flat-radios-do.md
- apps/preview/next/pages/showcases/Checkout/CheckoutDeliveryOptions.tsx
- apps/preview/next/pages/showcases/ListItem/ListItemSlots.tsx
- apps/preview/nuxt/pages/showcases/Checkout/CheckoutDeliveryOptions.vue
- apps/preview/nuxt/pages/showcases/ListItem/ListItemSlots.vue
- packages/sfui/frameworks/react/components/SfListItem/SfListItem.tsx
- packages/sfui/frameworks/vue/components/SfListItem/SfListItem.vue
Closes # https://vsf.atlassian.net/browse/SFUI2-1203
> fix!: remove flex classes from SfListItem 

- apps/preview/next/pages/showcases/FormFields/FormFieldsRequired.tsx
- apps/preview/nuxt/pages/showcases/FormFields/FormFieldsRequired.vue
Closes # https://vsf.atlassian.net/browse/SFUI2-1262
added additional label for phone number input
> feat: additional label for phone number input

- .vuestorefrontcloud/docs/default.conf
- README.md
Closes https://vsf.atlassian.net/browse/SFUI2-1294
> chore: update figma link [SFUI2-1294]

- apps/preview/next/pages/showcases/Filters/Color.tsx
- apps/preview/nuxt/pages/showcases/Filters/Color.vue
Closes # https://vsf.atlassian.net/browse/SFUI2-1252
same color when hovered color filter
> fix: hover color in color filter 

- apps/preview/next/pages/showcases/Combobox/ComboboxBasic.tsx
Closes # https://vsf.atlassian.net/browse/SFUI2-1271
removed required form combobox react
> fix: remove required form combobox react

- packages/vue/src/components/molecules/SfGallery/SfGallery.vue
Closes https://vsf.atlassian.net/browse/SFUI2-1263
closes #2798
set missing gallery css variables when setting up js props
> fix: cannot set width and height to SfGallery images [SFUI2-1263]

- apps/docs/components/.vuepress/config.js
https://vsf.atlassian.net/browse/SV-79
Replacing changelog urls in documentation to correct one
> chore: fix changelog links in documentation

- yarn.lock
Closes #
Sync dependency update so yarn.lock would match v2 === v2-develop
> chore: cherry pick update dependency

- apps/preview/next/pages/showcases/Footer/FooterBasic.tsx
- apps/preview/nuxt/pages/showcases/Footer/FooterBasic.vue
doing manual merge because automatic one is failing
> chore: merge v2 into v2 develop

- apps/docs/components/ai-assistant.md
Closes #
aDD TOP MARGIN IN ai aSSISTANT
> chore(docs): update margin in ai assistant

- apps/docs/components/index.md
Closes #
Added Qwik documentation link in the homepage
> chore(docs): add qwik documentation link

- .github/CODEOWNERS
Closes #
Added myself to codeowners
> chore(docs): add myself to codeowners

- .github/workflows/ci.yml
> chore: update sonarcloud action

- .github/workflows/ci.yml
- .gitignore
> ci(ENG-204): add ggshield scan

- apps/docs/components/ai-assistant.md
> chore: resolve conflicts for sync

- .changeset/lazy-donuts-draw.md
- packages/config/tailwind/index.ts
Reverts vuestorefront/storefront-ui#3071
> revert: remove inter display [UST-1349]

- .changeset/clever-colts-talk.md
- packages/config/tailwind/index.ts
> chore: change inter display into inter for headings

- .github/ISSUE_TEMPLATE/config.yml
- LICENSE
- README.md
- apps/preview/next/pages/showcases/Footer/FooterBasic.tsx
- apps/preview/nuxt/nuxt.config.ts
- apps/preview/nuxt/pages/showcases/Footer/FooterBasic.vue
- packages/config/tailwind/LICENSE
- packages/sfui/frameworks/react/LICENSE
- packages/sfui/frameworks/vue/LICENSE
- packages/sfui/shared/LICENSE
- packages/sfui/tw-plugin-peer-next/LICENSE
- packages/sfui/tw-plugin-peer-next/README.md
- packages/sfui/typography/LICENSE
- packages/sfui/typography/README.md
https://alokai.atlassian.net/browse/SMT-149
Closes #
> chore: rebrand readme's [SMT-149]

- .vuestorefrontcloud/docs/Dockerfile
> chore: update node version for docs deploy

- .changeset/fresh-toes-drum.md
> chore: changelog for type fixes

- apps/preview/nuxt/pages/showcases/Banners/Hero.vue
> chore(vue): unify Hero styling with react

- apps/preview/next/pages/showcases/Card/CategoryCard.tsx
- apps/preview/nuxt/pages/showcases/Card/CategoryCard.vue
> chore: fix CategoryCard link z-index

- apps/docs/components/server/plugins/code-snippets.ts
Closes #
- fixes source code on `Base Components` and `Hooks` that was not loading properly during build.
-
> docs: fix source code snippets

- .changeset/clever-colts-talk.md
- .changeset/cyan-carpets-collect.md
- .changeset/fresh-toes-drum.md
- .changeset/healthy-lies-wink.md
- .changeset/slimy-rice-breathe.md
> chore: remove changesets

- apps/docs/components/nuxt.config.ts
https://alokai.atlassian.net/browse/SMT-151
Closes #
> docs: change figma link [SMT-151]

- .github/workflows/cd-generate-changelog-changeset.yml
- .github/workflows/cd-v2-automerge.yml
- .github/workflows/ci.yml
- .github/workflows/configure-environment.yml
- .github/workflows/deploy-docs-vue-storefront-cloud.yml
- .github/workflows/image-build-vue-storefront-cloud.yml
Closes #
Update gh actions versions
> chore: update major action version for gh actions

- renovate.json
> chore: renovate block yarn 4

- .vuestorefrontcloud/demo/docker/Dockerfile
- .vuestorefrontcloud/docs/Dockerfile
- .vuestorefrontcloud/test-next/docker/Dockerfile
- .vuestorefrontcloud/test-nuxt/docker/Dockerfile
> chore: update node version in dockerfiles
