- scripts/postinstall.js
https://github.com/DivanteLtd/storefront-ui/issues/55
Fixed the issues with there being compilation errors out of the box, a fresh install shouldn't show any errors (prettier or otherwise). (when running npm serve)
Before:
After:
> #55 - Fresh installation giving errors for Playground.vue / Prettier

- src/components/molecules/SfSidebar/SfSidebar.spec.ts
Fixed the default test case for SfSidebar to make all tests pass again.
> [TESTS] Fix default test case for SfSidebar

- src/components/atoms/SfRating/README.md
- src/components/atoms/SfRating/SfRating.spec.ts
- src/components/atoms/SfRating/SfRating.stories.js
- src/components/molecules/SfMenuItem/SfMenuItem.spec.ts
#63 
Saw in [this commit](https://github.com/DivanteLtd/storefront-ui/commit/c306ee5c1cbee5787329d6ff5cd93a1499a14edb) that the names of the slots in SfRating were changed back to kebab case, so I've fixed the tests and documentation.
> Fix tests and documentation

- src/components/molecules/SfInputNumber/SfInputNumber.scss
--
Add user-select none
Before:
After:
> Make the controls not selectable

- docs/creating-new-component.md
- package.json
- scripts/create-component.js
Whenever we are ready to create a new component, we have to copy several required files then rename them. Under this situation, I write a script to auto-generate those files by user's inputs.
> chore: add create-component script

- package.json
- src/components/atoms/SfBadge/README.md
- src/components/atoms/SfBadge/SfBadge.html
- src/components/atoms/SfBadge/SfBadge.js
- src/components/atoms/SfBadge/SfBadge.scss
- src/components/atoms/SfBadge/SfBadge.spec.ts
- src/components/atoms/SfBadge/SfBadge.stories.js
- src/components/atoms/SfBadge/SfBadge.vue
- src/components/molecules/SfCallToAction/SfCallToAction.spec.ts
Finish SfBadge Component
supports different types and full-width via CSS modifier
> chore: add SfBadge component

- scripts/create-component.js
No related issue, I'm sorry 🙃 
I found out some typos, unuseful spaces that could create prettier/lint errors and I added the missing component name into the stories.js in place of "Component".
That's it.
> fix typos, add missing info, fix prettier errors

- packages/vue/src/components/atoms/SfBadge/SfBadge.scss
- packages/vue/src/components/atoms/SfBadge/SfBadge.stories.js
- packages/vue/src/components/atoms/SfBreadcrumbs/SfBreadcrumbs.js
- packages/vue/src/components/atoms/SfBreadcrumbs/SfBreadcrumbs.stories.js
- packages/vue/src/components/atoms/SfCircleIcon/SfCircleIcon.stories.js
- packages/vue/src/components/atoms/SfPrice/SfPrice.stories.js
- packages/vue/src/components/atoms/SfRating/SfRating.stories.js
- packages/vue/src/components/molecules/SfGallery/SfGallery.js
- packages/vue/src/components/molecules/SfGallery/SfGallery.stories.js
#123 
I refactored the documentation for SCSS vars, CSS modifiers in the atoms folder by moving it to Storybook info tab and removing the README since it's redundant.
> Document SCSS variables, CSS modifiers In Atoms

- packages/vue/html.js
- packages/vue/index.js
- packages/vue/js.js
- packages/vue/src/components/organisms/SfTopBar/SfTopBar.html
- packages/vue/src/components/organisms/SfTopBar/SfTopBar.js
- packages/vue/src/components/organisms/SfTopBar/SfTopBar.scss
- packages/vue/src/components/organisms/SfTopBar/SfTopBar.spec.ts
- packages/vue/src/components/organisms/SfTopBar/SfTopBar.stories.js
- packages/vue/src/components/organisms/SfTopBar/SfTopBar.vue
https://github.com/DivanteLtd/storefront-ui/issues/139
- Added the `SfTopBar` component, with tests, styles and stories.
- TopBar is hidden on screens less than `$desktop-min`
- TopBar uses three slots: `default` customises center content, `left` customises `left` content and `right` customises `right` content
> [ Desktop ] Create SfTopBar

- packages/shared/styles/components/SfDivider.scss
- packages/vue/src/components/atoms/SfDivider/SfDivider.html
- packages/vue/src/components/atoms/SfDivider/SfDivider.js
- packages/vue/src/components/atoms/SfDivider/SfDivider.spec.ts
- packages/vue/src/components/atoms/SfDivider/SfDivider.stories.js
- packages/vue/src/components/atoms/SfDivider/SfDivider.vue
#170 
Create divider component.
>  #170 [ Desktop / Mobile ] implement SfDivider

- packages/vue/src/components/atoms/SfDivider/SfDivider.stories.js
> Fix prettier warnings in sfDivider

- package.json
- packages/vue/scripts/component-template/component.html
- packages/vue/scripts/component-template/component.js
- packages/vue/scripts/component-template/component.spec.ts
- packages/vue/scripts/component-template/component.stories.js
- packages/vue/scripts/component-template/component.vue
- packages/vue/scripts/create-component.js
- scripts/create-component.js
- yarn.lock
#152
I fixed the path where the scss must be created. The script was already into packages/vue and must run from here to use it.
> ref. #152 improve create-component after monorepo

- packages/vue/src/components/organisms/SfCarousel/SfCarousel.html
- packages/vue/src/components/organisms/SfCarousel/SfCarousel.js
- packages/vue/src/components/organisms/SfCarousel/SfCarousel.stories.js
https://github.com/DivanteLtd/storefront-ui/issues/206
Creates slots for <code>SfCarousel</code> controls
> Creates slots for carousel controls

- packages/vue/docs/introduction.md
I added to the documentation a part which explains, how to test/run StorefrontUI independently of an own project.
website content of https://docs.storefrontui.io/introduction.html#current-state-of-the-project
> improve documentation for trying out StorefrontUI

- packages/shared/styles/components/SfProductCard.scss
- packages/vue/src/components/molecules/SfProductCard/SfProductCard.html
- packages/vue/src/components/molecules/SfProductCard/SfProductCard.js
- packages/vue/src/components/molecules/SfProductCard/SfProductCard.spec.ts
- packages/vue/src/components/molecules/SfProductCard/SfProductCard.stories.js
- packages/vue/src/examples/pages/category/Category.vue
1. Remove `onWishlistColor` prop
2. Change `onWishlistIcon` and `onWishlist` to `isOnWishlistIcon` and `isOnWishlist`
3. Make Wishlist icon always be visible when product is on wishlist
4. Allow to disable showing wishlist icon when `wishlistIcon` received `false`
> #249 SfProductCard tweaks

- packages/shared/styles/components/SfBannerGrid.scss
- packages/vue/src/examples/pages/home/Home.vue
Changed column child to `display: flex` and stretch it to full height
before
after
> Fixed SfBannerGrid column child stretch

- packages/shared/styles/components/SfHeading.scss
- packages/vue/src/components/atoms/SfHeading/SfHeading.stories.js
- packages/vue/src/components/molecules/SfSection/SfSection.html
- packages/vue/src/components/molecules/SfSection/SfSection.js
- packages/vue/src/components/molecules/SfSection/SfSection.stories.js
#261
Changed default SfHeading and SfSection style to underline on mobile
> SfHeading && Sfsection tweaks

- packages/vue/src/components/atoms/SfCheckbox/SfCheckbox.html
- packages/vue/src/components/atoms/SfIcon/SfIcon.js
- packages/vue/src/components/atoms/SfIcon/SfIcon.spec.ts
- packages/vue/src/components/atoms/SfIcon/SfIcon.stories.js
- packages/vue/src/components/molecules/SfAlert/SfAlert.html
- packages/vue/src/components/molecules/SfCharacteristic/SfCharacteristic.html
- packages/vue/src/components/molecules/SfCounter/SfCounter.html
- packages/vue/src/components/molecules/SfMenuItem/SfMenuItem.html
- packages/vue/src/components/molecules/SfModal/SfModal.html
- packages/vue/src/components/molecules/SfPagination/SfPagination.html
- packages/vue/src/components/molecules/SfProductCard/SfProductCard.html
- packages/vue/src/components/organisms/SfBottomNavigation/SfBottomNavigation.stories.js
- packages/vue/src/components/organisms/SfSidebar/SfSidebar.html
- packages/vue/src/components/organisms/SfStoreLocator/SfStoreLocator.html
- packages/vue/src/components/organisms/SfStoreLocator/_internal/SfStore.html
- yarn.lock
[#293 ](https://github.com/DivanteLtd/storefront-ui/issues/293)
Rename `path` to `icon` for a better convention
> #293 rename props path to icon SfIcon

- packages/vue/src/components/organisms/SfAccordion/SfAccordion.js
- packages/vue/src/components/organisms/SfAccordion/SfAccordion.vue
- packages/vue/src/components/organisms/SfAccordion/_internal/SfAccordionItem.html
https://github.com/DivanteLtd/storefront-ui/issues/280
Fade in/out effect added to SfAccordion component
> Fade in/out effect added to SfAccordion component

- packages/vue/docs/assets/members.json
- packages/vue/docs/contributing/become-a-contributor.md
- packages/vue/docs/introduction.md
#330 
1. Fix broken links (label system in `become-a-contributor.md`, to contributor guide in `introduction.md`
2. Update Nico's job title and location
N/A
> Fix #330 - Fix links to contributor guide, label system and Nico's location

- packages/vue/docs/.vuepress/config.js
- packages/vue/docs/.vuepress/enhanceApp.js
- packages/vue/scripts/create-vue-components-docs.js
#365 Auto-Docs-Generation doesn't retrieve SCSS details anymore
This fixes #365.
- Fix for issue
- SfCollectedProduct added to VuePress config
> #365 Fix for Auto-Docs-Generation doesn't retrieve SCSS details anymore

- packages/shared/styles/components/SfAccordion.scss
- packages/vue/scripts/create-vue-components-docs.js
#370 [Docs][Automation] Fix CSS modifier parsing and add possibility to ignore modifiers
- Fix CSS modifiers sometimes only being partially extracted.
- Add possibility to ignore CSS modifiers by using the no-docs annotation instead of the modifier annotation.
> #370 auto docs css modifiers

- packages/shared/styles/components/SfSidebar.scss
- packages/vue/src/components/molecules/SfSlidingSection/SfSlidingSection.js
- packages/vue/src/components/organisms/SfSidebar/SfSidebar.js
- added removed scroll lock to `beforeDestroy` for SfSidebar & SfSlidingSection
- prevent SfSlidingSection warchers to error on ssrto 
- changed SfSidebar inline scroll lock to class 
- fixed componen options order (https://vuejs.org/v2/style-guide/#Component-instance-options-order-recommended)
> Bugfix/Body Scroll Lock

- packages/vue/package.json
- packages/vue/scripts/postinstall.js
In commit a976c5b7 the generation of Playground.vue on postinstall got
accidentally removed. This re-adds it.
> Re-add missing Playground.vue generation

- packages/shared/styles/components/SfSteps.scss
- packages/vue/src/components/molecules/SfSteps/SfSteps.html
- packages/vue/src/components/molecules/SfSteps/SfSteps.js
#335
I refactored the way the progress bar used to work so it simplified the CSS code quite a bit, I also made sure to animate the `transform` property to keep the transition performant.
> Animate progress bar in steps component

- package.json
- packages/shared/.lintstagedrc.yml
- packages/shared/package.json
- packages/vue/.lintstagedrc.yml
- packages/vue/package.json
#396 [Bug] Auto-lint on precommit not working anymore
- install `lint-staged` and (underlying) `husky` as recommended for multi-package monorepo
- setup precommit hooks in both packages (_vue_ and _shared_)
- use `vue-cli-service lint` for _vue_ and `eslint --fix` for _shared_
- move lerna to devDeps
- minor clean-ups in _package.json_s
> #385 Fix precommit lint

- packages/vue/src/components/atoms/SfImage/SfImage.js
#437 SfImage `lazy` set to false shows another image on bottom
This fixes #437.
By design, lozad is supposed to be added _once_ to an element. But as we
allow to change the "lazy" attribute dynamically for our SfImages, this
triggers strange behavior: The reference to the IMG element which lozad
inserts after loading isn't fully removed from the DOM and another one
is then added to the picture tag, resulting in two images.
The fix consists of removing the spurious IMG tag when the "lazy"
attribute changes from true to false.
Also, when the attribute changes from false to true, the initialization
if lozad is retriggered.
> #437 Fix lozad adding new IMG tags if a multi-size src is provided

- packages/vue/config/storybook/webpack.config.js
It doesn't work with one single entry, so I added another one (`noinspection` is a WebStorm-specific comment which works similar to `eslint-disable`).
Looks like a bug in storysource.
--- 
edit: doesn't work with 2 options on CI either. I'll remove the `options` part completely. 🤷🏻‍♂️
#482, commit 63d2d51.
> Fix uglyCommentsRegex in storysource

- packages/shared/styles/components/SfCircleIcon.scss
- packages/shared/styles/components/SfHeader.scss
#531 
Fix css specificy for nested components:
- SfButton in SfCircleIcon
- SfCircleIcon in SfHeader
compare server and client
> bugfix/css specificity for SfCircleIcon. SfHeader

- packages/vue/scripts/create-vue-components-docs.js
This fix accounts for false positives in auto-generated components docs when a SCSS files contains CSS variables. Those look like BEM modifiers but are now explicitly excluded.
(Instead of making the reg exp. more complicated I decided to use a dedicated check for that.)
> Fix false positives in CSS modifiers on Vue components docs generation

- packages/vue/docs/getting-started.md
N/A
Specify min css-loader version (otherwise scss will not load images properly from assets directory) 
N/A
> [DOCS] add minimum css-loader version to the docs

- packages/vue/src/components/organisms/SfCarousel/SfCarousel.html
Closes #539
Mention #548
Change DOM elements order to solve problem
> fix(template): broken sf-carousel__wrapper unclickable space

- packages/shared/styles/components/SfHeader.scss
Close #575
set `width: auto` for `.sf-header__logo.sf-image`
> fix(organisms): unwitting logo image stretch in SfHeader

- packages/vue/src/components/organisms/SfTabs/_internal/SfTab.js
Closes #601
just check document width before run click script  
[[before changes]](https://storybook.storefrontui.io/?path=/story/organisms-tabs--common)
[[after changes]](https://deploy-preview-602--storefrontui-storybook.netlify.com/?path=/story/organisms-tabs--common)
> fix(organisms): the second click SfTab title on desktop hide content

- packages/vue/package.json
- yarn.lock
#525
Percy is useful but it screenshots limit it's burning too fast. We should use https://storybook.js.org/docs/testing/automated-visual-testing/#example-using-puppeteer-and-jest to Automated Visual Testing
> chore: remove percy

- packages/shared/styles/components/SfAccordion.scss
- packages/shared/styles/components/SfTabs.scss
Closes: #524 
Closes: #558
Move to top chevron in components for multiline header
[after]
[before]
> fix(style): chevron position in multiline header

- packages/shared/styles/components/SfHeader.scss
- packages/vue/src/components/organisms/SfHeader/SfHeader.html
- packages/vue/src/components/organisms/SfHeader/SfHeader.js
- packages/vue/src/components/organisms/SfHeader/SfHeader.stories.js
Closes #625
support #622
[with SfSearch]
[without SfSearch]
> feat: mobile header improvements 

- packages/vue/src/components/molecules/SfGallery/SfGallery.vue
- packages/vue/src/components/molecules/SfModal/SfModal.vue
- packages/vue/src/components/organisms/SfSidebar/SfSidebar.vue
when you use body-scroll-lock without $nextTick you have undefined on refs, then you should use next tick to fix it
> fix: move bodyLock to nextTick

- packages/shared/styles/components/SfAddToCart.scss
remove override to fix disable button color
> fix: add to cart disable style

- packages/shared/styles/components/SfBanner.scss
- packages/vue/src/components/molecules/SfBanner/SfBanner.stories.js
- packages/vue/src/components/molecules/SfBanner/SfBanner.vue
- packages/vue/src/examples/pages/home/Home.vue
> refactor: move background css variable to inline styles

- packages/shared/styles/components/SfSelect.scss
- packages/vue/src/components/molecules/SfSelect/SfSelect.vue
fix z-index 💚 in SfSelect dropdown
> fix: z-index in SfSelect dropdown

- packages/vue/src/examples/pages/my-account/_internal/ShippingDetails.vue
fix transition group key linter warning
> fix:  transition group on shipping details view

- packages/shared/styles/components/SfInput.scss
> fix: css specificity for show password button

- packages/vue/src/components/molecules/SfGallery/SfGallery.vue
- packages/vue/src/components/organisms/SfCarousel/SfCarousel.spec.js
- packages/vue/src/components/organisms/SfCarousel/SfCarousel.vue
- packages/vue/src/components/organisms/SfGroupedProduct/SfGroupedProduct.vue
- packages/vue/src/components/organisms/SfHero/SfHero.vue
glide.js must have child nodes to work
> fix: prevent glide mount for empty container

- packages/vue/src/components/molecules/SfBanner/SfBanner.vue
- packages/vue/src/components/molecules/SfSlidingSection/SfSlidingSection.vue
- packages/vue/src/components/organisms/SfContentPages/SfContentPages.vue
- packages/vue/src/components/organisms/SfFooter/SfFooter.vue
- packages/vue/src/components/organisms/SfMegaMenu/SfMegaMenu.vue
- packages/vue/src/utilities/mobile-observer.js
- packages/vue/src/utilities/mobile-observer.spec.js
Fixes #581 
This PR adds a new utility called mobile observer with the following features:
- adds one single event listener on window.matchMedia
- return a computed property isMobile that is reactive
- has a destroy function to clean up if no component is using it anymore
The new utility is bound to all the component that were implementing the isMobile behaviour.
The utility can be used in a similar fashion as the well know vuex helpers `mapComputed or mapState`
```javascript
computed : {
...mapMobileObserver()
}
```
this way the components receive a new computed property called `isMobile`
The utility keeps track of the amount of 'clients' that is serving and if the last one is destroyed it removes the event listeners and perform a basic cleanup.
The utility is compatible with SSR, and it …
> #581 Create Mobile observer

- packages/shared/styles/components/organisms/SfFooter.scss
- packages/vue/src/components/organisms/SfFooter/SfFooter.stories.js
- packages/vue/src/components/organisms/SfFooter/SfFooter.vue
- packages/vue/src/components/organisms/SfHeader/SfHeader.vue
adjust SfFooter to SfHeader styling API
[desktop]
> refactor: adjust SfFooter to SfHeader and MegaMenu

- packages/vue/docs/.vuepress/components/SfDocsColors.vue
- packages/vue/docs/.vuepress/components/SfDocsSizes.vue
- packages/vue/docs/contributing/creating-new-component.md
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.stories.js
Closes #750 Docs build on develop fails
* Update some SCSS imports in Vue files for docs
* Update a link in a MD file to a MD file which was moved
* Use `colors` as a named import for `colorsValues`. This is already declared in other files and hence expected in the auto-generation script.
> #750 fix: docs build fails due to outdated links

- packages/shared/styles/components/atoms/SfOverlay.scss
Closes #772
There was an issue between the opacity bound for the aspect of the SfOverlay and the fade transition's opacity. To get rid of this conflict, as the opacity of the SfOverlay was only for esthetical purposes, I removed it's opacity and used a rgba like it's done for the SfImage [example](https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/shared/styles/components/atoms/SfImage.scss#L3).
You might ask the question but I couldn't use the `rgba` function from sass in which you just have to pass a color and an opacity like this example.
```
rgba($color, $opacity)
```
Why couldn't I ? Because css variables are dynamic and so they can't be compiled at build time by sass. Doing this was resulting as if there was no color on the background.
Also I've considered using a …
> fix: overlay transition opacity conflicting

- packages/shared/styles/_global.scss
No related issues
I've added `font-display: swap` CSS rule to `@font-face` declaration in google fonts. This rule prevent browsers to block displaying font until custom fonts (from Google Fonts in this case) are loaded. This should improve page speed loading time.
If applicable:
> Add font-display: swap rule to google fonts

- packages/shared/styles/components/organisms/SfProductCard.scss
Fix position of addToCart button
If applicable:
> fix: SfProductCard - addToCart button position

- packages/vue/src/components/atoms/SfInput/SfInput.vue
Closes #782 
Add `type="button"` to SfButton with show-password-icon
If applicable:
> fix: SfInput - show-password button stops triggering submit

- packages/shared/styles/components/atoms/SfButton.scss
Closes #700 
Change background color on hover for variant colors
If applicable:
> fix: SfButton variants - background color on hover

- packages/shared/styles/components/atoms/SfButton.scss
Closes #777 
Add transparent bcg variable to outline modifiers
If applicable:
> fix: SfButton fix --outline modifiers background

- packages/vue/src/components/organisms/SfGroupedProduct/SfGroupedProduct.stories.js
Closes #797 
Add missing hasCarousel prop to stories
If applicable:
> fix: add missing hasCarousel prop to stories

- packages/shared/styles/helpers/_typography.scss
Scope of work
Add mixin for font
Use it like this:
```css
@include font(--breadcrumbs-font, 400, var(--font-size-small), 1.6, var(--body-font-family-secondary));
```
If applicable:
> add: scss font mixin

- packages/shared/styles/variables/_typography.scss
after a long analyst, I think we can use the same body font sizes on desktop and mobile
``` scss
--font-size-extra-small: 0.75rem; //12px
--font-size-small: 0.875rem; //14px
--font-size-regular: 1rem; //16px
--font-size-big: 1.125rem; //18px
```
If applicable:
> fix: font sizes variables

- packages/shared/styles/variables/_typography.scss
additional font-weight variable 
If applicable:
> fix: font-weight variables

- packages/shared/styles/components/atoms/SfColor.scss
- packages/vue/src/components/atoms/SfColor/SfColor.vue
add SfBadge with SfIcon on selected only for mobile
refactor SfColor styles 
If applicable:
> refactor(atoms): SfColor

- packages/shared/styles/variables/_layout.scss
- packages/shared/styles/variables/_typography.scss
After a long discussion about the name of 10px font size we decide to change our variable name convention  to more flexibility
Before | After
------------ | -------------
--font-weight-light: 300 | --font-light: 300
--font-weight-regular: 400 | --font-normal: 400
--font-weight-bold: 500 | --font-medium: 500
--font-weight-extra-bold: 600 | --font-semibold: 600
undefined | --font-bold: 700
undefined | --font-extra-bold: 800
undefined | --font-black: 900
Before | After
------------ | -------------
undefined | --font-2xs: 10px
--font-size-extra-small: 0.75rem | --font-xs: 12px
--font-size-small: 0.875rem | --font-sm: 14px
--font-size-regular: 1rem | --font-base: 16px
--font-size-big: 1.125rem | --font-lg: 18px
undefined | --font-xl: 24px
Before | After
------------ | ------------- …
> fix: global variables

- packages/vue/src/components/organisms/SfBottomNavigation/_internal/SfBottomNavigationItem.vue
https://github.com/DivanteLtd/shopware-pwa/pull/467
- fix issue with click event on bottom item menu by adding to SfBottomNavigationItem `v-on="$listeners"` to forward events
If applicable:
> fix: forwarded events on SfBottomNavigationItem

- packages/shared/styles/components/atoms/SfInput.scss
no
SfInput css: remove spinner buttons on input type number on firefox.
If applicable:
> fix: remove spinners on input number on firefox 

- packages/vue/src/components/organisms/SfAccordion/SfAccordion.stories.js
- packages/vue/src/components/organisms/SfAccordion/SfAccordion.vue
- packages/vue/src/examples/pages/category/Category.vue
- packages/vue/src/examples/pages/checkout/_internal/ConfirmOrder.vue
Closes #954 
- add `open` prop 
- add the possibility to open more that one item by passing header or headers in array
- updated stories
- deprecated `firstOpen` to be removed in 1.0.0 due to the fact this change is breaking change
> feat: add open by header in SfAccordion

- packages/vue/src/utilities/directives/focus-directive.js
#960 
- remove blur from focus directive, it breaks elements that they already have blur e.g. SfSelect
> fix: remove blur from focus-directive

- packages/vue/src/components/atoms/SfQuantitySelector/SfQuantitySelector.vue
#960 
Minus sign "-" was read as pause so has been changed to &minus;
> fix: minus sign in SfQuantitySelector

- packages/shared/styles/components/molecules/SfModal.scss
none
set font for SfModal content
If applicable:
> fix: default font for SfModal

- packages/shared/styles/components/organisms/SfProductCard.scss
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
- packages/vue/src/examples/pages/category/Category.vue
> fix: move add to cart button outside the link

- packages/shared/styles/components/molecules/SfAddToCart.scss
- packages/vue/src/components/molecules/SfAddToCart/SfAddToCart.vue
https://github.com/DivanteLtd/next/issues/425
Closes #1083
SfQuantitySelector is always before SfButton "Add to cart". For mobile, you should use SfBottomNavigation to Add To Cart. 
If applicable:
> fix(a11y): order of SfQuantitySelector in SfAddToCart

- packages/shared/styles/components/organisms/SfBottomNavigation.scss
- packages/vue/src/components/organisms/SfBottomNavigation/_internal/SfBottomNavigationItem.vue
Closes #
Related: https://github.com/DivanteLtd/next/issues/427
SfBottomNavigationItem cant be a button because inside there is a SfCircleIcon which is a button. Click on SfBottomNavigation only moves click event to the button so from the a11y side everything is working fine.
If applicable:
> fix: change button to div on SfBottomNavigation

- packages/shared/styles/components/organisms/SfCollectedProduct.scss
- packages/shared/styles/components/organisms/SfProductCard.scss
- packages/vue/src/examples/pages/cart/Cart.vue
Closes #
Elements that are visible only on hover now they are visible also on focus
> a11y: clickable elements visible on focus

- packages/shared/styles/components/atoms/SfImage.scss
- packages/vue/src/components/atoms/SfImage/SfImage.vue
https://github.com/DivanteLtd/next/issues/398
Closes #1066
added `noscript` fallback image only for lazy-loaded images and add few improvements
If applicable:
> fix: noscript fallback for SfImage

- packages/shared/styles/components/organisms/SfProductCard.scss
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
Closes #
After some research and discussions, I decided to fix SfProductCard links as simple as possible without complicated hacks. According to other ecommerce solutions and our UX designer @mbaran-dvnt, title and image should be linkable. So the best way is to make these two elements as separate links.
If someone finds here better solution taking our case into account, feel free to comment :)
If applicable:
> fix: button add to card on SfProductCard

- packages/vue/docs/customization.md
- packages/vue/src/components/molecules/SfAddToCart/SfAddToCart.md
- packages/vue/src/components/molecules/SfBanner/SfBanner.md
https://github.com/DivanteLtd/storefront-ui/issues/1157
Fixed broken links with below pages
- [Customization](packages/vue/docs/customization.md)
- [AddToCart](packages/vue/src/components/molecules/SfAddToCart/SfAddToCart.md) component
- [Banner](packages/vue/src/components/molecules/SfBanner/SfBanner.md) component
If applicable:
> [docs] Fixed broken links from the documentation

- packages/shared/styles/components/molecules/SfDropdown.scss
> fix: specificity for cancel button in SfDropdown

- packages/vue/src/components/atoms/SfImage/SfImage.vue
Revert ref="image" to SfImage. It's used in SfGallery for zoom feat
If applicable:
> fix: revert image refs in SfImage

- packages/vue/src/components/atoms/SfCheckbox/SfCheckbox.vue
> fix: checked icon on SfCheckbox

- packages/shared/styles/components/atoms/SfCheckbox.scss
- packages/shared/styles/components/molecules/SfFilter.scss
- packages/shared/styles/components/organisms/SfSidebar.scss
adjust checkbox and filter label size to design, use 14px 
after changes
before changes
If applicable:
> fix: checkbox font size

- packages/shared/styles/components/organisms/SfCollectedProduct.scss
- packages/vue/src/components/organisms/SfCollectedProduct/SfCollectedProduct.vue
Closes #1234 
SfCollectedProduct change title font-size and add title right margin to avoid overlapping icon.
> fix: SfCollected product title display

- packages/shared/styles/components/organisms/SfMegaMenu.scss
Fixed typo in variable name in mega-menu component `--mega-menu-column-header-margin`
If applicable:
> fix typo in mega menu

- packages/shared/styles/components/atoms/SfButton.scss
- packages/vue/src/components/atoms/SfButton/SfButton.stories.js
- packages/vue/src/components/atoms/SfButton/SfButton.vue
Closes #1241 
Add props to change component from native button to a tag (nativeButton) and link prop with link for "a" tag. Component is switching from "button" to "a" tag depending on boolean prop, if true it is a "button" if false it's SfLink component. Style is adjusted accordingly.
> feat: add sflink to button

- packages/shared/styles/components/organisms/SfHero.scss
- packages/vue/src/components/organisms/SfHero/SfHero.stories.js
Closes #1245
Added modifiers and custom classes in second hero item in stories
> fix: providing classes does not affect the position of slider content in SfHero

- packages/shared/styles/components/organisms/SfProductCard.scss
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
https://github.com/DivanteLtd/storefront-ui/issues/1240
Closes #1240 
SfProductCard - move the whishlist button inside image-wrapper to position it relatively.
> fix: wishlist position in relation to image

- packages/vue/src/components/molecules/SfSelect/SfSelect.vue
Closes #1270 [BUG] Can't put @blur for validation purposes on SfSelect
Move `v-on` to the div that has focus.
If applicable:
> fix: move v-on to div that has focus (#1270)

- packages/shared/styles/components/organisms/SfHero.scss
- packages/vue/src/components/organisms/SfHero/SfHero.vue
Closes #1279 
Controls wrapper has pointer-events none and arrows have all pointer-events
No visual changes
> fix: SfArrow in SfHero component covers other pointer actions

- packages/vue/docs/contributing/become-a-contributor.md
Closes #1294 
Roadmap link changed to proper one in docs.
> fix(docs): link to roadmap fixed

- packages/vue/docs/contributing/github-guidelines.md
- packages/vue/docs/design/color-palette.md
Closes #1309 
Fixes documentation broken links a snippets formatting
If applicable:
> docs: fix documentation broken links and snippets formatting

- packages/vue/src/components/organisms/SfHero/SfHero.spec.js
Closes #1314 
`findAll` method changed to `findAllComponents`
If applicable:
> refactor: change findAll methods to findAllComponents

- packages/shared/styles/components/atoms/SfInput.scss
Closes #1323 
border-radius and appearance none added to input
> fix: SfInput has a border radius and inner shadow on iOS/Safari 

- packages/vue/src/components/organisms/SfAccordion/SfAccordion.stories.js
- packages/vue/src/components/organisms/SfAccordion/SfAccordion.vue
Closes #1307
SfAccordion - when you pass 'all'  to open prop all the items should be open by default. Appropriate story was added.
> feat: SfAccordion add prop option to open all items by default

- packages/vue/src/components/molecules/SfScrollable/SfScrollable.vue
Closes #1329 
An additional condition has been added that should fix the bug.
If applicable:
> fix: offsetHeight of SfScrollable

- packages/shared/styles/components/molecules/SfModal.scss
Closes #1371 
max-height added for modal
If applicable:
> fix: modal cuted on desktop

- packages/vue/src/components/atoms/SfImage/SfImage.stories.js
Closes #1310 
Add rootMargin props to stories, because empty string causes error.
> fix: SfImage rootmargin error in storybook fixed on firefox

- packages/vue/src/components/molecules/SfSelect/SfSelect.stories.js
Closes #
There were wrong components: SfComponentSelect instead SfSelect and SfComponentSelectOption instead SfSelectOption
If applicable:
> fix: story with error msg fixed

- packages/vue/src/components/molecules/SfSteps/_internal/SfStep.vue
Closes #1389
Change lifecycle method from mounted to created to let use it during SSR.  
no
If applicable:
> fix: sfstep change lifecycle method to created

- packages/shared/styles/components/molecules/SfDropdown.scss
w/o issue 
Modifier --up adjusted to new SfDropdown
If applicable:
> fix: up modifier fixed in SfDropdown

- packages/shared/styles/components/molecules/SfSelect.scss
Closes #1409 
Add background img url variable to SfSelectOption component to remove warn on nuxt.
> fix: sfselect background image url

- packages/vue/docs/pull-off-components.md
Add information to pull off components docs  about adding fse package as dependency in order to run copy-components script properly. 
If applicable:
> hotfix: change pull off components docs

- packages/shared/styles/components/molecules/SfSelect.scss
Closes #1455 
Deleted display none for placeholder that was causing this bug and added a bit darker color for dropdown to differentiate from placeholder
If applicable:
> fix: SfSelect: clicking on an option results in another being selected instead on MacOS

- packages/shared/styles/components/atoms/SfTextarea.scss
- packages/vue/src/examples/others/form/Form.vue
Closes #1500 
Adjust the font properties to new ones and add SfTextarea to the Form example. 
If applicable:
> fix: fonts in SfTextarea and add SfTextarea to form example

- packages/vue/src/utilities/mobile-observer.js
Closes #1494
There was an error about null assignment to isMoblie so we need to check if there is no null. 
No visual changes 
If applicable:
> fix: Footer menu opens without clicking on it

- packages/shared/styles/components/atoms/SfButton.scss
Closes #
Buttons as text has the same color as link
If applicable:
> fix: button text modifier color changed 

- packages/shared/styles/components/organisms/SfCollectedProduct.scss
Closes #1486 
added background and color for icon in remove btn
If applicable:
> fix: color and background for remove btn in SfCollectedProduct

- packages/shared/styles/components/molecules/SfColorPicker.scss
- packages/vue/src/components/molecules/SfColorPicker/SfColorPicker.vue
Closes #1497 
Removed opacity that affected SfColor and SfOverlay added
No visual changes 
If applicable:
> fix: SfColorPicker opacity affects SfColor

- packages/vue/src/components/molecules/SfSelect/SfSelect.stories.js
Closes #1507 
Replace SfProductOption with span inside SfSelect to aviod possible SSR mismatch error. 
If applicable:
> fix: SfSelect stories remove SfProductOption

- packages/vue/src/components/atoms/SfImage/SfImage.stories.js
- packages/vue/src/components/atoms/SfImage/SfImage.vue
no
SfImage - add progressive lazy loading story and change code accordingly, fix story "with src" removing "srcset" property.
If applicable:
> fix: sfimage fix in story, add progressive lazy loading with story

- packages/shared/styles/components/organisms/SfCarousel.scss
Closes #1548
Made SfCarouselItem a flex container with items centered along x-axis
Before: 
After:
It also does not break the behavior when more than 4 items:
If applicable:
> Center SfCarousel content to fix #1548

- packages/shared/styles/components/organisms/SfProductCard.scss
Closes #1598 
after:
before:
If applicable:
> fix: img adjusted to mobile view

- packages/vue/src/components/organisms/SfHero/SfHero.vue
> hotfix: SfHero - left arrow below an image

- packages/vue/src/components/molecules/SfSelect/SfSelect.stories.js
Closes #1613 
selectedValue added to data
If applicable:
> hotfix: SfSelect - selectedValue is not defined 

- packages/vue/src/components/atoms/SfProperty/SfProperty.stories.js
> hotfix: SfProperty - missing data in slots examples

- packages/vue/src/components/organisms/SfStoreLocator/SfStoreLocator.stories.js
Closes #1631
Control options changed to object in SfStoreLocator tileServerUrl prop .
If applicable:
> fix: SfStoreLocator storybook - change control options to object 

- packages/vue/src/components/molecules/SfGallery/SfGallery.stories.js
Closes #1637 
Default value for slider options.
If applicable:
> hotfix: SfGallery - invalid prop type

- packages/vue/src/components/atoms/SfPrice/SfPrice.stories.js
> hotfix: SfPrice - lack of price in examples

- packages/vue/src/components/molecules/SfFilter/SfFilter.stories.js
Closes #1632 
Story for count slot in SfFilter 
If applicable:
> hotfix: SfFilter - wrong example in "use count slot"

- packages/vue/src/components/organisms/SfSidebar/SfSidebar.stories.js
Closes #1634 
Change the way of rendering docs to iframe instead of inline. Need to be styled, because iframe is too small to see whole component and shows only mobile mode. 
If applicable:
> fix: SfSidebar change rendering of docs to iframe on storybook

- packages/vue/src/components/atoms/SfArrow/SfArrow.vue
- packages/vue/src/components/atoms/SfCircleIcon/SfCircleIcon.vue
- packages/vue/src/components/atoms/SfOverlay/SfOverlay.vue
Closes #1647 
Additional listeners removed from SfCircleIcon and SfArrow.
Fix listener in SfOverlay to properly emit click event.
If applicable:
> fix: listeners in functional components 

- packages/vue/src/stories/getting-started/pull-off-components.md
- packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx
- packages/vue/src/stories/releases/v0.10.0/v0.10.0.stories.mdx
- packages/vue/src/stories/releases/v0.10.1/v0.10.1.stories.mdx
no
Add docs for 0.10.1 release.
If applicable:
> chore: add 0.10.1 release docs

- packages/vue/src/components/organisms/SfHero/SfHero.vue
- packages/vue/src/stories/releases/v0.10.1/v0.10.1.stories.mdx
no
Add client class to right control in order to avoid loading arrow on ssr.
If applicable:
> fix: sfhero add client class to right control

- packages/vue/src/components/organisms/SfSidebar/SfSidebar.vue
- packages/vue/src/stories/releases/v0.10.1/v0.10.1.stories.mdx
Closes #1665 
Revert changes implemented in 0.10.0 version to avoid bugs.
Add body scroll lock to whole sidebar component, not to content to avoid scrolling body.
Adding scrollbar should be made in new patch version because when using SfScrollabe it needs more changes in elements and style.
If applicable:
> fix: SfSidebar revert last changes 

- packages/vue/src/components/atoms/SfCimage/SfCimage.vue
- packages/vue/src/stories/releases/v0.10.1/v0.10.1.stories.mdx
Closes #1672 
- Image not defined in SSR
If applicable:
> #1672 fix c image ssr

- packages/shared/styles/components/organisms/SfGroupedProduct.scss
- packages/vue/src/components/organisms/SfGroupedProduct/SfGroupedProduct.stories.js
- packages/vue/src/components/organisms/SfGroupedProduct/SfGroupedProduct.vue
- packages/vue/src/components/organisms/SfGroupedProduct/_internal/SfGroupedProductItem.vue
Closes #1636 
Fix styling for mobile view with hasCarousel prop set to true. 
Set default number of sliders on desktop to 2.
Story fix - add more products.
If applicable:
> fix: SfGroupedProduct change mobile view for slider and adjust story

- packages/shared/styles/components/organisms/SfHeader.scss
- packages/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.vue
- packages/vue/src/components/organisms/SfHeader/SfHeader.stories.js
- packages/vue/src/stories/releases/v0.10.1/v0.10.1.stories.mdx
Closes #1635
Fix style for mobile navigation modifier and isNavVisable prop. 
Add menuItem for mobile to story. 
If applicable:
> fix: sfheader mobile navigation

- packages/vue/src/components/organisms/SfHero/SfHero.vue
- packages/vue/src/stories/releases/v0.10.3/v0.10.3.stories.mdx
Closes #1640 
Fix the condition to init glide only when there is more than one item.
If applicable:
> fix: SfHero add condition to init glide when more than one item

- packages/vue/src/components/molecules/SfSearchBar/SfSearchBar.stories.js
- packages/vue/src/components/molecules/SfSearchBar/SfSearchBar.vue
- packages/vue/src/stories/releases/v0.10.3/v0.10.3.stories.mdx
Closes #1692 
Add listeners computed property which allows adding more listeners to the search input. 
Adjust stories to this change.
If applicable:
> fix: SfSearchbar adding listeners 

- packages/shared/styles/components/organisms/SfProductCard.scss
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.stories.js
- packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
- packages/vue/src/stories/releases/v0.10.3/v0.10.3.stories.mdx
- packages/vue/src/stories/releases/v0.10.4/v0.10.4.stories.mdx
> fix: SfProductCard - picture and title shouldn't be only links

- packages/vue/src/components/molecules/SfRadio/SfRadio.stories.js
- packages/vue/src/components/molecules/SfRadio/SfRadio.vue
- packages/vue/src/stories/releases/v0.10.3/v0.10.3.stories.mdx
- packages/vue/src/stories/releases/v0.10.4/v0.10.4.stories.mdx
Closes #1604 
Add change event to the SfRadio to enable using by older browsers.
If applicable:
> fix: add change event to the SfRadio component

- packages/shared/styles/components/molecules/SfSelect.scss
- packages/vue/src/components/molecules/SfSelect/SfSelect.vue
- packages/vue/src/stories/releases/v0.10.3/v0.10.3.stories.mdx
- packages/vue/src/stories/releases/v0.10.4/v0.10.4.stories.mdx
> fix: Possible to open SfSelect when it is disabled 

- packages/vue/package.json
- packages/vue/src/stories/releases/v0.10.4/v0.10.4.stories.mdx
Closes #1659 
Add script to package.json to enable automatic adding SFUI storybook to users storybooks ([storybook composition](https://storybook.js.org/docs/react/workflows/package-composition)) 
If applicable:
> chore: enable automatic storybook composition 

- packages/vue/src/components/organisms/SfFooter/SfFooter.vue
- packages/vue/src/components/organisms/SfFooter/_internal/SfFooterColumn.vue
- packages/vue/src/stories/releases/v0.11.0/v0.11.0.stories.mdx
Closes #1667 
- Used `provide/inject`, watcher, and local data to make SfFooter work without JavaScript.
- Tested in `nuxt` branch and in Vue Storefront Next
If applicable:
> Fix #1667/sffooter without js

- packages/vue/src/components/organisms/SfAccordion/_internal/SfAccordionItem.vue
Closes #1668 (partly)
This is the first step for SfAccordion fix. With that small change, SfAccordion is visible without JS. It does not work (this will be introduced later in v11), but it can be viewed (for hotfix 10.4).
If applicable:
> feat: #1668 SfAccordion visual fix for hotfix 10.4

- packages/shared/styles/components/molecules/SfGallery.scss
- packages/vue/src/stories/releases/v0.10.5/v0.10.5.stories.mdx
Closes #1732 
Fix main image in SfGallery on Firefox.
If applicable:
> #1732 fix/sfgallery image not appearing on firefox

- packages/vue/src/components/atoms/SfIcon/SfIcon.vue
- packages/vue/src/stories/releases/v0.10.5/v0.10.5.stories.mdx
Closes #1766 
Change wrapping element of SfIcon to avoid ssr mismatch errors when it is put inside button (div inside button is not allowed html syntax). 
If applicable:
> fix: sficon replace div with span element

- packages/shared/styles/components/organisms/SfMegaMenu.scss
- packages/vue/src/stories/releases/v0.10.5/v0.10.5.stories.mdx
Closes #1751
Add class to sf-mega-menu__bar to upgrade specifity (avoid bar to show on desktop when in production mode).
If applicable:
> fix: SfMegaMenu bar shows on desktop

- packages/vue/src/components/molecules/SfModal/SfModal.vue
Fix showing and disappearing effect of modal when refreshing the page. 
If applicable:
> fix: SfModal blink effect on refresh

- packages/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.stories.js
- packages/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.vue
- packages/vue/src/stories/releases/v0.10.8/v0.10.8.stories.mdx
Closes #1835
for more details see #1838 
If applicable:
> fix: respect size of options list set as a prop on SfComponentSelect #1838 

- packages/shared/styles/components/atoms/SfButton.scss
- packages/vue/src/components/atoms/SfButton/SfButton.vue
- packages/vue/src/stories/releases/v0.10.9/v0.10.9.stories.mdx
Closes https://github.com/vuestorefront/storefront-ui/issues/1847
Removed disabled state - used aria-disabled instead.
> feat: remove disabled state from button, assure proper event trigger

- packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.stories.js
- packages/vue/src/components/organisms/SfProductCardHorizontal/SfProductCardHorizontal.vue
- packages/vue/src/stories/releases/v0.10.9/v0.10.9.stories.mdx
> fix: Impossible to access quantity during adding to cart 

- packages/vue/src/components/molecules/SfRadio/SfRadio.vue
- packages/vue/src/stories/releases/v0.10.9/v0.10.9.stories.mdx
> fix: SfRadio not working on Safari 11 & older

- packages/vue/src/components/molecules/SfNotification/SfNotification.stories.js
- packages/vue/src/components/molecules/SfNotification/SfNotification.vue
- packages/vue/src/stories/releases/v0.10.9/v0.10.9.stories.mdx
Closes #1765
Added persistent prop to render close slot conditionally.
> feat: provide an option to exclude closing button for SfNotification

- packages/vue/package.json
Added a missing dependency causing ```Error: @storefront-ui/vue tried to access glob, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.``` when using yarn2
If applicable:
> fix: add missing glob dependency

- packages/vue/src/components/molecules/SfGallery/SfGallery.vue
- packages/vue/src/stories/releases/v0.10.9/v0.10.9.stories.mdx
> fix: gallery missing alt on zoom

- packages/shared/styles/components/organisms/SfBottomNavigation.scss
- packages/vue/src/stories/releases/v0.10.9/v0.10.9.stories.mdx
> fix: bottom navigation adjusted the same wrapper size for the items

- packages/vue/src/components/organisms/SfAccordion/SfAccordion.stories.js
- packages/vue/src/components/organisms/SfAccordion/SfAccordion.vue
> fix: accordion items can be opened when are closed by click

- packages/nuxt-module/example/pages/index.vue
- packages/shared/styles/components/atoms/SfChevron.scss
- packages/shared/styles/components/atoms/SfInput.scss
- packages/shared/styles/components/molecules/SfComponentSelect.scss
- packages/shared/styles/components/molecules/SfSteps.scss
- packages/shared/styles/components/organisms/SfContentPages.scss
- packages/shared/styles/components/templates/checkout/SfShipping.scss
- packages/vue/src/components/pages/checkout/_internal/Shipping.vue
- packages/vue/src/components/pages/home/Home.vue
- packages/vue/src/stories/getting-started/2. development guide/1. customization.stories.mdx
- packages/vue/src/stories/releases/v0.11.x/v0.11.0/v0.11.0.stories.mdx
Closes #
Fixing bugs when building projects, probably connected with postcss. 
Move negative values in every css `calc` function  to the first place e.g.
from:
```
margin: 0 calc(var(--spacer-sm)  *  -1);
```
to:
```
margin: 0 calc(-1 * var(--spacer-sm));
```
If applicable:
> fix: change calc functions to have negative value first

- packages/vue/src/components/atoms/SfButton/SfButton.stories.js
- packages/vue/src/components/atoms/SfButton/SfButton.vue
- packages/vue/src/stories/releases/v0.11.x/v0.11.2/v0.11.2.stories.mdx
> fix: attribute link not allowed on element button

- packages/vue/src/components/atoms/SfArrow/SfArrow.stories.js
- packages/vue/src/components/organisms/SfMegaMenu/SfMegaMenu.stories.js
- packages/vue/src/components/organisms/SfTabs/SfTabs.stories.js
- packages/vue/src/stories/releases/v0.11.x/v0.11.2/v0.11.2.stories.mdx
1. add changelog note for adding css vars docs. 
2. fix SfArrow, SfMegaMenu and SfTabs layout when switching to css custom properties tab.
If applicable:
> fix: SfArrow layout in storybook and add changelog note

- packages/vue/src/components/molecules/SfBanner/SfBanner.vue
Fix typo in SfBanner component.
If applicable:
> bug: typo in SfBanner component

- CONTRIBUTING.md
- packages/vue/src/stories/contributing-guide/1. contribute.stories.mdx
- packages/vue/src/stories/contributing-guide/2. github.stories.mdx
- packages/vue/src/stories/contributing-guide/9. issue-report.stories.mdx
- packages/vue/src/stories/releases/v0.11.x/v0.11.2/v0.11.2.stories.mdx
There is no related issue.
- fix all discord invitation links
- fix typos, grammar mistakes and links on _Become a Contributor_ page 
If applicable:
- What does `{" "} ` do?
- I don't think there is the main documentation under the docs folder. This statement may be wrong.
> vue - This is the main project that contains main Storefront UI Vue components code in src, storybook config in config, customized scripts in scripts and main documentation written in vuepress will be found in docs.
> fix: discord links, become a contributor page

- packages/vue/src/components/organisms/SfContentPages/SfContentPages.spec.js
- packages/vue/src/components/organisms/SfContentPages/SfContentPages.vue
- packages/vue/src/components/organisms/SfContentPages/_internal/SfContentPage.spec.js
- packages/vue/src/components/organisms/SfContentPages/_internal/SfContentPage.vue
- packages/vue/src/stories/releases/v0.11.x/v0.11.3/v0.11.3.stories.mdx
In our core repository we have a page component `MyAccount.vue`. We're using `SfContentPages` there to display content pages depending on the slug that comes after the `/my-account` part.
We can pass an unlimited number of content pages there. Which one should be displayed is determined by two things: 
- the `active` prop passed to the `SfContentPages` component
- the `title` prop passed to `SfContentPage` components passed as slots
```
<SfContentPages active="...">
<SfContentCategory title="Personal Details">
<SfContentPage title="...">
<MyProfile />
</SfContentPage>
</SfContentCategory>
</SfContentPages>
```
The problem is, the values of the `active` and `title` props might now always have a matching casing even if they're supposed to point to the same page. For example, in …
> refactor: detecting active page in SfContentPages regardless of the casing

- packages/shared/styles/components/atoms/SfButton.scss
- packages/vue/src/stories/releases/v0.11.x/v0.11.3/v0.11.3.stories.mdx
Closes #1715
- fixed issue with specificity
If applicable:
> fix: SfButton as link - full width is not working

- packages/vue/src/components/organisms/SfCollectedProduct/SfCollectedProduct.stories.js
- packages/vue/src/components/organisms/SfCollectedProduct/SfCollectedProduct.vue
- packages/vue/src/stories/releases/v0.11.x/v0.11.3/v0.11.3.stories.mdx
Closes #2111 
- added missing props
- updated docs
no visual change
If applicable:
> SfCollectedProduct - Add possibility to setup min and max qty

- packages/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.stories.js
- packages/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.vue
- packages/vue/src/stories/releases/v0.11.x/v0.11.3/v0.11.3.stories.mdx
Closes #2094
- added binding for cancelHandler
- added cancelLabel prop
no visual changes
If applicable:
> fix: SfComponentSelect - add cancelLabel prop and binding for cancel slot

- packages/nuxt/nuxt.config.js
- packages/nuxt/package.json
- packages/vue/src/stories/releases/v0.11.4/v0.11.4.stories.mdx
- yarn.lock
Closes #2097 
- added html validator for nuxt, that shows html errors in dev mode:
If applicable:
> feat: added html validator for nuxt

- packages/vue/src/components/molecules/SfSearchBar/SfSearchBar.vue
- packages/vue/src/stories/releases/v0.11.x/v0.11.4/v0.11.4.stories.mdx
> fix: type attribute added to SfButton in SfSearchBar

- packages/vue/src/components/organisms/SfTabs/SfTabs.vue
- packages/vue/src/stories/releases/v0.11.x/v0.11.3/v0.11.3.stories.mdx
- packages/vue/src/stories/releases/v0.12.x/v0.12.0/v0.12.0.stories.mdx
Closes #2152 
- removed mutating $children directly issue
-
If applicable:
> fix: SfTabs - adjusted tabs logic to avoid mutating readonly properties

- packages/shared/styles/components/organisms/SfTabs.scss
> hotfix: chevron in SfTabs on desktop

- packages/vue/src/stories/getting-started/2. development guide/1. customization.stories.mdx
- packages/vue/src/stories/getting-started/2. development guide/6. FAQ.stories.mdx
- packages/vue/src/stories/releases/v0.12.x/v0.12.0/v0.12.0.stories.mdx
Closes #2180 
Update docs to recommend using `:root` selector for overwriting global styles for Vue and Nuxt apps. Changes made in #1969 PR.
If applicable:
> chore: update docs to use root selector

- packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
- packages/vue/src/stories/releases/v0.12.x/v0.12.0/v0.12.0.stories.mdx
Closes #2184
Replaced template tag with a div and have a DOM element to be able to apply display: none
If applicable:
> fix: replace template tag with div SFProductCard

- packages/shared/styles/components/molecules/SfComponentSelect.scss
- packages/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.stories.js
- packages/vue/src/stories/releases/v0.12.x/v0.12.0/v0.12.0.stories.mdx
Closes #1306 
- added modifier for positioning SfComponentSelect label on the right
If applicable:
> feat: added new modifier for SfComponentSelect

- packages/vue/src/components/molecules/SfGallery/SfGallery.vue
- packages/vue/src/stories/releases/v0.12.x/v0.12.0/v0.12.0.stories.mdx
Closes #
When pushing new images to the gallery the glide functionality stops working. In my case the last images do not show when clicking its thumb. This fix will mount the glide again on `updated`.
On mounted
After adding a new image, the last image does not show anymore
After fix the image show when clicking the thumb
If applicable:
> fix(SfGallery): also mount glide on update

- packages/vue/.storybook/main.js
- packages/vue/src/stories/releases/v0.12.x/v0.12.1/v0.12.1.stories.mdx
Closes #2149 
Changed the order of addons in storybook main.js
After:
If applicable:
> feat: changed the order of css custom properties addon

- packages/vue/src/components/organisms/SfCollectedProduct/SfCollectedProduct.vue
- packages/vue/src/stories/releases/v0.12.x/v0.12.1/v0.12.1.stories.mdx
(https://github.com/vuestorefront/storefront-ui/issues/2239)
Closes #
`<template>` had a class set that used props, but since you can't set `<template>` classes, because of this the class did not work, I created a wrapper for the content, which I set the desired class.
If applicable:
> fix: class in <template> results in unexpected behavior #2239

- packages/vue/src/components/atoms/SfQuantitySelector/SfQuantitySelector.stories.js
- packages/vue/src/components/molecules/SfAddToCart/SfAddToCart.stories.js
- packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.stories.js
- packages/vue/src/components/molecules/SfCheckbox/SfCheckbox.stories.js
- packages/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.stories.js
- packages/vue/src/components/molecules/SfModal/SfModal.stories.js
- packages/vue/src/components/molecules/SfRadio/SfRadio.stories.js
- packages/vue/src/components/molecules/SfSteps/SfSteps.stories.js
- packages/vue/src/components/organisms/SfCollectedProduct/SfCollectedProduct.stories.js
- packages/vue/src/components/organisms/SfGroupedProduct/SfGroupedProduct.stories.js
- packages/vue/src/stories/releases/v0.12.x/v0.12.1/v0.12.1.stories.mdx
Closes #2148 
Added description for v-model in components where it used with custom props or events: 
- SfQuantitySelectos,
- SfAddressPicker
- SfAddToCart
- SfCheckbox
- SfComponentSelect
- SfModal
- SfRadio
- SfSteps
- SfCollectedProduct
- SfGroupedProduct.
If applicable:
> feat: add descriptions for v-model custom usage

- packages/vue/src/components/organisms/SfAccordion/SfAccordion.vue
Closes #2247 
Replaced `this.items.push(...this.$children)` with `this.items = this.$children`. This way we're not pushing new items to the array on every component update.
https://www.loom.com/share/4066dadc32684209afb10f324de27ac3
In the video you can see that the problem appears after I had toggled the checkbox. The SfAccordion's `updated` hook gets triggered even though the property managed with the checkbox is neither passed to SfAccordion as a prop nor related to it in any way.
Turns out it has to do with the SfAccordion **default** slot. When I replace it with a **named** slot, the SfAccordion is not updated on checkbox toggling.
> #2237 fix: sfaccordion stops toggling items correctly

- packages/shared/styles/components/organisms/SfGroupedProduct.scss
- packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx
Closes #2245 
Add styles for classes `.sf-grouped-product-item__quantity-selector`, `.sf-grouped-product.without-carousel .sf-grouped-product-item__quantity-selector`  for desktop view 
```
position: absolute;
bottom: var(--grouped-product-item-quantity-selector-bottom, var(--spacer-sm));
```
If applicable:
> #2245-fix: SfGroupedProduct mobile issue

- packages/vue/src/components/atoms/SfImage/SfImage.vue
- packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx
Closes #
Added default value of `img` for `image-tag` prop when SfImage is rendered on nuxt, to avoid passing empty string when this prop is not set. 
If applicable:
> fix: sfimage image-tag set to img on nuxt

- packages/vue/src/components/molecules/SfAddToCart/SfAddToCart.stories.js
- packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.stories.js
- packages/vue/src/components/molecules/SfCheckbox/SfCheckbox.stories.js
- packages/vue/src/components/molecules/SfColorPicker/SfColorPicker.stories.js
- packages/vue/src/components/molecules/SfDropdown/SfDropdown.stories.js
- packages/vue/src/components/molecules/SfPagination/SfPagination.stories.js
- packages/vue/src/components/organisms/SfContentPages/SfContentPages.stories.js
- packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx
Closes #2128 
Get rid of mutating prop directly issue in Storybook stories: 
- SfAddressPicker - selected
- SfAddToCart - qty
- SfColorPicker - isOpen
- SfDropdown - isOpen
- SfCheckbox - selected
- SfPagination - current
- SfContentPages - active
If applicable:
> fix: mutating props error in stories

- packages/nuxt/cypress.json
- packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx
Closes #2255
Randomly e2e tests fails for Home page because of SfHero component.
I've added timeout options to cypress config.
If applicable:
> fix:#2255-home-page-e2e-issue

- packages/nuxt-module/lib/module.js
- packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx
Closes #2126
This PR resolve bug  with `$ is not a function error`. Bug happens after installing ui nuxt module.
According to author of `core-js`, library shouldn't be transpiled by babel -  https://github.com/zloirock/core-js/issues/912
I've excluded  from transpiling process: 
- `/\bcore-js\b/` - core js module
- `/\bwebpack\/buildin\b/` - fix potential bug related with older versions of `core-js`.
More info about problem - https://github.com/zloirock/core-js/issues/743
If applicable:
> fix: core.js causes $ is not a function error

- packages/vue/src/components/molecules/SfReview/SfReview.stories.js
- packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx
Closes #1623 
Changed the date prop format to text to display the value that is actually passed. Users need to implement the proper date format by themselves and pass the result into the component. 
If applicable:
> fix: changed date prop format to text in SfReview story

- packages/shared/styles/components/molecules/SfModal.scss
- packages/vue/src/components/molecules/SfModal/SfModal.stories.js
- packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx
Closes #1880
New CSS var `--modal-content-height` for `SfModal` is added. Default value is `100%`. It allows setting height of SfModal content.
I have tested this solution responsively and in different browsers like: `Chrome`, `Safari`, `Firefox`. It seems that this feature works properly.
If applicable:
> feat: allow setting height for SfModal content

- packages/vue/src/components/atoms/SfInput/SfInput.vue
- packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx
https://github.com/vuestorefront/storefront-ui/issues/2262
Closes #
The component `SfInput` had attributes that, when entering a value with a _whitespace_, led to an error, I replaced the value with a `computed`, which removes _whitespace_.
If applicable:
> #2262 - fix:'SfInput' attribute has invalid input in some cases

- packages/vue/src/components/atoms/SfImage/SfImage.vue
- packages/vue/src/stories/releases/v0.12.x/v0.12.2/v0.12.2.stories.mdx
Closes #2277 
`Width` and `height` props passed to attributes to be added when `nuxt-img` is used.  
If applicable:
> fix: adding width and height when nuxt-img is used

- packages/shared/styles/components/molecules/SfColorPicker.scss
- packages/vue/src/stories/releases/v0.12.x/v0.12.3/v0.12.3.stories.mdx
Closes #2258 
- Changed the --color-picker-align-items to start
If applicable:
> fix: the align-items property to start to make all the colors visible

- package.json
- packages/vue/src/components/molecules/SfGallery/SfGallery.vue
- packages/vue/src/stories/releases/v0.12.x/v0.12.3/v0.12.3.stories.mdx
- yarn.lock
Fixes no `alt` and `src` props error appearing on product page entered after refreshing category page. 
Added empty url prop in pictureSelected. 
If applicable:
> fix: add url property to big image in pictureSelected

- packages/vue/src/components/organisms/SfAccordion/SfAccordion.vue
Currently the accordion closes all headers when updating and multiple attribute is passed.
The issue is https://github.com/vuestorefront/storefront-ui/blob/develop/packages/vue/src/components/organisms/SfAccordion/SfAccordion.vue#L88 is the only place openHeader is set which is inside a check for !internalMultiple. https://github.com/vuestorefront/storefront-ui/blob/develop/packages/vue/src/components/organisms/SfAccordion/SfAccordion.vue#L76 is called each time the component updates which resets all isOpen properties to those specified in the openHeader.
Below is a simple reproduction of the issue
```
<template>
<SfAccordion :multiple="true">
<SfAccordionItem
key="color"
header="Color"
>
<SfFilter
key="red"
label="Red"
:selected="red"
@change="red = !red"
/>
<SfFilter
key="green" …
```
> fix: accordion closing headers when multiple is used

- .github/workflows/on-push-pull-tests.yml
- packages/vue/src/stories/releases/v0.12.x/v0.12.4/v0.12.4.stories.mdx
Closes #2319 
Change gh action workflow to run tests only on push/pull request to master or develop branches.
If applicable:
> feat: change gh action workflow

- packages/shared/styles/components/organisms/SfFooter.scss
- packages/vue/src/components/organisms/SfFooter/SfFooter.vue
- packages/vue/src/components/organisms/SfFooter/_internal/SfFooterColumn.vue
- packages/vue/src/stories/releases/v0.12.x/v0.12.3/v0.12.3.stories.mdx
- packages/vue/src/stories/releases/v0.12.x/v0.12.4/v0.12.4.stories.mdx
Closes #2315 
- removed isMobile from SfFooter
- adjusted css classes and html template
no visual changes
If applicable:
> chore: remove isMobile from SfFooter

- packages/vue/src/components/organisms/SfHero/_internal/SfHeroItem.vue
- packages/vue/src/stories/releases/v0.12.x/v0.12.4/v0.12.4.stories.mdx
Closes #2327 
Fixed passing images as objects in the SfHero component.  
If applicable:
> fix: sfhero image passed as objects

- packages/vue/src/components/organisms/SfSidebar/SfSidebar.stories.js
- packages/vue/src/components/organisms/SfSidebar/SfSidebar.vue
- packages/vue/src/stories/releases/v0.12.x/v0.12.4/v0.12.4.stories.mdx
Closes [En511](https://vsf.atlassian.net/browse/EN-511)
This PR resolve bug  with lazy loaded SfSidebar animation.
New props `position` is added. Default value is `left`.
**Usage examples:**
-  for `Sidebar`, where animation is appeared from `right` side
```
<SfSidebar
class="sf-sidebar--right"
position="right"
/>
```
**How to test on CT:**
- for `CartSidebar` add `setTimeout` inside `toggleCartSidebar` method - file `useUiState`. `setTimeout` allows handling `out` animation in proper way
```
setTimeout(() => {
state.isCartSidebarOpen = !state.isCartSidebarOpen;
},300)
```
If applicable:
> fix(SfSidebar): fixed lazy loaded animation

- packages/vue/src/components/atoms/SfButton/SfButton.stories.js
- packages/vue/src/stories/releases/v0.13.x/v0.13.1/v0.13.1.stories.mdx
Closes #2357 
Replaced onClick with click method
If applicable:
> fix: the issue of onClick not defined in button

- packages/shared/styles/components/molecules/SfCallToAction.scss
- packages/vue/src/stories/releases/v0.13.x/v0.13.1/v0.13.1.stories.mdx
> fix: SfCallToAction show desktop images in background

- packages/shared/styles/components/organisms/SfHero.scss
- packages/vue/src/components/organisms/SfHero/_internal/SfHeroItem.vue
- packages/vue/src/stories/releases/v0.13.x/v0.13.1/v0.13.1.stories.mdx
Closes #2365 
Fixed passing mobile image to SfHero. 
If applicable:
> #SFUI-123 fix: change style and HeroItem to show mobile images

- packages/shared/styles/components/molecules/SfGallery.scss
- packages/vue/src/components/molecules/SfGallery/SfGallery.stories.js
- packages/vue/src/stories/releases/v0.13.x/v0.13.1/v0.13.1.stories.mdx
Closes #2381 
Changed outside zoom in SfGallery to be in limited size and positioned outside main image (not to overwrite it). 
Also changes time for autoplay option in SfGallery stories to change every 3s. 
If applicable:
> 130 fix: SfGallery outside zoom image size and position

- packages/vue/src/components/molecules/SfCheckbox/SfCheckbox.stories.js
- packages/vue/src/stories/releases/v0.13.x/v0.13.2/v0.13.2.stories.mdx
Closes #2379 
Changed size of checkbox in the stories.
If applicable:
> fix: SfCheckbox size adjusted to the content

- packages/vue/src/components/molecules/SfRadio/SfRadio.stories.js
- packages/vue/src/stories/releases/v0.13.x/v0.13.2/v0.13.2.stories.mdx
Closes #2384
I removed `required` prop from story, because `required` functionality for `SfRadio` is not applied. 
If applicable:
> fix: SfRadio - remove required prop from storybook

- packages/vue/scripts/update-components-docs.js
EDIT: See regex example here https://regex101.com/r/rPY7mx/4
Before this change the following in f.ex `packages/shared/styles/components/atoms/SfArrow.scss`:
```scss
&__icon {
width: calc(2rem * var(--arrow-width-multiplier));
transform: var(--arrow-icon-transform);
}
```
Would result in:
```js
[
[
[ '--arrow-justify-content', '' ],
[ '--arrow-width-multiplier)', '' ],
[ '--arrow-icon-transform', '' ]
],
[
[ '--button-width', '' ],
[ '--button-height', '' ],
[ '--button-padding', '0 0.625rem' ],
[ '--button-background', '' ],
[ '--button-transition', '' ],
[ '--icon-color', '' ],
[ '--button-box-shadow', '' ],
[ '--box-shadow-transition-opacity-duration', '150ms' ],
[ '--button-box-shadow-opacity', '0.25' ],
[ '--button-border-radius', '' ]
]
]
```
When the `yarn run …
> fix: update-components-docs regex

- packages/vue/src/components/molecules/SfSearchBar/SfSearchBar.stories.js
- packages/vue/src/stories/releases/v0.13.x/v0.13.1/v0.13.1.stories.mdx
- packages/vue/src/stories/releases/v0.13.x/v0.13.2/v0.13.2.stories.mdx
Closes #2376 
Changed `click` event name to proper one in the story. 
If applicable:
> fix: SfSearchbar change event name in story

- packages/vue/src/components/organisms/SfStoreLocator/SfStoreLocator.vue
- packages/vue/src/stories/releases/v0.13.x/v0.13.2/v0.13.2.stories.mdx
Closes #2393 
Added script to fix issue with lacking marker icons in SfStoreLocator. Based on solution in VueLeafLet docs:
https://vue2-leaflet.netlify.app/quickstart/#marker-icons-are-missing 
Hard to say if it works properly cause this error doesn't appear locally. 
If applicable:
> fix: SfStorelocator add marker icons

- packages/vue/src/components/atoms/SfTextarea/SfTextarea.stories.js
- packages/vue/src/components/atoms/SfTextarea/SfTextarea.vue
- packages/vue/src/stories/releases/v0.13.x/v0.13.3/v0.13.3.stories.mdx
Closes #2436 
SfTextarea pass readonly prop in component and add to story.
If applicable:
> fix: SfTextarea readonly prop

- packages/shared/styles/components/organisms/SfFooter.scss
- packages/vue/src/components/organisms/SfFooter/SfFooter.stories.js
- packages/vue/src/components/organisms/SfFooter/SfFooter.vue
- packages/vue/src/components/organisms/SfFooter/_internal/SfFooterColumn.vue
- packages/vue/src/stories/releases/v0.13.x/v0.13.4/v0.13.4.stories.mdx
Closes #2465 
Changed passing `open` prop and styles on mobile to allow closing columns depending on the prop value.
If applicable:
> fix: footer closing on mobile

- packages/shared/styles/components/molecules/SfGallery.scss
- packages/vue/src/stories/releases/v0.13.x/v0.13.4/v0.13.4.stories.mdx
> fix: SfGallery - for more than 4 thumbnails gallery is breaking

- packages/vue/src/components/molecules/SfDropdown/SfDropdown.stories.js
- packages/vue/src/stories/releases/v0.13.x/v0.13.4/v0.13.4.stories.mdx
Closes #2464 
Fix storybook docs Dropdown iframe issue. When settings changed to `inline: false` props in docs are not reactive. After toggling to `true` the layout is broken so there is need to add some extra styling.
If applicable:
> fix: Dropdown docs interactivity

- packages/vue/src/components/atoms/SfBullets/SfBullets.vue
- packages/vue/src/components/atoms/SfImage/SfImage.vue
- packages/vue/src/stories/releases/v0.13.x/v0.13.4/v0.13.4.stories.mdx
> fix: SfBullets and SfImage warnings instead of errors

- packages/vue/src/components/molecules/SfModal/SfModal.stories.js
- packages/vue/src/stories/releases/v0.13.x/v0.13.4/v0.13.4.stories.mdx
> fix: Storybook Molecules Modal cannot close the modal even with persistent turned off

- packages/vue/src/components/atoms/SfInput/SfInput.stories.js
- packages/vue/src/stories/releases/v0.13.x/v0.13.4/v0.13.4.stories.mdx
> fix: Storybook Atoms Input placeholder prop does not work

- packages/nuxt/package.json
- packages/vue/src/stories/releases/v0.13.x/v0.13.3/v0.13.3.stories.mdx
> fix: Vue project no longer compiles with npm

- packages/vue/src/components/organisms/SfStoreLocator/SfStoreLocator.vue
Importing leaflet will cause `window is not defined` error on SSR.
Move https://github.com/vuestorefront/storefront-ui/pull/2428 fix on mounted lifecycle.
https://github.com/vuestorefront/storefront-ui/pull/2428
https://github.com/vuestorefront/storefront-ui/issues/2499
> Fix Leaflet SSR bug

- apps/docs/components/.vuepress/config.js
- renames `Docs` to `Base Components` in the navbar
If applicable:
> docs: navbar renaming

- apps/docs/components/.vuepress/config.js
- apps/docs/components/.vuepress/theme/layouts/HomeLayout.vue
- apps/docs/components/.vuepress/theme/styles/index.styl
- apps/docs/components/index.md
- apps/docs/components/utils/utils.js
- add github star call to action on the home page
- fix `Edit this page` link for blocks/hooks
If applicable:
> docs: github updates

- apps/docs/components/react/getting-started.md
- apps/docs/components/vue/getting-started.md
Closes #
- adds link to the Stackblitz playground for Vue/React to the corresponding introduction page
If applicable:
> docs: add playground link

- packages/sfui/frameworks/react/components/SfInput/SfInput.tsx
- packages/sfui/frameworks/react/components/SfRadio/SfRadio.tsx
- packages/sfui/frameworks/vue/components/SfInput/SfInput.vue
- packages/sfui/frameworks/vue/components/SfRadio/SfRadio.vue
Closes https://vsf.atlassian.net/browse/SFUI2-902
add width due to radio overflowing in firefox
Now it works:
> fix: radio styling in firefox [SFUI2-902]

- apps/docs/components/react/getting-started.md
We need additional transpilation step for next.js to work
> chore: refine next.js getting-started guide

- apps/preview/next/pages/showcases/ProductCard/Details.tsx
- apps/preview/next/pages/showcases/ProductCard/ProductCardHorizontal.tsx
- apps/preview/next/pages/showcases/QuantitySelector/OutOfStock.tsx
- apps/preview/next/pages/showcases/QuantitySelector/QuantitySelector.tsx
- apps/preview/next/pages/showcases/QuantitySelector/Rounded.tsx
- apps/preview/nuxt/pages/showcases/ProductCard/Details.vue
- apps/preview/nuxt/pages/showcases/ProductCard/ProductCardHorizontal.vue
- apps/preview/nuxt/pages/showcases/QuantitySelector/OutOfStock.vue
- apps/preview/nuxt/pages/showcases/QuantitySelector/QuantitySelector.vue
- apps/preview/nuxt/pages/showcases/QuantitySelector/Rounded.vue
Closes https://vsf.atlassian.net/browse/SFUI2-902
Fix quantity selector in firefox
Before:
After:
> fix: quantitySelector in firefox [SFUI2-902]

- apps/docs/components/.vuepress/config.js
- apps/docs/components/package.json
- yarn.lock
Currently, the "Getting Started" at the top navigation (which should link to the VSF core docs) does not resolve properly. 
- Fixed upstream in the theme and updated config
built app + the link now directs to the proper url
> docs: fix top navigation

- apps/docs/components/.vuepress/config.js
- apps/docs/components/package.json
- yarn.lock
After the main website rework (vuestorefront.io) - some of the links that were previously in the docs footer now 404. Just found this out with the SFUI release because of the number of new developers exploring the docs site. 
- updated links in shared theme
> docs: update footer links via vuepress theme

- apps/docs/components/components/tooltip.md
- apps/preview/next/pages/showcases/Tooltip/BasicTooltip.tsx
- apps/preview/nuxt/pages/showcases/Tooltip/BasicTooltip.vue
Currently, `SfTooltip` does not have a copy and paste example of usage.
- converts the `SfTooltip` playground into a minimal copy and paste example for Next/Nuxt
If applicable:
> docs: add basic tooltip example

- README.md
- apps/docs/components/.vuepress/config.js
- packages/sfui/typography/README.md
The current Figma link goes directly to the `Rating` component, we want this to be the home page instead.
Closes #
- changes link
> docs: update figma link

- packages/sfui/frameworks/vue/composables/useDisclosure/useDisclosure.ts
Closes[ #903](https://vsf.atlassian.net/browse/SFUI2-903)
Passed `initialValue`  to `isOpen` property in `useDisclosure` Vue composable. 
Now when changing to `useDisclosure({ initialValue: true });`  in the Modal component it is opened by default.
> fix: (sfui2-903) initialvalue in useDisclosure composable 

- apps/preview/next/package.json
- apps/preview/vue/package.json
- yarn.lock
Closes #
Right now with new cypress version, we can update vue-preview cypress into 12.9.0. Previous ^12 version affect speed headless tests
> chore(deps): unify and update cypress version to 12.9

- apps/docs/components/react/getting-started.md
With the Next.js `/app` directory, Storefront UI components need to be used inside Client Components. This should be called out in our docs. 
- adds callout in Next.js getting started guide regarding the `"use client"` directive
> docs: add app directory callout for next.js docs

- packages/sfui/frameworks/react/components/SfLink/SfLink.tsx
- packages/sfui/frameworks/vue/components/SfLink/SfLink.vue
https://vsf.atlassian.net/browse/SFUI2-972?atlOrigin=eyJpIjoiNjQ4ZTkyY2NiOGE2NDc1OGI2ZmEzNWZiZjc0MjYyYWIiLCJwIjoiaiJ9
- removed styling for visited state
> chore: adjusted visited styling

- .github/CODEOWNERS
Closes #
The purpose of this change is to increase security and reduce the amount of code owners to prevent unsafe code injection. 
More you can find here: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-codeowners-to-monitor-changes
> chore: changing code owners

- apps/docs/components/react/getting-started.md
- apps/docs/components/vue/getting-started.md
Getting Started Videos were recently published, so we can add them to the relevant docs!
Closes #
- adds getting started to next/nuxt getting started guides
> docs: add videos to getting started guides

- packages/sfui/frameworks/vue/components/SfDropdown/SfDropdown.vue
- packages/sfui/frameworks/vue/components/SfTooltip/SfTooltip.vue
https://vsf.atlassian.net/browse/SFUI2-973?atlOrigin=eyJpIjoiOTUwZmI4ZjU3YThjNGM3NzhkZjYxNzI2ZTQ1NTMyNGMiLCJwIjoiaiJ9
- added unions in Dropdown and Tooltip
-
> fix: unions for enums in dropdown and tooltip components

- renovate.json
Closes #
Renovate keep updating `swc` plugin but we can't use it since its buggy, 0.0.14 -> 0.0.15 because of https://github.com/kwonoj/swc-plugin-coverage-instrument/issues/200
blocking: https://github.com/vuestorefront/storefront-ui/pull/2582
> chore: disable renovate to update swc-plugin-coverage-instrument

- apps/preview/next/pages/examples/SfLink.tsx
- apps/preview/next/pages/showcases/Link/LinkVariants.tsx
- apps/preview/next/pages/showcases/Link/NextLink.tsx
- apps/preview/nuxt/pages/examples/SfLink.vue
- apps/preview/nuxt/pages/showcases/Link/NuxtLink.vue
- packages/sfui/frameworks/react/components/SfLink/SfLink.tsx
Closes [SFUI2-928](https://vsf.atlassian.net/browse/SFUI2-928)
Fixed SfLink examples mostly by setting neutral `href="#"` that does not redirect to other page.
[SFUI2-928]: https://vsf.atlassian.net/browse/SFUI2-928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: link examples

- apps/docs/components/blocks/Alert.md
- apps/docs/components/blocks/Banners.md
- apps/docs/components/blocks/Breadcrumbs.md
- apps/docs/components/blocks/Card.md
- apps/docs/components/blocks/Checkout.md
- apps/docs/components/blocks/Filters.md
- apps/docs/components/blocks/Footer.md
- apps/docs/components/blocks/NavbarBottom.md
- apps/docs/components/blocks/NavbarTop.md
- apps/docs/components/blocks/OrderSummary.md
- apps/docs/components/blocks/Pagination.md
- apps/docs/components/blocks/ProductCard.md
- apps/docs/components/blocks/QuantitySelector.md
- apps/docs/components/blocks/Review.md
- apps/docs/components/react/blocks.md
- apps/docs/components/vue/blocks.md
https://vsf.atlassian.net/browse/SFUI2-968
When reviewing ways to better show our blocks at different sizes, I saw that we need to show these at larger widths by default. So I added the `hideToc` option on all the blocks pages. 
- also fixed the height of the Colors Filter block.
> docs: remove table of contents from blocks

- .github/workflows/ci.yml
Closes [SFUI2-1020](https://vsf.atlassian.net/browse/SFUI2-1020)
Collaborator verification job added. When contributor is not a collaborator then skip SonarCloud step.
[SFUI2-1020]: https://vsf.atlassian.net/browse/SFUI2-1020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: run SonarCloud pipeline only for collaborators

- apps/docs/components/blocks/NewsletterBox.md
- apps/docs/components/utils/future-blocks.json
- apps/preview/next/pages/showcases/NewsletterBox/NewsletterBox.tsx
- apps/preview/nuxt/pages/showcases/NewsletterBox/NewsletterBox.vue
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/69?modal=detail&selectedIssue=SFUI2-664
NewsletterBox block
In task there's a note that this should be in Banners but as this description was made before and there was already a separate place for NewsletterBox with thumbnail then it was put to this block
Two alerts are added separately (for demo purposes) as we can't do a component and there might be a case where we can see both of them (one after another)
> feat: newsletterbox block

- apps/preview/next/pages/showcases/ProductCard/ProductCardHorizontal.tsx
- apps/preview/next/pages/showcases/ProductCard/ProductCardVertical.tsx
Closes #2573 
I implemented `img` instead of `Image` from `next/image` on `ProductCardHorizontal` and `ProductCardVertical`.
> fix: product card image blocks

- packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx
- packages/sfui/frameworks/vue/components/SfSelect/SfSelect.vue
Closes #2569 
Chevron will rotate when select is focused.
So, I implemented `chevronRotated` as a ref variable to handle `rotate-180`.
Then, I add `onClickOutside` to handle `chevronRotated`. When clicking outside of select, the chevron should rotate back.
https://user-images.githubusercontent.com/6861191/230060193-45fd4c9e-fbc2-4115-9142-fd180f16d1cc.mov
This problem occurs for React too. Should I update to `SfSelect.tsx` for this PR?
> fix: sfselect chevron rotate

- apps/preview/next/pages/showcases/MegaMenu/BaseMegaMenu.tsx
- apps/preview/nuxt/pages/showcases/MegaMenu/BaseMegaMenu.vue
https://vsf.atlassian.net/browse/SFUI2-1033?atlOrigin=eyJpIjoiNmVhODZjNmJjNjhmNDdhNmI0YzkwMDE3NzQ4ZjhjMWEiLCJwIjoiaiJ9
- added flex-nowrap classes for icons container
> fix: styling improvement for wrapping icons in megamenu

- apps/preview/next/pages/showcases/MegaMenu/BaseMegaMenu.tsx
- apps/preview/nuxt/pages/showcases/MegaMenu/BaseMegaMenu.vue
- packages/sfui/frameworks/react/hooks/useTrapFocus/useTrapFocus.ts
- packages/sfui/frameworks/vue/composables/useTrapFocus/useTrapFocus.ts
https://vsf.atlassian.net/browse/SFUI2-1027?atlOrigin=eyJpIjoiMTE1ZGVlZjYxYzE5NGI1MGIzY2Q3YmRlOGRmOWIyYWMiLCJwIjoiaiJ9
https://vsf.atlassian.net/browse/SFUI2-689
- added arrows navigation for megamenu using useTrapFocus composable
-
> feat: (sfui2-1027) added arrows support for navigating mega menu

- README.md
- apps/docs/components/.vuepress/config.js
- packages/sfui/typography/README.md
Updates all instances of the Figma Link to the latest designs: https://www.figma.com/file/7pRNATsiFwYmveafXzjhSV/SFUI-2-%7C-Design-Kit-(public)
Closes #
> docs: update figma link for 2.1 release

- apps/preview/next/pages/showcases/NewsletterBox/NewsletterBox.tsx
- apps/preview/nuxt/pages/showcases/NewsletterBox/NewsletterBox.vue
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/69?modal=detail&selectedIssue=SFUI2-1035&assignee=5fcf86fca1d3f100684db8a5
Links color changed to gray and added href prop
> fix: newsletterbox links color

- apps/docs/components/components/scrollable.md
- apps/preview/next/package.json
- apps/preview/next/pages/showcases/Scrollable/ScrollByOneItem.tsx
- packages/sfui/frameworks/react/components/SfButton/SfButton.tsx
- packages/sfui/frameworks/react/components/SfDrawer/SfDrawer.tsx
- packages/sfui/frameworks/react/components/SfModal/SfModal.tsx
- packages/sfui/frameworks/react/components/SfScrollable/SfScrollable.tsx
- packages/sfui/frameworks/react/components/SfScrollable/types.ts
- packages/sfui/frameworks/react/hooks/useScrollable/useScrollable.ts
- packages/sfui/frameworks/react/hooks/useTooltip/useTooltip.ts
- packages/sfui/frameworks/react/package.json
- packages/sfui/frameworks/react/shared/utils/props.ts
- yarn.lock
Closes [SFUI2-1024](https://vsf.atlassian.net/browse/SFUI2-1024)
- Fixed typing of `createPropsGetter` function.
- Refactored `<SfScrollable />` component.
- Changed name of the prop: `wrapperClassNames` -> `wrapperClassName`
- Switched to [`react-merge-refs`](https://www.npmjs.com/package/react-merge-refs) due to issue on Next build with previous package `merge-refs`.
**Important!** Please note that when you use props getter, you must always pass all additional props through function's argument. Passing custom props outside of the props getter may cause issues, due to unexpected props overriding or incorrect props merging.
```
// Correct usage example
// onClick props will get merged
<SfButton {...getNextButtonProps({
variant: 'secondary',
size: 'lg',
onClick: () => console.log('click'), …
```
> fix: props getters in Scrollable

- apps/preview/next/pages/showcases/Pagination/Pagination.tsx
- apps/preview/nuxt/pages/showcases/Pagination/Pagination.vue
https://vsf.atlassian.net/browse/SFUI2-1044?atlOrigin=eyJpIjoiZTBiODM2YTVhZDg5NGYyYzhlYWQ4ZTFhZjcxYjlhMTciLCJwIjoiaiJ9
- adjusted flex properties of pagination
- changed border color to primary-700
- added missig size prop for button
> fix: (sfui2-1044) pagination styling improvements

- packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx
- packages/sfui/frameworks/vue/components/SfSelect/SfSelect.vue
Closes #2603
Add `disabled`,`selected` and `hidden` attributes to the placeholder option to hide from the selection.
https://user-images.githubusercontent.com/6861191/233136222-e1f9cb6c-648b-4cde-bec5-b1a8c37aa53f.mov
> fix: sfselect placeholder hidden

- packages/sfui/frameworks/react/components/SfListItem/SfListItem.tsx
- packages/sfui/frameworks/vue/components/SfListItem/SfListItem.vue
Closes [SFUI2-1053](https://vsf.atlassian.net/browse/SFUI2-1053)
Changes applied to SfListItem component:
- add missing focus ring on focus visible,
- remove `tabindex`,
- make focus ring position over another list item with hover (see screenshot).
SfListItem component interactivity depends on the context. General focus ring is a part of the component but it is enabled only when the component is used as an interactive element like `<a>`, e.g. `<SfListItem as="a">` in React, or `<SfListItem tag="a">` in Vue. By default SfListItem renders as `<li>` element, which is non-interactive, so focus ring won't be applied.
[SFUI2-1053]: https://vsf.atlassian.net/browse/SFUI2-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add missing focus visible to list item

- apps/preview/next/pages/showcases/MegaMenu/BaseMegaMenu.tsx
- apps/preview/nuxt/pages/showcases/MegaMenu/BaseMegaMenu.vue
- packages/sfui/frameworks/vue/components/SfListItem/SfListItem.vue
https://vsf.atlassian.net/browse/SFUI2-1027?atlOrigin=eyJpIjoiZDIxZTNjYjZmZDhkNDEzMzg5ZjNjOGRjMjlmNGIyYTUiLCJwIjoiaiJ9
- fixed issue with double-focus outline on megamenu items in vue
-
> fix: (sfui2-1027) megamenu focus outline improvements

- .github/workflows/ci.yml
change version of sonarcloud action that we use to working `1.8` as the latest version is broken
references https://github.com/SonarSource/sonar-scanner-cli-docker/issues/175
> fix: sonarcloud action

- apps/docs/components/blocks/Search.md
- apps/preview/next/pages/showcases/Search/AutocompleteSearch.tsx
- apps/preview/next/pages/showcases/Search/SearchBasic.tsx
- apps/preview/nuxt/pages/showcases/Search/SearchBasic.vue
- packages/sfui/frameworks/vue/components/SfInput/SfInput.vue
Closes [SFUI2-669](https://vsf.atlassian.net/browse/SFUI2-669)
- Adds Search block. First simple example with autocomplete.
- Small fixes in Input Vue component: remove focus event emit, adjust `??` operator to catch empty string as a value.
[SFUI2-669]: https://vsf.atlassian.net/browse/SFUI2-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: search block

- apps/preview/next/pages/showcases/Search/SearchBasic.tsx
- apps/preview/nuxt/pages/showcases/Search/SearchBasic.vue
Closes [SFUI2-669](https://vsf.atlassian.net/browse/SFUI2-669)
- fix of reset button behaviour
[SFUI2-669]: https://vsf.atlassian.net/browse/SFUI2-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: search block show reset button only when value

- .github/workflows/ci.yml
- apps/docs/components/package.json
- package.json
- turbo.json
Closes #
Just because we have slow built step on CI jobs (around 10 minutes) IMHO its good idea to split whatever we can and run it in parallel, building docs can be splitted like that. With this simple change time is cut from 10 minutes to 6 minutes
> ci: split docs from building step

- apps/preview/nuxt/pages/showcases/Switch/SwitchWithoutLabel.vue
https://vsf.atlassian.net/browse/SFUI2-1072?atlOrigin=eyJpIjoiMjA0NzIwMzcwNjEwNGUzNjk1ODk3MTUxZTYwOTc1OWEiLCJwIjoiaiJ9
- unified initial Switch state for vue and react
-
> fix: unified examples for switch component

- apps/docs/components/blocks/MegaMenu.md
- apps/docs/components/blocks/NewsletterBox.md
- apps/preview/next/pages/showcases/MegaMenu/BaseMegaMenu.tsx
- apps/preview/next/pages/showcases/MegaMenu/MegaMenuNavigation.tsx
- apps/preview/nuxt/pages/showcases/MegaMenu/BaseMegaMenu.vue
- apps/preview/nuxt/pages/showcases/MegaMenu/MegaMenuNavigation.vue
Closes
- [SFUI2-1105](https://vsf.atlassian.net/browse/SFUI2-1105)
- [SFUI2-1106](https://vsf.atlassian.net/browse/SFUI2-1106)
- [SFUI2-1107](https://vsf.atlassian.net/browse/SFUI2-1107)
- [SFUI2-1108](https://vsf.atlassian.net/browse/SFUI2-1108)
- Hide ToC in Mega Menu and Newsletter pages in the docs.
- Fix font weight of the title/back button in nested navigation mega menu on mobile devices.
- Fix size of the logo in base mega menu example.
- Fix styles (mostly colors) of the buttons in extended navigation bar.
[SFUI2-1105]: https://vsf.atlassian.net/browse/SFUI2-1105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SFUI2-1106]: https://vsf.atlassian.net/browse/SFUI2-1106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
> fix: mega menu improvements

- apps/preview/next/pages/showcases/MegaMenu/MegaMenuNavigation.tsx
- apps/preview/nuxt/pages/showcases/MegaMenu/MegaMenuNavigation.vue
Closes [SFUI2-1105](https://vsf.atlassian.net/browse/SFUI2-1105)
Overrides default button hover color.
[SFUI2-1105]: https://vsf.atlassian.net/browse/SFUI2-1105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: mega menu category button color

- packages/sfui/frameworks/vue/components/SfScrollable/SfScrollable.vue
- packages/sfui/shared/scrollable/scrollable.ts
Closes[ #1113](https://vsf.atlassian.net/browse/SFUI2-1113)
- fixed buttons in GalleryHorizontal on Vue. Changed condition in SfScrollable in order to show buttons passed in slots when `floating` position is set. 
- replaced `onResize` method with `resizeObserver` to intercept when SfScrollable element changes its size and refresh it
> fix: gallery horizontal buttons on vue and resize observer in sfscrollable

- apps/docs/components/components/scrollable.md
- apps/preview/next/pages/showcases/Gallery/GalleryVertical.tsx
- apps/preview/next/pages/showcases/Gallery/GalleryWithBullets.tsx
- apps/preview/next/pages/showcases/Scrollable/ScrollByOneItem.tsx
- apps/preview/nuxt/pages/showcases/Scrollable/ScrollByOneItem.vue
- packages/sfui/frameworks/react/components/SfScrollable/SfScrollable.tsx
- packages/sfui/frameworks/react/components/SfScrollable/types.ts
- packages/sfui/frameworks/react/hooks/useScrollable/useScrollable.ts
- packages/sfui/frameworks/vue/components/SfScrollable/SfScrollable.vue
Closes [#1112](https://vsf.atlassian.net/browse/SFUI2-1112)
- In Vue prop name was corrected, changed to `prevDisabled` in order to keep consistency with other props like `onPrev` (not using entire "previous" word)
- in React disabled props have to take priority over default behavior in order to disable buttons correctly - condition for that was changed in useScrollable hook
> fix: scrollable by one item in vue and react

- apps/preview/next/layouts/Showcases.tsx
- apps/preview/nuxt/pages/showcases.vue
- packages/config/example-style/index.scss
https://vsf.atlassian.net/browse/SFUI2-1122
- search inputwith saving in url query
- all showcase items are hidden by default
- existing showcase opened that is in url
[baf07192-a3f8-430e-aadc-34e653507311.webm](https://github.com/vuestorefront/storefront-ui/assets/2566152/45763d3f-5d3b-413d-b7be-e929360e6e1e)
> chore: add search and url filter for showcases [SFUI2-1122]

- .vuestorefrontcloud/router/docker/default.conf
- README.md
- apps/docs/components/.vuepress/config.js
- packages/sfui/typography/README.md
Closes #
https://vsf.atlassian.net/browse/SFUI2-1144
- adds redirect for figma link
- changes instances of the Figma URL to `https://docs.storefrontui.io/v2/figma`
> docs: add redirect for friendly figma link

- packages/sfui/frameworks/vue/components/SfCheckbox/SfCheckbox.vue
Closes # https://vsf.atlassian.net/browse/SFUI2-1071
Checkbox doesn't have background image when invalid and indeterminate states are enabled
> fix: checkbox invalid state with indeterminate

- apps/preview/next/pages/showcases/Gallery/GalleryVertical.tsx
- apps/preview/nuxt/pages/showcases/Gallery/GalleryVertical.vue
https://vsf.atlassian.net/browse/SFUI2-1126
screen width 320:
screen width 800:
screen width 1492:
> fix: gallery vertical [SFUI2-1126]

- apps/preview/next/pages/showcases/Gallery/GalleryHorizontal.tsx
- apps/preview/nuxt/pages/showcases/Gallery/GalleryHorizontal.vue
https://vsf.atlassian.net/browse/SFUI2-1126
320:
800:
1440:
> fix: gallery horizontal [SFUI2-1126]

- apps/docs/components/.vuepress/components/Generate.vue
- apps/docs/components/.vuepress/components/Showcase.vue
- apps/docs/components/blocks/Footer.md
- apps/docs/components/blocks/MegaMenu.md
- apps/docs/components/blocks/NavbarBottom.md
- apps/docs/components/blocks/NavbarTop.md
- apps/preview/next/layouts/Showcases.tsx
- apps/preview/nuxt/pages/showcases.vue
- apps/preview/nuxt/pages/showcases/Link/NuxtLink.vue
- packages/config/example-style/index.scss
https://vsf.atlassian.net/browse/SFUI2-1136
- add possibility to have showcase without paddings
- fix/improve no sidebar in showcases when run in docs, previously in react there was quick jump from visible sidenav to hidden after initial load
> docs: add no-paddings feature, improve no sidebar in showcases [SFUI2-1136]

- apps/docs/components/blocks/Breadcrumbs.md
- apps/preview/next/pages/showcases/Breadcrumbs/Breadcrumbs.tsx
- apps/preview/next/pages/showcases/Breadcrumbs/BreadcrumbsSeparator.tsx
- apps/preview/next/pages/showcases/Breadcrumbs/BreadcrumbsWithIcon.tsx
- apps/preview/nuxt/pages/showcases/Breadcrumbs/Breadcrumbs.vue
- apps/preview/nuxt/pages/showcases/Breadcrumbs/BreadcrumbsSeparator.vue
- apps/preview/nuxt/pages/showcases/Breadcrumbs/BreadcrumbsWithIcon.vue
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/146?modal=detail&selectedIssue=SFUI2-992
Last item is not a link
> fix: last item in breadcrumbs is not a link

- apps/preview/next/pages/showcases/Filters/FiltersPanel.tsx
- apps/preview/nuxt/pages/showcases/Filters/FiltersPanel.vue
Closes [SFUI2-907](https://vsf.atlassian.net/browse/SFUI2-907)
- Click on the entire row selects a filter.
- Color filter rings fixed.
[SFUI2-907]: https://vsf.atlassian.net/browse/SFUI2-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: filters label select

- package.json
- packages/config/tailwind/tsconfig.json
- packages/sfui/frameworks/react/tsconfig.json
- packages/sfui/frameworks/vue/composables/useTrapFocus/useTrapFocus.ts
- packages/sfui/frameworks/vue/tsconfig.json
- packages/sfui/shared/tsconfig.json
- packages/sfui/tw-plugin-peer-next/tsconfig.json
- packages/sfui/typography/tsconfig.json
https://vsf.atlassian.net/browse/SFUI2-1163
- `useTrapFocus` error `The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.`
- overwriting existing dists and proper defined `outDir`
> fix: errors during building packages [SFUI2-1163]

- apps/preview/nuxt/pages/showcases/Gallery/GalleryVertical.vue
thumbImage variable is non-existent in GalleryVertical anymore - looks like a rebase error between v2-develop and my assets branch
> fix: incorrect thumb images usage

- apps/preview/next/pages/showcases/Filters/FiltersPanel.tsx
- apps/preview/next/pages/showcases/Filters/Ratings.tsx
- apps/preview/nuxt/pages/showcases/Filters/FiltersPanel.vue
- apps/preview/nuxt/pages/showcases/Filters/Ratings.vue
https://vsf.atlassian.net/browse/SFUI2-767?atlOrigin=eyJpIjoiOGE2MmI3ZmMzYjBlNGFkZmIwZGZhODFhMzEwOGMxNmIiLCJwIjoiaiJ9
- It is a followup PR for RatingsList task
- added support for unselecting radios in filters
-
> feat: added support for unselecting radios

- apps/docs/components/hooks/useDropdown.md
- apps/docs/components/hooks/useScrollable.md
- apps/docs/components/hooks/useTrapFocus.md
- apps/preview/next/pages/showcases/MegaMenu/BaseMegaMenu.tsx
- apps/preview/next/pages/showcases/MegaMenu/MegaMenuNavigation.tsx
- apps/preview/nuxt/pages/showcases/MegaMenu/BaseMegaMenu.vue
- apps/preview/nuxt/pages/showcases/MegaMenu/MegaMenuNavigation.vue
- packages/sfui/frameworks/react/hooks/useDropdown/types.ts
- packages/sfui/frameworks/react/hooks/useDropdown/useDropdown.ts
- packages/sfui/frameworks/react/hooks/useTrapFocus/useTrapFocus.ts
- packages/sfui/frameworks/vue/composables/useTrapFocus/useTrapFocus.ts
https://vsf.atlassian.net/browse/SFUI2-1110
- fix focus trap inside megamenu blocks
- change `useTrapFocus` API with possibility of initial focus of `container`
- split `arrowKeysOn` into `arrowKeysLeftRight` and `arrowKeysUpDown`
- fix `useDropdown` and add `onCloseDeps` since internally `useKey` uses `useMemo` 
- change `/` url into `#` since in documentation when you click on desktop link it redirect to `/`
> fix: mega menu focusing [SFUI2-1110]

- packages/sfui/frameworks/react/hooks/useTrapFocus/useTrapFocus.ts
- packages/sfui/frameworks/vue/composables/useTrapFocus/useTrapFocus.ts
Closes #
With this [PR](https://github.com/vuestorefront/storefront-ui/pull/2722) option `arrowKeysOn` was broken for `useTrapFocus`
> fix: arrowKeysOn in useTrapFocus

- .github/workflows/ci.yml
- .github/workflows/release-changeset-changelog.yml
- .github/workflows/workflow-dispatch-changeset.yml
- package.json
Added 3 github actions
- Create changelog PR from changeset on every commit push into `v2-release/**` 
- Create Trigger if this changelog should be for release candidate (rc tag) or production (latest)
- If latest commit message in `v2-release/**` is `[ci] release rc` should run publish with tag `rc`
File `release-changeset-changelog.yml` job `create-release-changelog`
Run every time commit lands into `v2-release/**` branch and creates PR with new changelog either for RC or PROD changelog
File `ci.yml` job `release-next`
Runs only on `v2-release` when last pushed commit name is `[ci] release next` and publish release-candidate with tag `next`, this is benefitial because we can run publish after all `lint` `build` `vue-test` `react-test` checks …
> ci: add realase candidate pipeline action [SFUI2-1184]

- renovate.json
I've added a renovate config to the shared [.github](https://github.com/vuestorefront/.github) repo
> chore: use shared organization renovate config

- apps/preview/next/pages/showcases/Filters/Size.tsx
Closes #
Fixed typo in Size filter block.
> fix: filter sizes typo

- CHANGELOG.md
- packages/sfui/frameworks/nuxt/package.json
- yarn.lock
closes https://vsf.atlassian.net/browse/SFUI2-1237
closes #2793
> fix(nuxt): use @storefront-ui/vue as workspace dep [SFUI2-1237] #2793

- .github/workflows/exit-pre-mode-on-comment.yml
Github action that is triggered on comment creation to exit pre-release mode for changset, its run when:
- when comment is CREATED in PULL REQUEST, can be issue etc
- when comment value is `!prod-ready`
- when branch name starts with `v2-release/**`
NOTE: this PR will be merged directly into `v2` branch !!
> ci: exit pre-release changesets when comment created [SFUI2-1184]

- .yarn/patches/@changesets-assemble-release-plan-npm-5.2.3-296454a28f.patch
- package.json
- yarn.lock
`changesets` package has [bug](https://github.com/changesets/changesets/pull/847) therefor monkey patch has to be done for now
> chore: monkey patch changesets [SFUI2-1184]

- .github/workflows/ci.yml
- .github/workflows/generate-changelog-changeset.yml
Simplify process for creating changelog and publishing release candidate 
Enter and exit pre-release has to be manually
Enter `yarn changeset pre enter rc` -> when changelog PR merge -> auto publish
Exit `yarn changeset pre exit` -> when changelog PR merged -> nothing happens
> ci: release candidate workflow [SFUI2-1184]

- .github/workflows/ci.yml
https://vsf.atlassian.net/browse/SFUI2-1099
Closes #
Do not run coverage step for react/vue tests when run on contributor fork
> ci: contributor run no sonarcloud coverage [SFUI2-1099]

- apps/docs/tests/e2e/overviewCheck.cy.ts
- apps/docs/tests/fixtures/overviewblocks.json
- apps/docs/tests/fixtures/overviewcomponents.json
- apps/docs/tests/support/pageObject/OverviewVisible.PageObject.ts
Closes #
Automated tasks:
SFUI2 Homepage and some elements are visible
Go to Base component - > You can see overview of base components
Go to Blocks - > You can see overview of Blocks 
- [x ] Self code-reviewed
- [x ] Changes documented
- [x ] cypress tests created
> feat: add e2e test for blocks and component overview

- apps/preview/next/pages/showcases/Search/SearchBasic.tsx
- apps/preview/next/pages/showcases/Search/SearchWithButton.tsx
- apps/preview/next/pages/showcases/Search/SearchWithIcon.tsx
- apps/preview/nuxt/pages/showcases/Search/SearchBasic.vue
- apps/preview/nuxt/pages/showcases/Search/SearchWithButton.vue
- apps/preview/nuxt/pages/showcases/Search/SearchWithIcon.vue
Closes [#1205](https://vsf.atlassian.net/browse/SFUI2-1205)
Added bottom/up arrow handling when focused on the input field. Now it moves focus to the dropdown items.
> fix: search arrow key handling [SFUI2-1205]

- apps/docs/components/blocks/NavbarBottom.md
https://vsf.atlassian.net/browse/SFUI2-796
- adds callout to the `NavbarBottom` block explaining the usage of `Sf
> docs: add SfButton explanation on NavbarBottom

- .changeset/five-geese-serve.md
- .changeset/flat-birds-grab.md
- packages/sfui/frameworks/react/components/SfButton/SfButton.tsx
- packages/sfui/frameworks/vue/components/SfButton/SfButton.vue
https://vsf.atlassian.net/browse/SFUI2-1066?atlOrigin=eyJpIjoiMmNkZDU2MDgwMjY4NDVlM2E5MWNkMDRiNDNkMzExYmIiLCJwIjoiaiJ9
- adjusted paddings from 16px to 12px for large version of button.
-
> fix: breaking change - sfbutton padding size 

- apps/preview/next/pages/showcases/ProductCard/ProductCardVertical.tsx
- apps/preview/next/pages/showcases/ProductSlider/Basic.tsx
- apps/preview/nuxt/pages/showcases/ProductCard/ProductCardVertical.vue
- apps/preview/nuxt/pages/showcases/ProductSlider/Basic.vue
"Add to wishilist" button is designed with a ring (not a border). This issue was duplicated directly from ProductCard example, so I fixed it there as well
> fix: ring instead of border on add to wishlist

- apps/docs/components/blocks/Gallery.md
- apps/docs/components/blocks/ProductSlider.md
move accessibility notes higher on the documentation page
change name for the example to something more descriptive
> docs: accessibility notes should be closer to top of the page

- apps/docs/components/blocks/Gallery.md
- apps/docs/components/blocks/ProductSlider.md
- apps/preview/next/pages/showcases/ProductCard/ProductCardVertical.tsx
- apps/preview/next/pages/showcases/ProductSlider/Basic.tsx
- apps/preview/nuxt/pages/showcases/ProductCard/ProductCardVertical.vue
- apps/preview/nuxt/pages/showcases/ProductSlider/Basic.vue
Focus ring was not being displayed for image at all for ProductCard (and [it should be](https://www.figma.com/file/CWOkbpne0tDpSenT4ZEUTQ/%F0%9F%9B%A0-SFUI-2-%7C-Design-Kit-v2.4-(development)?type=design&node-id=14013%3A45717&t=yfc7Yt1fxaKSWAds-1)).
This issue got copied over to ProductSlider, so I fixed it there as well.
before:
after:
> fix: focus border around image is not visible

- apps/preview/next/next.config.mjs
- apps/preview/nuxt/nuxt.config.ts
https://vsf.atlassian.net/browse/SFUI2-1244
On windows file path is different than on linux
Windows: `file/path/component.tsx`
Linux `file\path\component.tsx`
> chore: fix nuxt next windows alias regex [SFUI2-1244]

- apps/docs/components/react/getting-started.md
- apps/docs/tests/fixtures/installationExamplesReact.json
- no issue
- temporarly removed astro from our react docs as it does not work (react-use is a commonJS module and does not work with Vite/Astro)
> chore: removed astro from react docs

- apps/docs/components/components/accordionitem.md
- apps/preview/next/pages/showcases/AccordionItem/AccordionAnimate.tsx
- apps/preview/nuxt/pages/showcases/AccordionItem/AccordionAnimate.vue
Closes #2561 
[SFUI2-965](https://vsf.atlassian.net/browse/SFUI2-965)
Adds an example of how to animate AccordionItem
Works for both single and multiple items open
https://github.com/vuestorefront/storefront-ui/assets/34419118/842096da-88ef-4d91-bb3f-e266b87acf99
https://github.com/vuestorefront/storefront-ui/assets/34419118/fcab9031-314f-405c-ab98-f711e1467bb7
[SFUI2-965]: https://vsf.atlassian.net/browse/SFUI2-965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add AccordionItem animation example

- apps/docs/components/blocks/NavbarTop.md
- apps/preview/next/pages/showcases/NavbarTop/NavbarTopFilledSimpleMobile.tsx
- apps/preview/next/pages/showcases/NavbarTop/NavbarTopSimpleMobile.tsx
- apps/preview/nuxt/pages/showcases/NavbarTop/NavbarTopFilledSimpleMobile.vue
- apps/preview/nuxt/pages/showcases/NavbarTop/NavbarTopSimpleMobile.vue
Closes # https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/69?modal=detail&selectedIssue=SFUI2-1172&assignee=5fcf86fca1d3f100684db8a5
Blocks for navbar top with simple mobile bar
> feat: navbar top simple mobile

- .changeset/sharp-scissors-heal.md
- apps/docs/components/components/scrollable.md
- apps/preview/next/pages/examples/SfScrollable.tsx
- apps/preview/nuxt/pages/examples/SfScrollable.vue
- packages/sfui/frameworks/react/components/SfScrollable/SfScrollable.tsx
- packages/sfui/frameworks/react/components/SfScrollable/types.ts
- packages/sfui/frameworks/vue/components/SfScrollable/SfScrollable.vue
Closes [#1170](https://vsf.atlassian.net/browse/SFUI2-1170)
SfScrollable - added props: `buttonPrevAriaLabel` and `buttonNextAriaLabel` to set the proper aria label for buttons
> fix: sfscrollable add props for buttons aria labels

- apps/preview/nuxt/pages/showcases/Card/CategoryCard.vue
- apps/preview/nuxt/pages/showcases/SelectDropdown/SelectDropdownPreselected.vue
Some vue blocks have `className` instead of `class`
> fix: vue blocks containing className

- packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
- packages/vue/src/stories/releases/v0.13.x/v0.13.7/v0.13.7.stories.mdx
Closes #2514 
Changed typo from `deafult` to `default`
> fix: typo in the prop section of SfProductCard

- .github/workflows/ci.yml
- .yarnrc.yml
https://vsf.atlassian.net/browse/SFUI2-1185
`yarn changeset publish` does not work as expected, it does not replace `workspace:*` into version - [GH issue](https://github.com/changesets/changesets/issues/432)
Publishing needs to be done manually 
- set config with correct credentials
Reviewer can check package.json that it has replaced versions of eg `@storefront-ui/shared` 
https://www.npmjs.com/package/@storefront-ui/vue/v/2.5.0-062c866?activeTab=code
> ci: npm publish

- packages/vue/src/components/organisms/SfCarousel/SfCarousel.vue
- packages/vue/src/components/organisms/SfGroupedProduct/SfGroupedProduct.vue
- packages/vue/src/components/organisms/SfHero/SfHero.vue
Closes #2405, #2400
closes https://vsf.atlassian.net/jira/software/c/projects/SFUI2/boards/146?selectedIssue=SFUI2-1261
Make sure that glide instance is properly destroyed when component unmounts
> fix: remove glide instance on component destroy [SFUI2-1261]

- .changeset/five-geese-serve.md
- packages/sfui/frameworks/react/components/SfButton/SfButton.tsx
- packages/sfui/frameworks/vue/components/SfButton/SfButton.vue
https://vsf.atlassian.net/browse/SFUI2-1226?atlOrigin=eyJpIjoiNjVhNTc3NjNlYWYyNGZiZDllMmYxZTcwYjk1NGRiZWUiLCJwIjoiaiJ9
- changed padding right from 14px to 12px
-
> fix: breaking change - sfbutton padding size  (#2815)

- apps/docs/components/.vuepress/components/TypographyList.vue
- apps/preview/next/pages/showcases/Banners/DisplayHorizontal.tsx
- apps/preview/next/pages/showcases/Banners/DisplayVertical.tsx
- apps/preview/next/pages/showcases/Banners/DisplayVerticalMultiple.tsx
- apps/preview/next/pages/showcases/Banners/Hero.tsx
- apps/preview/nuxt/pages/showcases/Banners/DisplayHorizontal.vue
- apps/preview/nuxt/pages/showcases/Banners/DisplayVertical.vue
- apps/preview/nuxt/pages/showcases/Banners/DisplayVerticalMultiple.vue
- apps/preview/nuxt/pages/showcases/Banners/Hero.vue
- packages/sfui/typography/index.ts
Closes [SFUI2-1246](https://vsf.atlassian.net/browse/SFUI2-1246)
This PR extends typography with 3 new classes:
- `typography-display-1`
- `typography-display-2`
- `typography-display-3`
[SFUI2-1246]: https://vsf.atlassian.net/browse/SFUI2-1246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add display typography

- packages/nuxt/cypress.json
- packages/nuxt/nuxt.config.js
- packages/nuxt/package.json
- packages/vue/babel.config.js
- packages/vue/index.js
- packages/vue/package.json
- yarn.lock
Closes #2364
closes https://vsf.atlassian.net/browse/SFUI2-1265
Updated babel preset via [vue-cli](https://cli.vuejs.org/migrations/migrate-from-v3.html#vue-cli-plugin-babel-vue-babel-preset-app)
> feat: upgrade babel presets to new version [SFUI2-1265]

- .changeset/fresh-emus-care.md
- packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx
- packages/sfui/frameworks/vue/components/SfSelect/SfSelect.vue
https://vsf.atlassian.net/browse/SFUI2-1226?atlOrigin=eyJpIjoiNzEwZDQ2Yzg5N2NiNDhkZWI1MWYxZDE3NjlkYzJhYjAiLCJwIjoiaiJ9
- adjusted paddings for select to 12px
-
> fix!: changed paddings in sfselect

- apps/docs/components/components/link.md
- changed structure of vue/react sections so the link can load properly
-
> fix: fixed issue with 404 on usage with next link in docs

- apps/docs/components/.vuepress/config.js
- apps/docs/components/react/browser-support.md
- apps/docs/components/vue/browser-support.md
https://vsf.atlassian.net/browse/SFUI2-1161
Adding browser support page in documentation
> docs: add browser support page [SFUI2-1161]

- apps/docs/development/testing.md
- apps/docs/tests/cypress.config.ts
- apps/docs/tests/package.json
- package.json
- turbo.json
- yarn.lock
https://vsf.atlassian.net/browse/SFUI2-933
Adding turbo workspace package `@storefront-ui/docs-tests` that can be run in pair with other processes. 
Add readme how to run cypress e2e test for docs locally without needing run everything manually
> test: add local setup for docs e2e tests [SFUI2-933]

- apps/docs/components/.vuepress/config.js
https://vsf.atlassian.net/browse/SFUI2-1161
Followup PR for original implementation, missing `vue` entry in navigation results in not showing item in nav
> docs: add missing entry for browser support in nav [SFUI2-1161]

- apps/docs/components/blocks/Tabs.md
- apps/preview/next/pages/showcases/Tabs/TabsBasic.tsx
- apps/preview/nuxt/pages/showcases/Tabs/TabsBasic.vue
Closes [SFUI2-1216](https://vsf.atlassian.net/browse/SFUI2-1216)
This PR adds a new block page – Tabs, with one basic example.
https://github.com/vuestorefront/storefront-ui/assets/34419118/3bd253d7-7401-4024-8a79-387428ba4d24
[SFUI2-1216]: https://vsf.atlassian.net/browse/SFUI2-1216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add Tabs block

- packages/sfui/frameworks/vue/components/SfButton/SfButton.vue
- packages/sfui/frameworks/vue/components/SfDrawer/SfDrawer.vue
- packages/sfui/frameworks/vue/components/SfInput/SfInput.vue
- packages/sfui/frameworks/vue/components/SfListItem/SfListItem.vue
- packages/sfui/frameworks/vue/components/SfModal/SfModal.vue
- packages/sfui/frameworks/vue/components/SfScrollable/SfScrollable.vue
Closes https://vsf.atlassian.net/browse/SFUI2-1283
add support for custom components to all of the tag props in our library
> fix: broaden tag prop typings in all components [SFUI2-1283]

- apps/preview/next/pages/examples/SfTextarea.tsx
- apps/preview/nuxt/pages/examples/SfTextarea.vue
Closes [#1296](https://vsf.atlassian.net/browse/SFUI2-1296)
Added classes for `disabled` and `readonly` states in order not to show hover styles.
> fix: hover on readonly and disabled

- apps/docs/components/blocks/Card.md
- apps/preview/nuxt/.eslintrc.js
- apps/preview/nuxt/pages/showcases/Banners/Hero.vue
- apps/preview/nuxt/pages/showcases/Card/CardDefault.vue
- apps/preview/nuxt/pages/showcases/Drawer/Placement.vue
- apps/preview/nuxt/pages/showcases/MegaMenu/MegaMenuNavigation.vue
- apps/preview/nuxt/pages/showcases/ProductCard/Details.vue
- apps/preview/nuxt/pages/showcases/ProductCard/ProductCardHorizontal.vue
- apps/preview/nuxt/pages/showcases/QuantitySelector/OutOfStock.vue
- apps/preview/nuxt/pages/showcases/QuantitySelector/QuantitySelector.vue
- apps/preview/nuxt/pages/showcases/QuantitySelector/Rounded.vue
- apps/preview/nuxt/pages/showcases/SelectDropdown/SelectDropdownDisabled.vue
- packages/config/eslint/package.json
- packages/config/eslint/vue.js
- packages/sfui/frameworks/react/components/SfSwitch/SfSwitch.tsx
- packages/sfui/frameworks/vue/components/SfAccordionItem/SfAccordionItem.vue
- packages/sfui/frameworks/vue/components/SfRatingButton/SfRatingButton.vue
- packages/sfui/frameworks/vue/components/SfSwitch/SfSwitch.vue
- yarn.lock
https://vsf.atlassian.net/browse/SFUI2-1192
Follow-up for already done eslint company config migration ticket. React has `a11y` plugin for eslint, this PR adds this as well into `vue` eslint
> chore: add a11y to vue eslint [SFUI2-1192]

- .changeset/short-lions-develop.md
- apps/docs/components/components/scrollable.md
- packages/sfui/frameworks/react/components/SfScrollable/SfScrollable.tsx
- packages/sfui/frameworks/vue/components/SfScrollable/SfScrollable.vue
https://vsf.atlassian.net/browse/SFUI2-1301
- unify styling in react and vue
- fix not assigning composable `getPrevButtonProps` and `getNextButtonProps` for disabled attribute 
- change behavior so it would match figma, hiding buttons  `floating` for `buttonsPlacement`
> fix(SfScrollable): floating disabled state, refactor [SFUI2-1301

- .changeset/four-elephants-wait.md
- apps/docs/components/components/select.md
- apps/preview/nuxt/pages/showcases/Filters/Category.vue
- apps/preview/nuxt/pages/showcases/Filters/Color.vue
- apps/preview/nuxt/pages/showcases/Filters/FiltersSidepanel.vue
- apps/preview/nuxt/pages/showcases/Filters/Sorting.vue
- apps/preview/nuxt/pages/showcases/Select/SelectInvalid.vue
- packages/sfui/frameworks/vue/components/SfSelect/SfSelect.vue
https://vsf.atlassian.net/browse/SFUI2-1300
SfSelect pass wrongly `modelValue`, as `value` prop and then `emits` state via `@onChange` which did not work 
[3e3ba8d0-4b59-47e1-8d5f-1ef1df271afb.webm](https://github.com/vuestorefront/storefront-ui/assets/2566152/d6982f3c-4f3e-4402-9fe3-91b25a9c25a7)
Wrong applying `value` in `sorting` block, it was served as Object when it should be String
Additionally some block used `as` instead of `tag` prop
> fix(SfSelect): correct usage of v-model [SFUI2-1300]

- .changeset/weak-terms-search.md
- packages/sfui/frameworks/react/components/SfScrollable/SfScrollable.tsx
https://vsf.atlassian.net/browse/SFUI2-1306
Changed `ariaLabel` attribute to `aria-label`.
> fix(SfScrollable): aria label casing [SFUI2-1306]

- .changeset/wise-bananas-build.md
- packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx
- packages/sfui/frameworks/vue/components/SfSelect/SfSelect.vue
- packages/tests/components/SfSelect/SfSelect.cy.tsx
https://vsf.atlassian.net/browse/SFUI2-1307
Removed redundant `selected` attribute from `SfSelect` placeholder. It caused a warning: Warning: Use the defaultValue or value props on `<select>` instead of setting selected on `<option>`
> fix(SfSelect): disabled state attributes [SFUI2-1307]

- .changeset/fast-pugs-warn.md
- packages/sfui/frameworks/react/components/SfBadge/SfBadge.tsx
- packages/sfui/frameworks/react/components/SfBadge/index.ts
- packages/sfui/frameworks/react/components/SfRadio/index.ts
- packages/sfui/frameworks/react/components/SfRatingButton/index.ts
Closes #
I just changed the import statement to point to the package
> fix: importing types from a local file instead of the package in SfBadge

- renovate.json
Closes #
Because we cannot update `eslint-config-next` dependency we have to disable auto update dependency by renovate. 
Why we cannot update it? because `eslint-config-next` internally it has 
```
"eslint-plugin-react-hooks": "5.0.0-canary-7118f5dd7-20230705"
``` 
as dependency https://github.com/vercel/next.js/blob/canary/packages/eslint-config-next/package.json#L21C5-L21C67 
Which cause 2 problems
1. For your internal config we use package `eslint-plugin-react-hooks` 4.9... so those 2 packages are incompatible
2. we cant update our internal config because they use `canary` which for me is bad practice to use version that is not stable
> chore: disable eslint-config-next rule for renovate

- renovate.json
https://github.com/vuestorefront/storefront-ui/issues/2958
Closes #
Possibly `#` breaks renovate config
> chore: update renovate.config

- apps/docs/tests/package.json
- apps/test/react/package.json
- apps/test/vue/package.json
- yarn.lock
Closes #
There seems to be issue with newest `ubuntu` version run on CI via `ubuntu-latest`, chrome is update to newest version that causes cypress failing https://github.com/cypress-io/cypress/issues/27804
> fix: update cypress version

- .changeset/rude-berries-beg.md
- packages/sfui/frameworks/vue/components/SfChip/SfChip.vue
- packages/sfui/frameworks/vue/components/SfInput/SfInput.vue
- packages/sfui/frameworks/vue/components/SfSelect/SfSelect.vue
- packages/sfui/frameworks/vue/components/SfTooltip/SfTooltip.vue
https://vsf.atlassian.net/browse/SV-222
Some components had wrong placement of v-bind, because of that user would not be able to overwrite some initial attributes, such as `data-testid`
> fix: binding on vue components [SV-222]

- apps/preview/nuxt/pages/showcases/Checkbox/CheckboxLeading.vue
- apps/preview/nuxt/pages/showcases/Textarea/TextareaAutoresize.vue
https://vsf.atlassian.net/browse/SFUI2-1305
REplacing `class-name` or `className` in vue blocks
> fix: change class-name attribute in vue blocks [SFUI2-1305]

- apps/preview/next/pages/showcases/Footer/FooterBasic.tsx
- apps/preview/nuxt/pages/showcases/Footer/FooterBasic.vue
https://vsf.atlassian.net/browse/SFUI2-1302
> fix: footer block semantic html structure [SFUI2-1302]

- apps/preview/next/pages/showcases/Filters/FiltersSidepanel.tsx
- apps/preview/next/pages/showcases/Filters/Price.tsx
- apps/preview/next/pages/showcases/Filters/Rating.tsx
- apps/preview/next/pages/showcases/Rating/RatingValues.tsx
- apps/preview/nuxt/pages/showcases.vue
- apps/preview/nuxt/pages/showcases/Filters/Category.vue
Fixing errors and warnings in showcase Nuxt and Next
Wrong attribute casing in `RatingValues.tsx`
Wrong usage of `Radio` in filter showcases
Missing key on Fragment
Fixing hydration for Nuxt sidebar, cause by `isNotIframe` window missing on Server side 
Fixing hydration for SfListItem https://github.com/vuestorefront/storefront-ui/issues/2962
> fix: showcase errors and warnings

- apps/preview/next/pages/showcases/Pagination/Pagination.tsx
- apps/preview/nuxt/pages/showcases/Pagination/Pagination.vue
Closes # https://vsf.atlassian.net/browse/SFUI2-1303
added min width for pagination buttons (as in figma they should be not less than 38px)
> fix: pagination buttons are too small

- .changeset/cyan-carpets-collect.md
- packages/sfui/frameworks/react/components/SfAccordionItem/SfAccordionItem.tsx
- packages/sfui/frameworks/react/components/SfSwitch/SfSwitch.tsx
- packages/sfui/frameworks/react/components/SfTextarea/SfTextarea.tsx
Closes #
Some react components still have wrong attribute inhertiance order
> fix: proper inherit attributes

- apps/docs/components/index.md
- apps/docs/components/tailwind.config.js
Closes #
Changes the Qwik background button to use a custom color since in Tailwind 2.x - JIT mode has to be enabled for arbitary values (`bg-[#whatever]`) to work.
> docs: fix qwik background colors

- apps/docs/components/.vuepress/config.js
- apps/docs/components/package.json
- yarn.lock
Closes #
- updates upstream vuepress theme to include alokai branding and a link to the up-to-date docs
> docs: add alokai docs link

- apps/docs/components/blocks/Banners.md
- apps/preview/next/pages/showcases/Banners/Hero.tsx
- apps/preview/nuxt/pages/showcases/Banners/Hero.vue
https://alokai.atlassian.net/browse/ES-387
current hero implementation is wrong for mobile devices - background image should try to cover whole element, but without changing it's aspect ratio
add description for best image sizes for hero background
Hero on mobile before:
after:
Description:
> fix(hero): backgroundImage should cover whole elements area on mobile [ES-387]

- apps/docs/components/components/content/AppSidebarTop.vue
- apps/docs/components/content/_blocks/Banners.md
- apps/docs/components/package.json
- apps/preview/next/pages/showcases/Banners/Hero.tsx
- apps/preview/nuxt/pages/showcases/Banners/Hero.vue
- yarn.lock
Closes #
- changes to `sf-docs-base` to adjust scroll behavior on page load
- make the `AppSidebarTop` component sticky so the framework selector is always visible
Both screenshots show the sidebar position on page load
> docs: update default sidebar scroll behavior

- apps/docs/components/nuxt.config.ts
- apps/preview/next/layouts/Examples.tsx
- apps/preview/nuxt/pages/examples.vue
- apps/preview/nuxt/pages/showcases.vue
Closes #
- uses `useRouter` to generate the sidebar instead of glob imports. The glob imports where resulting in over-importing all examples or showcases. Resulting in slower iframes and rate limiting in the docs
- prerenders the docs pages.
Before (255 requests)
After (25 requests)
> fix(preview): avoid glob import for nuxt-preview

- apps/docs/components/components/content/Generate.vue
Closes #
To further reduce the number of unnecessary requests per page, we can add `loading="lazy"`  to our embedded iframe examples.
> docs: add loading="lazy" to iframes

- renovate.json
Closes #
we do not want to have yarn 4 https://docs.renovatebot.com/configuration-options/#allowedversions
> chore: exclude renovate update to yarn v4

- packages/sfui/frameworks/react/vite.config.ts
- packages/sfui/frameworks/vue/vite.config.ts
Closes #
Weirdly while building react package ts picks up all tsconfigs and throws error e.g for docs not existing typings (needs to run `yarn nuxt prepare`), so we need to define root for tsconfig `vite-tsconfig-paths`, once its set up no errors and package is build properly
> chore: define ts config paths

- apps/docs/components/content/_components/scrollable.md
- apps/preview/next/pages/showcases/Gallery/GalleryHorizontal.tsx
- apps/preview/next/pages/showcases/Gallery/GalleryVertical.tsx
- apps/preview/next/pages/showcases/Scrollable/ScrollByOneItem.tsx
- apps/preview/nuxt/pages/showcases/Gallery/GalleryHorizontal.vue
- apps/preview/nuxt/pages/showcases/Gallery/GalleryVertical.vue
- apps/preview/nuxt/pages/showcases/Scrollable/ScrollByOneItem.vue
https://alokai.atlassian.net/browse/ES-157
when scrolling snapped galleries on mobile it's really easy to scroll two items with a single swipe
now always - single swipe = single item change
> docs: fix scrollable & gallery snapping [ES-157]

- apps/preview/nuxt/pages/showcases/Banners/Hero.vue
https://github.com/vuestorefront/unified-storefronts/pull/1237#issuecomment-2069309576
Closes #
Without w-full the image behaves weirdly when the container is not 100% width
> chore(hero): add w-full to image
